<title>loan System | Edit Module</title>
<?php 
	$cancel_url=$this->url(array(
		'module'=>'rsvacl',
		'controller'=>'acl',
		'action'=>'index',
	));

?>
 
<form action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">										
			if(this.validate()) {								
				return true;
			}
			return false;
	</script>
	<table cellspacing="20" style="margin: 0 auto; width: 450px">
		<tr>
			<td>
				<fieldset>
					<legend><strong>Module/Controller/Action</strong></legend>
					<table cellspacing="10" width="100%">
						<tr>
							<td align="center" valign="top">
								<table width="100%" cellspacing="10" >
								   <tr>
										<td>Label</td>
										<td width="300px">
											<input type="text" required="true" name="label" id="label" placeholder="label" 
											dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->acl_data['label'];?>"
											missingMessage="Label" class='fullside'/>
										</td>
									</tr>
									<tr><td style="height:5px;"></td></tr>
									<tr>
										<td>Module</td>
										<td width="300px">
											<input type="text" required="true" name="module" id="module" placeholder="Module" 
											dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->acl_data['module'];?>"
											missingMessage="Invalid Module!" class='fullside'/>
										</td>
									</tr>
									<tr><td style="height:5px;"></td></tr>
									<tr>
										<td>Contoller</td>
										<td>
											<input type="text" required="true" name="controller" id="controller" placeholder="Controller" 
											dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->acl_data['controller'];?>"
											missingMessage="Invalid Controller!" class='fullside'/>
										</td>
									</tr>
									<tr><td style="height:5px;"></td></tr>
									<tr>
										<td>Action</td>
										<td>
											<input type="text" required="true" name="action" id="action" placeholder="Action" 
											dojoType="dijit.form.ValidationTextBox" value="<?php echo $this->acl_data['action'];?>"
											missingMessage="Invalid Action!" class='fullside'/>
										</td>
									</tr>		
									<tr><td style="height:5px;"></td></tr>
									<tr>
										<td>Order</td>
										<td width="200px">
											<input type="text"  name="order" dojoType="dijit.form.TextBox" class='fullside' value="<?php echo $this->acl_data['rank'];?>"/>
										</td>
									</tr>
									<tr><td style="height:5px;"></td></tr>
									<tr>
										<td>Type</td>
										<td width="200px">
											<select class="fullside" name="type" dojoType="dijit.form.FilteringSelect" >
											    <option value="1" <?php if($this->acl_data['is_menu']==1) echo "selected='selected'"; ?> >MEMU</option>
												<option value="0" <?php if($this->acl_data['is_menu']==0) echo "selected='selected'"; ?> >NOT_MENU</option>
											</select>
										</td>
									</tr>
									<tr><td style="height:5px;"></td></tr>
									<tr>
										<td>Status</td>
										<td width="200px">
											<select class="fullside" name="status" dojoType="dijit.form.FilteringSelect" >
											    <option value="1" <?php if($this->acl_data['status']==1) echo "selected='selected'"; ?> >Active</option>
												<option value="0" <?php if($this->acl_data['status']==0) echo "selected='selected'"; ?> >Deactive</option>
											</select>
										</td>
									</tr>	
									<tr><td style="height:5px;"></td></tr>			
													
								</table>
							</td>							
						</tr>
					</table>	
				</fieldset>
			</td>			
		</tr>
		<tr>
			<td colspan="2" align="center">
				<input type="submit" value="រក្សាទុក" label="រក្សាទុក" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
			</td>
		</tr>
	</table>	
	<input type="hidden" name="user_type_id" value="<?php echo $this->user_edit['id'];?>" />
</form>

<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
</script>