<?php $filter = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$url = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-groupmember'));
$url_client = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-paymentschedules'));
$frm=$this->frm;
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("Guide Info");?></title>

<div style=" width:28cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
<div id="divPrint" style="width: 100%;">
<style>
.style{
	line-height: 20px;font-size: 10px !important;
	font-family: 'Khmer OS Battambang';
}
th{padding: 5px;}
</style>
<table style="font-family: 'Khmer OS Content'; width:100%;">
	<tr>
    	<td align="center">
    		<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
            	<tr>
                	<td width="20%"></td>
                	<td width="60%" valign="top">
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRANCH_TITLE");?></label></h2>
                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("Driver/Tour Guide Agreement Report");?></h2>
                	</td>
                    <td width="20%"></td>
                </tr> 
                <tr>
                	<td colspan="3">
		              </td>
		           </tr>   
            </table>
        </td>
    </tr>
    <tr>
    	<td>
            <table id="exportExcel" border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:10px; white-space: nowrap;" width="100%" cellspacing="0">
                 <tr bgcolor="#ccc" class="style" align="center" style="floafont-weight:bold; line-height: 14px; font-size:12px; padding:5px 0px; ">
                    <th >&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</th>
                    <th ><?php echo $tr->translate("Agreement Code");?></th>
                    <th ><?php echo $tr->translate("Owner Name");?></th>
                    <th ><?php echo $tr->translate("Customer Name");?></th>
                    <th ><?php echo $tr->translate("Booking No.");?></th>
                    <th ><?php echo $tr->translate("Incept Date");?></th>
                    <th ><?php echo $tr->translate("Return Date");?></th>
                    <th ><?php echo $tr->translate("Return Time");?></th>
                    <th ><?php echo $tr->translate("Period");?></th>
                    <th ><?php echo $tr->translate("Date");?></th>
                </tr>
               <?php 
               if(!empty($this->rows)) foreach($this->rows as $key =>$row){?>
					<tr align="center" style="line-height: 18px;">
						<td>&nbsp;<?php echo $key+1; ?>&nbsp;</td>
						<td align="left" >&nbsp;<a href="<?php echo $this->url(array('module'=>'report','controller'=>'pricing','action'=>'productagreement','id'=>$row['id']), null, true);?>"><?php echo $row['agreement_code']; ?></a>&nbsp;</td>
						<td align="left">&nbsp;<a href="<?php echo $this->url(array('module'=>'report','controller'=>'pricing','action'=>'productagreement','id'=>$row['id']), null, true);?>"><?php echo $row['owner_name'];?>&nbsp;</a></td>
						<td align="left">&nbsp;<a href="<?php echo $this->url(array('module'=>'report','controller'=>'pricing','action'=>'productagreement','id'=>$row['id']), null, true);?>"><?php echo $row['customer_name'];?>&nbsp;</a></td>
						<td align="center" style="line-height:15px;"><a href="<?php echo $this->url(array('module'=>'report','controller'=>'pricing','action'=>'productagreement','id'=>$row['id']), null, true);?>">&nbsp;<?php echo $row['booking_id'];?></a></td>	
						<td align="left"><span style="line-height:15px;">&nbsp;<?php echo $row['start_date']; ?></span>&nbsp;</td>	
						<td align="left"><span style="line-height:15px;">&nbsp;<?php echo date("d/m/Y",strtotime($row['finish_date'])); ?></span>&nbsp;</td>	
						<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo $row['return_time'] ?>&nbsp;</td>
						<td style="white-space:nowrap;">&nbsp;<?php echo $row['period']; ?>&nbsp;</td>
						<td style="white-space:nowrap;">&nbsp;<?php echo date("d-m-Y",strtotime($row['date_create'])); ?>&nbsp;</td>
					</tr>
				<?php } ?>
            </table>
            <br />
               <table align="center" width="100%">
				   <tr style="font-size: 12px;">
				        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
				        <th></th>
				        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
				   </tr>
			</table>
    	</td>
    </tr>
</table>
</div>
</div>