<?php $filter = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$url = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-groupmember'));
$url_client = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-paymentschedules'));
$frm=$this->frm_search;
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("Report Vehicle Agreement");?></title>
<div class="row">
	<div class="x_panel " >
		<form method="post">
			<div class="clearfix"></div>
				  <div class="form-group">
					<div class="col-md-2 col-xs-12 mg-10">
					  <?php echo $frm->getElement("search_text");?>
					</div>
					<div class="col-md-1 col-xs-12 ">
						<label class="control-label" style="padding-left: 5px;"><?php echo $tr->translate('Booking From')?>
			            </label>
					</div>
					<div class="col-md-2 col-xs-12 mg-10">
					  <?php echo $frm->getElement('from_book_date');?>
					</div>
					<div class="col-md-1 col-xs-12">
						<label class="control-label" style="padding-left: 5px;"><?php echo $tr->translate('To Booking')?>
			            </label>
					</div>
					<div class="col-md-2 col-xs-12 mg-10">
					  <?php echo $frm->getElement('to_book_date');?>
					</div>
				  </div>
				  <div class="form-group">
					  	<div class="col-md-2 col-xs-12 mg-10">
						  <?php echo $frm->getElement("customer");?>
						</div>
						<div class="col-md-1 col-xs-12">
							<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
						</div>
				  </div>
		</form>
		<div style=" width:28cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
			<div id="divPrint" style="width: 100%;">
				<style>
					.style{
						line-height: 20px;font-size: 10px !important;
						font-family: 'Khmer OS Battambang';
					}
					th{padding: 5px;}
					tr.header {
					    font-weight: bold;
					    line-height: 14px;
					    font-size: 12px;
					    background: #eee;
					}
					tr.header td {
					    padding: 5px;
					}
					tr td a{
						color:#000;
						text-decoration: none;
					}
				</style>
				<table style="font-family: 'Khmer OS Content'; width:100%;">
					<tr>
				    	<td align="center">
				    		<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
				            	<tr>
				                	<td width="20%"></td>
				                	<td width="60%" valign="top">
				                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRANCH_TITLE");?></label></h2>
				                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("Report Vehicle Agreement");?></h2>
				                	</td>
				                    <td width="20%"></td>
				                </tr> 
				                <tr>
				                	<td colspan="3">
						              </td>
						           </tr>   
				            </table>
				        </td>
				    </tr>
				    <tr>
				    	<td>
				            <table id="exportExcel" border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:10px; white-space: nowrap;" width="100%" cellspacing="0">
				                 <tr class="header">
				                    <td >&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
				                    <td ><?php echo $tr->translate("Agreement Code");?></td>
				                    <td ><?php echo $tr->translate("Owner Name");?></td>
				                    <td ><?php echo $tr->translate("Customer Name");?></td>
				                    <td ><?php echo $tr->translate("Booking No.");?></td>
				                    <td ><?php echo $tr->translate("Incept Date");?></td>
				                    <td ><?php echo $tr->translate("Return Date");?></td>
				                    <td ><?php echo $tr->translate("Return Time");?></td>
				                    <td ><?php echo $tr->translate("Period");?></td>
				                    <td ><?php echo $tr->translate("Date");?></td>
				                </tr>
				               <?php 
				               if(!empty($this->rows)) foreach($this->rows as $key =>$row){?>
									<tr align="center" style="line-height: 18px; background: #fff;">
										<td>&nbsp;<?php echo $key+1; ?>&nbsp;</td>
										<td align="left" >&nbsp;<a target="_blank" href="<?php echo $this->url(array('module'=>'report','controller'=>'pricing','action'=>'vehicleagreement','id'=>$row['id']), null, true);?>"><?php echo $row['agreement_code']; ?></a>&nbsp;</td>
										<td align="left">&nbsp;<a target="_blank" href="<?php echo $this->url(array('module'=>'report','controller'=>'pricing','action'=>'vehicleagreement','id'=>$row['id']), null, true);?>"><?php echo $row['owner_name'];?>&nbsp;</a></td>
										<td align="left">&nbsp;<a target="_blank" href="<?php echo $this->url(array('module'=>'report','controller'=>'pricing','action'=>'vehicleagreement','id'=>$row['id']), null, true);?>"><?php echo $row['customer_name'];?>&nbsp;</a></td>
										<td align="center" style="line-height:15px;"><a href="<?php echo $this->url(array('module'=>'report','controller'=>'pricing','action'=>'vehicleagreement','id'=>$row['id']), null, true);?>">&nbsp;<?php echo $row['booking_no'];?></a></td>	
										<td align="left"><span style="line-height:15px;">&nbsp;<?php echo $row['inception_date']; ?></span>&nbsp;</td>	
										<td align="left"><span style="line-height:15px;">&nbsp;<?php echo date("d/m/Y",strtotime($row['return_date'])); ?></span>&nbsp;</td>	
										<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo $row['return_time'] ?>&nbsp;</td>
										<td style="white-space:nowrap;">&nbsp;<?php echo $row['period']; ?>&nbsp;</td>
										<td style="white-space:nowrap;">&nbsp;<?php echo date("d-m-Y",strtotime($row['date_create'])); ?>&nbsp;</td>
									</tr>
								<?php } ?>
				            </table>
				            <br />
				               <table align="center" width="100%">
								   <tr style="font-size: 12px;">
								        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
								        <th></th>
								        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
								   </tr>
							</table>
				    	</td>
				    </tr>
				</table>
			</div>
		</div>
	</div>
</div>