<?php 
   $tr = Application_Form_FrmLanguages::getCurrentlanguage();
   echo $this->headTitle($tr->translate("BOOKING_VIEW"));
   $frm = $this->frm;
  
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dijit.form.DateTextBox");
dojo.require("dojo.data.ItemFileWriteStore"); 
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
 
dojo.require("dojo.html");
dojo.require("dojo.NodeList-manipulate");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.TimeTextBox");
dojo.require("dojo.parser");
 
</script>
<style>
div.cus_info{
	display: block;
    border: solid 1px #eee;
    clear: both;
    padding: 5px 2px;
    background: #f7f7f7;
}
.image-box.infor {
    padding: 2px;
    border: solid 1px #eee;
}		
span.span_title {
    min-width: 30%;
    display: inline-block;
    font-weight: 600;
}
h4.car_title {
    font-size: 14px;
    color: #156288;
    font-weight: 600;
    margin: 0;
    text-align: center;
    padding: 2px 0;
}

body{
	    color: #3f3f3f;
	    background: #156086;
	    font-weight: 400;
	    line-height: 1.471;
	    font-size: 96%;
	    font-family: "Helvetica Neue",Roboto,Arial,"Droid Sans",sans-serif,'Kh Battambang','Khmer Battambang';
	    font-size: 13px;
}

</style>
<div class="clearfix"></div>
<div class="x_panel">
	<div class="row">
		<form action="" method="post" id="addbookingrental" dojoType="dijit.form.Form">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					if(dijit.byId("delivery_time").get("value")==''){
						alert("Please Chose Time");
                        dijit.byId("delivery_time").focus();
						return false;
					}
					if(dijit.byId("driver").get("value")==0){
						alert("<?php echo $tr->translate('PLEASE_SELECT_DRIVER')?>");
						dijit.byId('driver').focus(); 
						return false;
					}
					loading();
					return true;
				} else {
					return false;
				}
			</script>
      	 <div class="col-md-12 col-xs-12 forms_padding">
	          <div class="x_panel">
	              <div class="x_title">
	                 <h2><i class="fa  fa-info-circle" aria-hidden="true"></i> <?php echo $tr->translate('BOOKING_VIEW')?></h2>
	                 <ul class="nav navbar-right panel_toolbox">
	                    <li>
	                    	<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
	                    </li>
	               	</ul>
               		<div class="clearfix"></div>
          		</div>
	       		<div class="x_content">
	       			<div class="col-md-8 col-sm-8 col-xs-12">
		                <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("BOOKING_NO")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('booking_no');?>
		                    	<input type="hidden" dojoType="dijit.form.TextBox" name="booking_id" id="booking_id" value="<?php echo $this->row['id'];?>" >
		                    	<input type="hidden" dojoType="dijit.form.TextBox" name="is_commssion_paid" id="is_commssion_paid" value="<?php echo $this->row['is_paid_commission'];?>" >
		                   </div>
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("CUSTOMER")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('customer');?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("BOOKING_DATE")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('booking_date');?>
		                   </div>
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("AGENCY")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('agency');?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("DELIVERY_DATE")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('delivery_date');?>
		                   </div>
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("DRIVER")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('driver');?>
		                   </div>
		                </div>
		                 <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("DELIVERY_TIME")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('delivery_time');?>
		                   </div>
			                 <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("VEHICLE_TYPE")?>
			                   </label>
			                   <div class="col-md-4 col-sm-4 col-xs-12">
			                    	<?php echo $frm->getElement('vehicle_type');?>
			                   </div>
		                </div>
		                <div class="form-group">
		                	<label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("FROM_LOCATION")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('from_location');?>
		                   </div>
		                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("DRIVER_FEE")?><?php //echo $tr->translate("VEHICLE")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php //echo $frm->getElement('vehicle');?>
		                    	<select name="vehicle" id="vehicle" dojoType="dijit.form.FilteringSelect" class="fullside" autoComplete="false" queryExpr="*${0}*" onchange="getCareInfoByid();"  style="display:none" >
								       <option value="0" label=" "><?php echo $tr->translate("SELECT_VEHICLE")?></option>
								       <?php if(!empty($this->cars)) foreach ($this->cars As $car){?>
								       <option value="<?php echo $car['id']?>" label=" "><?php echo $car['name']?></option>
								       <?php }?>
								</select>
								<?php echo $frm->getElement('driver_fee');?>
		                   </div>
		                </div>
		                 <div class="form-group">
		                	<label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("TO_LOCATION")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('to_location');?>
		                   </div>
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">
		                   		<?php echo $tr->translate("BOOKING_STATUS")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('working_status');?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("DESCRIPTION")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('remark');?>
		                   </div>
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name">
		                   			<?php echo $tr->translate("NOTE")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('note');?>
		                   </div>
		                </div>
		                  
		                <div class="text-center">
		                <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">  </label>
							<input type="button" value="GO_BACK" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
										iconClass="dijitIconUndo" onclick="window.history.back();" />
							<input class="button_success" type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" id="save_close" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 	
						</div>
	       			</div>
	       			<div class="col-md-4 col-sm-4 col-xs-12">
						<div class="title_form_blog " style=" margin: 0;">
	       					<h4 style=" font-size: 14px;"><i class="fa  fa-user" aria-hidden="true"></i> <?php echo $tr->translate('Driver Infomation')?></h4>
	       				</div>
	       				<div id="driver_html" class="cus_info col-md-12 col-sm-12 col-xs-12">
		       				<div class="col-md-4 col-sm-4 col-xs-12">
				               	<div class="image-box infor">
				               		<?php 
				               		$profile = $this->baseUrl().'/images/profile.jpg';
					               		if (!empty($this->driver_info['photo'])){
					               			$profile = $this->baseUrl().'/images/driverphoto/'.$this->driver_info['photo'];
					               		}
				               		?>
									<img id="profile_wiew" src="<?php echo $profile;?>" alt=""  />
								</div>
							</div>
							<div class="col-md-8 col-sm-8 col-xs-12">
								<ul class="list-unstyled">
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('NAME')?></span> : <span class="span_value"><?php if (!empty($this->driver_info['first_name'])){ echo $this->driver_info['first_name']." ".$this->driver_info['last_name'];}?></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('Gender')?></span> : <span class="span_value"><?php if (!empty($this->driver_info['sexs'])){ echo $this->driver_info['sexs'];}?></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('Nationality')?></span> : <span class="span_value"><?php if (!empty($this->driver_info['nationality'])){ echo $this->driver_info['nationality'];}?></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('PHONE')?></span> : <span class="span_value"><?php if (!empty($this->driver_info['tel'])){ echo $this->driver_info['tel'];}?></span>
                              		</li>
                              	</ul>
							</div>
						</div>
						<div class="clearfix"></div>
						
						
						
						
						<div class="title_form_blog " style=" margin: 0;">
	       					<h4 style=" font-size: 14px;"><i class="fa  fa-user" aria-hidden="true"></i> <?php echo $tr->translate('Customer Information')?></h4>
	       				</div>
	       				<div id="vehiclesss" class="cus_info col-md-12 col-sm-12 col-xs-12">
							<div class="col-md-8 col-sm-8 col-xs-12">
								<ul class="list-unstyled">
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('OTHER_BOOKING_NO')?></span> : <span class="span_value"><?php echo $this->row['payment_booking_no']?></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('CUSTOMER_NAME')?></span> : <span class="span_value"><?php echo $this->row['last_name']?></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('CUS_PHONE')?></span> : <span class="span_value"><?php echo $this->row['phone']?></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('CUS_EMAIL')?></span> : <span class="span_value"><?php echo $this->row['email']?></span>
                              		</li>
                              		 
                              	</ul>
							</div>
							 
							<div class="col-md-8 col-sm-8 col-xs-12">
								<ul class="list-unstyled">
								    <li>
                              			<h4 class="car_title" style="text-align: left;"><?php echo $tr->translate('Payment Information')?> :  </h4>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate("Company Price")?></span> :<span class="span_value" style="font-weight: 900;">&nbsp;<?php echo ($this->row['total']==0)?"":"$&nbsp;".number_format($this->row["total"],2);?></span>
                              		</li> 
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate("CARPRICE")?></span> :<span class="span_value"style="font-weight: 900;">&nbsp;<?php echo ($this->row['price']==0)?"":"$&nbsp;".number_format($this->row["price"],2);?></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate("OTHER_FEE")?></span> :<span class="span_value" style="font-weight: 900;">&nbsp;<?php echo ($this->row['other_fee']==0)?"":"$&nbsp;".number_format($this->row["other_fee"],2);?> </span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate("TOTAL_SERVICE")?></span> :<span class="span_value" style="font-weight: 900;">&nbsp;<?php echo ($this->row['total_service']==0)?"":"$&nbsp;".number_format($this->row["total_service"],2);?></span>
                              		</li>
                              		 <li>
                              			<span class="span_title"><?php echo $tr->translate("GRAND_TOTAL")?></span> :<span class="span_value" style="font-weight: 900;">&nbsp;<?php echo ($this->row['grand_total']==0)?"":"$&nbsp;".number_format($this->row["grand_total"],2);?></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate("NoPay")?></span> :<span class="span_value" style="font-weight: 900;">&nbsp;<?php echo ($this->row['paid']==0)?"":"$&nbsp;".number_format($this->row["paid"],2);?> </span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate("BALANCE")?></span> :<span class="span_value" style="font-weight: 900;">&nbsp;<?php echo ($this->row['balance']==0)?"":"$&nbsp;".number_format($this->row["balance"],2);?></span>
                              		</li>
                              		
                              	</ul>
							</div>
						</div>
						<div class="clearfix"></div>
						
						
	       			</div>
	       		</div>
       		</div>
  		 </div>
     </form>
</div>
</div>

<script type="text/javascript">
var care_typestore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->cars));?> );
require(["dojo/ready"], function(ready){
	ready(function(){
        if('<?php echo $this->row['driver_id'];?>'){
       	   dijit.byId("vehicle").attr("value",'<?php echo $this->row['vehicle_id'];?>');
           getDriverInfoByid();
           getCareInfoByid();
           dijit.byId("vehicle").hide();
        }
       
        dijit.byId("agency").attr("disabled", true);
		dijit.byId("booking_date").attr("disabled", true);
		dijit.byId("delivery_date").attr("disabled", true);
		 
		dijit.byId("to_location").attr("disabled", true);
		dijit.byId("from_location").attr("disabled", true);
		dijit.byId("customer").attr("disabled", true);
		dijit.byId("vehicle_type").attr("disabled", true);
		//dijit.byId("vehicle").attr("disabled", true);
		
	 
	});
});
  
/*
var urldriver_car="<?php //echo $this->url(array('module'=>'bookings','controller'=>'index','action'=>'getdrivercar'));?>";
function getDriver(type){
	if(type==1){
		var id = dijit.byId('driver').get('value');
	}else if(type=2){
		var id = dijit.byId('vehicle').get('value');
	}
	loading();
	dojo.xhrPost({
	    url: urldriver_car,
	    content:{
	     'id':id,'type':type
	     },
	    handleAs:"json",
	    load: function(data) {
	    	//document.getElementById('driver_html').innerHTML =data.driver;
	    	//document.getElementById('vehiclesss').innerHTML =data.vehicle;
	    	if(dijit.byId('driver').get('value')==data.driver_id ){
	    		document.getElementsByClassName("overlay")[0].style.display="none";
	    	}
	    	if(type==1){
	    		 dijit.byId('vehicle').set('value',data.vehicle_id);
	    	}else if(type=2){
	    		dijit.byId('driver').set('value',data.driver_id);
	    	}
	    },
	    error: function(err) {
	     alert(err);
	    }
   });
}
*/
 

var urldriver_car="<?php echo $this->url(array('module'=>'bookings','controller'=>'index','action'=>'getdrivercar'));?>";
function getDriverInfoByid(){
	
	var id = dijit.byId('driver').get('value');
	if(id==''){
		return false;
	}
	//loading();
	 
	dojo.xhrPost({
	    url: urldriver_car,
	    content:{
	     'id':id,
	     },
	    handleAs:"json",
	    load: function(data) {
	    	document.getElementById('driver_html').innerHTML =data.driver;
	    	if(dijit.byId('driver').get('value')==data.driver_id ){
	    		document.getElementsByClassName("overlay")[0].style.display="none";
	    	}
	    	//dijit.byId('driver').set('value',data.driver_id);
	    },
	    error: function(err) {
	     //alert(err);
	    }
   });
}


var url_car="<?php echo $this->url(array('module'=>'bookings','controller'=>'index','action'=>'getcar'));?>";
function getCareInfoByid(){
	var id = dijit.byId('vehicle').get('value');
	if( id==''){
		return false;
	}
	loading();
	dojo.xhrPost({
	    url: url_car,
	    content:{
	     'id':id,
	     },
	    handleAs:"json",
	    load: function(data) {
	    	//document.getElementById('vehiclesss').innerHTML =data;
	        document.getElementsByClassName("overlay")[0].style.display="none";
	    },
	    error: function(err) {
	     alert(err);
	    }
   });
}

function getPopupFormDriver(){
	dijit.byId("car_save").attr("disabled",false);
	driver = dijit.byId('driver').get('value');
	if(driver==-1){
		dijit.byId("pop_vehicle_type").show();
	}
}

function hideDriverPopUp(){
	dijit.byId("pop_vehicle_type").hide();
}

var vehicletype_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->drivers));?> );
var url_vehicletype = '<?php echo $this->url(array('module'=>'bookings','controller'=>'index','action'=>'add-driver')); ?>';
function addDriver(){
	if(dijit.byId('frm_vehicle_type').validate()){
		dijit.byId("car_save").attr("disabled",true);
		dojo.xhrPost({
			url: url_vehicletype,
			form: dojo.byId("frm_vehicle_type"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data.id,
					    name: dijit.byId('driver_name').get('value')+'('+data.driver_id+')',
				};			
				addDataToSelectbox(dijit.byId('driver'), vehicletype_store, Itemmake, data.id);
				dijit.byId('frm_vehicle_type').reset();
				dijit.byId("pop_vehicle_type").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}

</script>

<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_vehicle_type" title="<?php echo $tr->translate("DRIVER_NAME")?>">
		<form id='frm_vehicle_type' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td><?php echo $tr->translate("DRIVER_NAME")?></td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="driver_name" name="driver_name" value="" type="text"></td>
			</tr>
			<tr><td colspan="2" style="height: 5px;" ></td></tr>
			<tr>
				<td><?php echo $tr->translate("PHONE")?></td>
				<td><input dojoType="dijit.form.ValidationTextBox" id="driver_phone" name="driver_phone" value="" type="text"></td>
			</tr>
			<tr><td colspan="2" style="height: 5px;" ></td></tr>
			  
			<tr>
				<td><?php echo $tr->translate("Vehicle Ref.No")?></td>
				<td><input dojoType="dijit.form.ValidationTextBox"  id="vehicle_ref_no" name="vehicle_ref_no" value="" type="text"></td>
			</tr>
			<tr><td colspan="2" style="height: 5px;" ></td></tr>
			<tr>
				<td><?php echo $tr->translate("VEHICLE_TYPE")?></td>
				<td><?php echo $frm->getElement('car_type');?></td>
			</tr>
			<tr><td colspan="2" style="height: 5px;" ></td></tr>
			 
			<tr>
				<td colspan="2" align="center">
				<input type="button"  name="s_cancel" id="s_cancel"  label="<?php echo $tr->translate("CANCEL");?>" id="cancelButton" 
					dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel" onclick="hideDriverPopUp()"/>
				  	<input type="button"  label="<?php echo $tr->translate("SAVE")?>" dojoType="dijit.form.Button" id="car_save"
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addDriver();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>

