<?php 
   $tr = Application_Form_FrmLanguages::getCurrentlanguage();
   echo $this->headTitle($tr->translate("BOOKING_VIEW"));
   $frm = $this->frm;
?>
<script type="text/javascript">
dojo.ready(function(){
});
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.TimeTextBox");
dojo.require("dojo.parser");
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
</script>
<style>
div.cus_info{
	display: block;
    border: solid 1px #eee;
    clear: both;
    padding: 5px 2px;
    background: #f7f7f7;
}
.image-box.infor {
    padding: 2px;
    border: solid 1px #eee;
}		
span.span_title {
    min-width: 30%;
    display: inline-block;
    font-weight: 600;
}
h4.car_title {
    font-size: 14px;
    color: #156288;
    font-weight: 600;
    margin: 0;
    text-align: center;
    padding: 2px 0;
}
</style>
<div class="clearfix"></div>
<div class="x_panel">
	<div class="row">
		<form action="" method="post" id="addbookingrental" dojoType="dijit.form.Form">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					if(dijit.byId("driver").get("value")==0){
						alert("<?php echo $tr->translate('PLEASE_SELECT_DRIVER')?>");
						dijit.byId('driver').focus(); 
						return false;
					}
					loading();
					return true;
				} else {
					return false;
				}
			</script>
      	 <div class="col-md-12 col-xs-12 forms_padding">
	          <div class="x_panel">
	              <div class="x_title">
	                 <h2><i class="fa  fa-info-circle" aria-hidden="true"></i> <?php echo $tr->translate('BOOKING_VIEW')?></h2>
	                 <ul class="nav navbar-right panel_toolbox">
	                    <li>
	                    	<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
	                    </li>
	               	</ul>
               		<div class="clearfix"></div>
          		</div>
	       		<div class="x_content">
	       			<div class="col-md-8 col-sm-8 col-xs-12">
		                <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("BOOKING_NO")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('booking_no');?>
		                    	<input type="hidden" dojoType="dijit.form.TextBox" name="booking_id" id="booking_id" value="<?php echo $this->row['id'];?>" >
		                    	<input type="hidden" dojoType="dijit.form.TextBox" name="is_commssion_paid" id="is_commssion_paid" value="<?php echo $this->row['is_paid_commission'];?>" >
		                   </div>
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("CUSTOMER")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('customer');?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("BOOKING_DATE")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('booking_date');?>
		                   </div>
		                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("FLY_NO")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('fly_no');?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("DELIVERY_DATE")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('delivery_date');?>
		                   </div>
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("AGENCY")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('agency');?>
		                   </div>
		                  
		                </div>
		                 <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("DELIVERY_TIME")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('delivery_time');?>
		                   </div>
		                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("DRIVER")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('driver');?>
		                   </div>
		                 
		                </div>
		                <div class="form-group">
		                	<label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("FROM_LOCATION")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('from_location');?>
		                   </div>
		                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("VEHICLE")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('vehicle');?>
		                   </div>
		                </div>
		                 <div class="form-group">
		                	<label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("TO_LOCATION")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('to_location');?>
		                   </div>
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("DRIVER_FEE")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('driver_fee');?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("REMARK")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('remark');?>
		                   </div>
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("BOOKING_STATUS")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('working_status');?>
		                   </div>
		                </div>
		                  
		                <div class="text-center">
							<input type="button" value="GO_BACK" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
										iconClass="dijitIconUndo" onclick="window.history.back();" />
							<input class="button_success" type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" id="save_close" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 	
							<input class="button_success" type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" id="save_new" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
									
						</div>
	       			</div>
	       			<div class="col-md-4 col-sm-4 col-xs-12">
						<div class="title_form_blog " style=" margin: 0;">
	       					<h4 style=" font-size: 14px;"><i class="fa  fa-user" aria-hidden="true"></i> <?php echo $tr->translate('Driver Infomation')?></h4>
	       				</div>
	       				<div id="driver_html" class="cus_info col-md-12 col-sm-12 col-xs-12">
		       				<div class="col-md-4 col-sm-4 col-xs-12">
				               	<div class="image-box infor">
				               		<?php 
				               		$profile = $this->baseUrl().'/images/profile.jpg';
					               		if (!empty($this->driver_info['photo'])){
					               			$profile = $this->baseUrl().'/images/driverphoto/'.$this->driver_info['photo'];
					               		}
				               		?>
									<img id="profile_wiew" src="<?php echo $profile;?>" alt=""  />
								</div>
							</div>
							<div class="col-md-8 col-sm-8 col-xs-12">
								<ul class="list-unstyled">
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('NAME')?></span> : <span class="span_value"><?php if (!empty($this->driver_info['first_name'])){ echo $this->driver_info['first_name']." ".$this->driver_info['last_name'];}?></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('Gender')?></span> : <span class="span_value"><?php if (!empty($this->driver_info['sexs'])){ echo $this->driver_info['sexs'];}?></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('Nationality')?></span> : <span class="span_value"><?php if (!empty($this->driver_info['nationality'])){ echo $this->driver_info['nationality'];}?></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('PHONE')?></span> : <span class="span_value"><?php if (!empty($this->driver_info['tel'])){ echo $this->driver_info['tel'];}?></span>
                              		</li>
                              	</ul>
							</div>
						</div>
						<div class="clearfix"></div>
	       			</div>
	       		</div>
       		</div>
  		 </div>
     </form>
</div>
</div>

<script type="text/javascript">
require(["dojo/ready"], function(ready){
	ready(function(){
        if('<?php echo $this->row['driver_id'];?>'){
        	getDriver(1);
        }
        dijit.byId("agency").attr("disabled", true);
		dijit.byId("booking_date").attr("disabled", true);
		dijit.byId("delivery_date").attr("disabled", true);
		 
		dijit.byId("to_location").attr("disabled", true);
		dijit.byId("from_location").attr("disabled", true);
		dijit.byId("customer").attr("disabled", true);
		dijit.byId("fly_no").attr("disabled", true);
		dijit.byId("vehicle").attr("disabled", true);
		
	 
	});
});
  

var urldriver_car="<?php echo $this->url(array('module'=>'bookings','controller'=>'index','action'=>'getdrivercar'));?>";
function getDriver(type){
	if(type==1){
		var id = dijit.byId('driver').get('value');
	}else if(type=2){
		//var id = dijit.byId('vehicle').get('value');
	}
	loading();
	dojo.xhrPost({
	    url: urldriver_car,
	    content:{
	     'id':id,'type':type
	     },
	    handleAs:"json",
	    load: function(data) {
	    	document.getElementById('driver_html').innerHTML =data.driver;
	    	//document.getElementById('vehiclesss').innerHTML =data.vehicle;
	    	if(dijit.byId('driver').get('value')==data.driver_id ){
	    		document.getElementsByClassName("overlay")[0].style.display="none";
	    	}
	    	if(type==1){
	    		// dijit.byId('vehicle').set('value',data.vehicle_id);
	    	}else if(type=2){
	    		dijit.byId('driver').set('value',data.driver_id);
	    	}
	    },
	    error: function(err) {
	     alert(err);
	    }
   });
}

</script>
