<?php 
   $tr = Application_Form_FrmLanguages::getCurrentlanguage();
   echo $this->headTitle($tr->translate("BOOKING"));
   $frm = $this->frm;
   $ser_detail=$this->ser_detail;
  
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dijit.form.DateTextBox");
dojo.require("dojo.data.ItemFileWriteStore"); 
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
 
dojo.require("dojo.html");
dojo.require("dojo.NodeList-manipulate");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.TimeTextBox");
dojo.require("dojo.parser");
 
</script>
<style>
div.cus_info{
	display: block;
    border: solid 1px #eee;
    clear: both;
    padding: 5px 2px;
    background: #f7f7f7;
}
.image-box.infor {
    padding: 2px;
    border: solid 1px #eee;
}		
span.span_title {
    min-width: 30%;
    display: inline-block;
    font-weight: 600;
}
h4.car_title {
    font-size: 14px;
    color: #156288;
    font-weight: 600;
    margin: 0;
    text-align: center;
    padding: 2px 0;
}
</style>
<div class="clearfix"></div>
<div class="x_panel">
	<div class="row">
		<form action="" method="post" id="addbookingrental" dojoType="dijit.form.Form">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					var customer = dijit.byId('customer').get('value');
					if(customer==0){
						alert("<?php echo $tr->translate('PLEASE_SELECT_CUSTOMER')?>");
						dijit.byId('customer').focus(); 
						return false;
					}
					var total_paid = dijit.byId('total_paid').get('value');
					if(total_paid>0){
						var payment_method = dijit.byId('payment_method').get('value');
						if(payment_method==0){
							alert("<?php echo $tr->translate('PLEASE_SELECT_PAYMENT_METHOD')?>");
							dijit.byId('payment_method').focus(); 
							return false;
						}
					}
					if(dijit.byId("from_location").get("value")==0){
                      	alert("<?php echo $tr->translate('CHOOSE_LOCTION')?>");
							dijit.byId('from_location').focus();
							return false;
					}
					if(dijit.byId("to_location").get("value")==0){
                      		alert("<?php echo $tr->translate('CHOOSE_LOCTION')?>");
							dijit.byId('to_location').focus();
							return false;
					}
					var rowId = $('#record_row').val();
    				if(rowId!=''){ 
						var rowIDArray = rowId.split(',');
						for(var n = 0; n < rowIDArray.length; n++){
						var service = dijit.byId('service'+rowIDArray[n]).get('value');
						if(service==0){
							alert("<?php echo $tr->translate('SELECT_SERVICE')?>");
							dijit.byId('service'+rowIDArray[n]).focus();
							return false;
							}
						}
					}
					loading();
					return true;
				} else {
					return false;
				}
			</script>
      	 <div class="col-md-12 col-xs-12 forms_padding">
	          <div class="x_panel">
	              <div class="x_title">
	                 <h2><i class="fa fa-edit" aria-hidden="true"></i> <?php echo $tr->translate('CARRENTALBOOKING')?></h2>
	                 <ul class="nav navbar-right panel_toolbox">
	                    <li>
	                    	<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
	                    </li>
	               	</ul>
               		<div class="clearfix"></div>
          		</div>
	       		<div class="x_content">
	       			<div class="col-md-8 col-sm-8 col-xs-12">
		                <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("BOOKING_NO")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                  	 	<input type="hidden" dojoType="dijit.form.TextBox" name="booking_id" id="booking_id" value="<?php echo $this->row['id'];?>" >
								<input type="hidden" dojoType="dijit.form.TextBox" name="is_commssion_paid" id="is_commssion_paid" value="<?php echo $this->row['is_paid_commission'];?>" >
		                    	<?php echo $frm->getElement('booking_no');?>
		                   </div>
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("OTHER_BOOKING_NO")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('other_booking_no');?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("BOOKING_DATE")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('booking_date');?>
		                   </div>
		                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("CUSTOMER_NAME")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('cus_name');?>
		                    	<!-- <input id="dept" />  -->
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("DELIVERY_DATE")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('delivery_date');?>
		                   </div>
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("CUS_PHONE")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('cus_phone');?>
		                   </div>
		                  
		                </div>
		                 <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("DELIVERY_TIME")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('delivery_time');?>
		                   </div>
							<label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("CUS_EMAIL")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('cus_email');?>
		                   </div>
		                 
		                </div>
		                <div class="form-group">
		                	<label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("FROM_LOCATION")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('from_location');?>
		                   </div>
		                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("AGENCY")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('agency');?>
		                   </div>
		                </div>
		                 <div class="form-group">
		                	<label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("TO_LOCATION")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('to_location');?>
		                   </div>
		                  <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("VEHICLE_TYPE")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<!--<?php echo $frm->getElement('vehicle');?>-->
		                    	<?php echo $frm->getElement('vehicle_type');?>
		                   </div>
		                </div>
		                <div class="form-group">
		                	<label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("DESCRIPT")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('remark');?>
		                   </div>
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('note');?>
		                   </div>
		                </div>
		                <div class="title_form_blog">
		               		<h4><i class="fa  fa-money" aria-hidden="true"></i> <?php echo $tr->translate('PRICE_INFORMATION')?></h4>
		               </div>
		               <div class="form-group">
		               	   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("GRAND_TOTAL")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('total');?>
		                   </div>
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("CAR_RENT_FEE")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('price');?>
		                   </div>
		                   
		                  
		                </div>
		                <div class="form-group">
		                	<label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("OTHER_FEE")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('other_fee');?>
		                   </div>
		                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("COMMISSION_FEE")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('commision_fee');?>
		                   </div>
		                   
		                </div>
		                <div class="title_form_blog">
		               		<h4><i class="fa  fa-money" aria-hidden="true"></i> <?php echo $tr->translate('PAYMENT_INFORMATION')?></h4>
		               </div>
		                <div class="form-group">
		                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("PAYMENT_METHOD")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('payment_method');?>
		                   </div>
		                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("TOTAL_PAYMENT")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('total_payment');?>
		                   </div>
		                </div>
		               <div class="form-group">
		                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("PAYMENT_NOTE")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('payment_note');?>
		                   </div>
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("TOTAL_PAID")?>
		                   </label>
		                   <div class="col-md-2 col-sm-2 col-xs-12">
		                   <?php echo $frm->getElement('total_paid');?>
		                   </div>
		                   <div class="col-md-2 col-sm-2 col-xs-12">
		                   <?php echo $frm->getElement('paid_status');?>
		                   </div>
		                </div>
		                <div class="form-group">
		                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php //echo $tr->translate("")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	
		                   </div>
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("BALANCE")?>
		                   </label>
		                   <div class="col-md-2 col-sm-2 col-xs-12">
		                    	<?php echo $frm->getElement('balance');?>
		                   </div>
		                   <div class="col-md-2 col-sm-2 col-xs-12">
		                    	<?php echo $frm->getElement('balanc_status');?>
		                   </div>
		                </div>
		                <div class="text-center">
							<input type="button" value="GO_BACK" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
										iconClass="dijitIconUndo" onclick="window.history.back();" />
							<input class="button_success" type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" id="save_close" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 	
							 
						</div>
	       			</div>
	       			<div class="col-md-4 col-sm-4 col-xs-12">
	       				<div class="clearfix"></div>
						<div class="title_form_blog " style=" margin: 0;">
	       					<h4 style=" font-size: 14px;"><i class="fa  fa-user" aria-hidden="true"></i> <?php echo $tr->translate('Service Information')?></h4>
	       				</div>
	       				<div id="service" class="cus_info col-md-12 col-sm-12 col-xs-12">
		       				 <div class="form-group">
					                <div class="col-md-12 col-sm-12 col-xs-12">
					                	<div style="clear: both;"></div>
										<input type="hidden" dojoType="dijit.form.TextBox" id="record_row" name="record_row" />
										<div  id="store_record"></div>
										 <input  iconClass="dijitEditorIcon dijitEditorIconSave" type="button" onClick="addPockage();" label=" <?php echo $tr->translate("ADD_SERVICE")?>" dojoType="dijit.form.Button"/>
					                </div>
				               </div>
						</div>
	       			<!-- 
	       				<div class="title_form_blog " style=" margin: 0;">
	       					<h4 style=" font-size: 14px;"><i class="fa  fa-user" aria-hidden="true"></i> <?php echo $tr->translate('CUSTOMER_INFO')?></h4>
	       				</div>
	       				<div id="cus_info" class="cus_info col-md-12 col-sm-12 col-xs-12">
		       				<div class="col-md-4 col-sm-4 col-xs-12">
				               	<div class="image-box infor">
									<img id="profile_wiew" src="<?php echo $this->baseUrl().'/images/profile.jpg';?>" alt=""  />
								</div>
							</div>
							<div class="col-md-8 col-sm-8 col-xs-12">
								<ul class="list-unstyled">
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('NAME')?></span> : <span class="span_value"></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('Gender')?></span> : <span class="span_value"></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('Nationality')?></span> : <span class="span_value"></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('PHONE')?></span> : <span class="span_value"></span>
                              		</li>
                              	</ul>
							</div>
						</div>
						 -->
						<div class="clearfix"></div>
						<div class="title_form_blog " style=" margin: 0;">
	       					<h4 style=" font-size: 14px;"><i class="fa  fa-user" aria-hidden="true"></i> <?php echo $tr->translate('AGENCY_INFO')?></h4>
	       				</div>
	       				<div id="agent_info" class="cus_info col-md-12 col-sm-12 col-xs-12">
		       				<div class="col-md-4 col-sm-4 col-xs-12">
				               	<div class="image-box infor">
									<img id="profile_wiew" src="<?php echo $this->baseUrl().'/images/profile.jpg';?>" alt=""  />
								</div>
							</div>
							<div class="col-md-8 col-sm-8 col-xs-12">
								<ul class="list-unstyled">
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('NAME')?></span> : <span class="span_value"></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('Gender')?></span> : <span class="span_value"></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('Nationality')?></span> : <span class="span_value"></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('PHONE')?></span> : <span class="span_value"></span>
                              		</li>
                              	</ul>
							</div>
						</div>
						
						<div class="clearfix"></div>
						<div class="title_form_blog " style=" margin: 0;">
	       					<h4 style=" font-size: 14px;"><i class="fa  fa-car" aria-hidden="true"></i> <?php echo $tr->translate('Vehicle Infomation')?></h4>
	       				</div>
	       				<!--  
	       				<div id="vehiclesss" class="cus_info col-md-12 col-sm-12 col-xs-12">
	       					<h4 class="car_title"></h4>
		       				<div class="col-md-4 col-sm-4 col-xs-12">
				               	<div class="image-box infor">
									<img id="profile_wiew" src="<?php echo $this->baseUrl().'/images/no_car.png';?>" alt=""  />
								</div>
							</div>
							<div class="col-md-8 col-sm-8 col-xs-12">
								<ul class="list-unstyled">
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('Vehicle Ref.No.')?></span> : <span class="span_value"></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('YEAR')?></span> : <span class="span_value"></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('Color')?></span> : <span class="span_value"></span>
                              		</li>
                              	</ul>
							</div>
						</div>
						-->
						<div class="clearfix"></div>
	       			</div>
	       		</div>
       		</div>
  		 </div>
     </form>
</div>
</div>
 
<script type="text/javascript">

var url="<?php echo $this->url(array('module'=>'bookings','controller'=>'index','action'=>'getcustomer'));?>";
function getCustomer(){
	var id = dijit.byId('customer').get('value');
	if(id=='' || id==0){
		return false;
	}
	loading();
	dojo.xhrPost({
	    url: url,
	    content:{
	     'customer':id
	     },
	    handleAs:"json",
	    load: function(data) {
	    	document.getElementById('cus_info').innerHTML =data;
			document.getElementsByClassName("overlay")[0].style.display="none";
	    },
	    error: function(err) {
	     alert(err);
	    }
	   });
}
var urlagent="<?php echo $this->url(array('module'=>'bookings','controller'=>'index','action'=>'getagent'));?>";
function getAgent(){
	var id = dijit.byId('agency').get('value');
	if(id=='' || id==0){
		return false;
	}
	loading();
	dojo.xhrPost({
	    url: urlagent,
	    content:{
	     'agency':id
	     },
	    handleAs:"json",
	    load: function(data) {
	    	document.getElementById('agent_info').innerHTML =data;
			document.getElementsByClassName("overlay")[0].style.display="none";
	    },
	    error: function(err) {
	     alert(err);
	    }
	   });
}

var urldriver_car="<?php echo $this->url(array('module'=>'bookings','controller'=>'index','action'=>'getdrivercar'));?>";
function getDriver(type){
	if(type==1){
		//var id = dijit.byId('driver').get('value');
	}else if(type=2){
		var id = dijit.byId('vehicle').get('value');
	}
	loading();
	dojo.xhrPost({
	    url: urldriver_car,
	    content:{
	     'id':id,'type':type
	     },
	    handleAs:"json",
	    load: function(data) {
	    	
	    	//document.getElementById('driver_html').innerHTML =data.driver;
	    	document.getElementById('vehiclesss').innerHTML =data.vehicle;
	    	//if(dijit.byId('driver').get('value')==data.driver_id && dijit.byId('vehicle').get('value')==data.vehicle_id){
	    		document.getElementsByClassName("overlay")[0].style.display="none";
	    	//}
	    	if(type==1){
	    		 dijit.byId('vehicle').set('value',data.vehicle_id);
	    	}else if(type=2){
	    		//dijit.byId('driver').set('value',data.driver_id);
	    	}
	    	
			
	    	
	    },
	    error: function(err) {
	     alert(err);
	    }
   });
}

function CalculateTotal(){
	var total = dijit.byId('total').get('value');
	var other_fee = dijit.byId('other_fee').get('value');
	var price = dijit.byId('price').get('value');
	var commision_fee = dijit.byId('commision_fee').get('value');
    totals=Number(total)+Number(other_fee);

    dijit.byId("price").attr("value",totals);
    dijit.byId("total_payment").attr("value",totals);
    getPice();
    netTotal();
}

function getPice(){
	var total = dijit.byId('total').get('value');
	var other_fee = dijit.byId('other_fee').get('value');
	var price = dijit.byId('price').get('value');
	 totals=Number(total)+Number(other_fee);
	 result=Number(totals)-price;
	 dijit.byId("commision_fee").attr("value",result);
	 calculatebalance();
}

function netTotal() {
	var netTotal=0;
	total=0;
	var rowId = $('#record_row').val();
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		netTotal += dijit.byId('price_'+rowIDArray[n]).get('value');
	}
	total=Number(dijit.byId("total").get("value"))+Number(dijit.byId("other_fee").get("value"));
	netTotal=Number(netTotal)+Number(total);
	dijit.byId('total_payment').attr('value',netTotal);
	dijit.byId('balance').attr('value',netTotal);
 }

function calculatebalance(){
	var total = dijit.byId('total_payment').get('value');
	var total_paid = dijit.byId('total_paid').get('value');
	if(total_paid>total){
		total_paid = total;
		dijit.byId('total_paid').set('value',total.toFixed(2));
	}
	var balance = total - total_paid;
	dijit.byId('balance').set('value',balance.toFixed(2));
}
function settotal(){
	var other_fee = dijit.byId('other_fee').get('value');
	var total = dijit.byId('total').get('value');
	dijit.byId('total_payment').set('value',total.toFixed(2));
	total = total -other_fee;
	if(total<0){
		total = 0;
	}
	dijit.byId('price').set('value',total.toFixed(2));
	dijit.byId('commision_fee').set('value',0);
	netTotal();
}


</script>

<script type="text/javascript"> 
require(["dojo/ready"], function(ready){
	ready(function(){
		oldPockage();
		//getCustomer();
		getAgent();
		getDriver();
	});
});

service_booking = '<?php echo $this->service_booking;?>';
function addNewRecord(){
	dojo.query("#store_record").append('');
	tmp='<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
	tmp+='<tr style="background:#eee; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	tmp+='</table>';
	dojo.query("#store_record").append(tmp);
	thead='<th style="text-align:center;"><?php echo $tr->translate('DELETE');?></th>';
	thead+='<th style="text-align:center;"><?php echo $tr->translate('NUM');?></th>';
	thead+='<th style="text-align:center;"><?php echo $tr->translate('SERVICE_NAME');?></th>';
	thead+='<th style="text-align:center;"><?php echo $tr->translate('PRICE');?></th>';
	thead+='<th style="text-align:center;"><?php echo $tr->translate('NOTE');?></th>';
	fund_title=1;
	dojo.query("#head_title").append(thead);	
	dijit.byId('record_row').attr('value','');
	addPockage();
}

r=0;
function addPockage(){
	r++;
	tmp='<tr style="border:1px solid #ccc;" id="row_guide'+r+'">'
	tmp+="</tr>";
		dojo.query("#t_amountmoneytype").append(tmp);

	temp='<td style="width:30px !important;text-align:center;" ><img style="cursor:pointer" onclick="deleteRecord('+r+');CalculateTotal()" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"  ></td>';	
	temp+='<td align="center">'+r+'</td>';
	temp+='<td><select  style="width:120px !important;" id="service'+r+'" name="service'+r+'" dojoType="dijit.form.FilteringSelect" onchange="getServicePopup('+r+')">'+service_booking+'</select></td>';
	temp+='<td><input   dojoType="dijit.form.NumberTextBox" class="fullside" required="true" name="price_'+r+'" id="price_'+r+'" value="" type="text" onkeyup="CalculateTotal()" ></td>';
	temp+='<td><input   dojoType="dijit.form.TextBox" class="fullside"  name="note_'+r+'" id="note_'+r+'" value="" type="text" ></td>';
	
	dojo.html.set(dojo.byId("row_guide"+r),temp, {
	    parseContent: true,
	});
	if(dijit.byId("record_row").get('value')!="") {
		var ids = dijit.byId("record_row").value;
		dijit.byId("record_row").attr('value',ids+','+r);
	} else { dijit.byId("record_row").attr('value',r);}
}

function oldPockage(){
	dojo.query("#store_record").append('');
	tmp='<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
	tmp+='<tr style="background:#eee; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	tmp+='</table>';
	dojo.query("#store_record").append(tmp);
	thead='<th style="text-align:center;"><?php echo $tr->translate('DELETE');?></th>';
	thead+='<th style="text-align:center;"><?php echo $tr->translate('NUM');?></th>';
	thead+='<th style="text-align:center;"><?php echo $tr->translate('SERVICE_NAME');?></th>';
	thead+='<th style="text-align:center;"><?php echo $tr->translate('PRICE');?></th>';
	thead+='<th style="text-align:center;"><?php echo $tr->translate('NOTE');?></th>';
	fund_title=1;
	dojo.query("#head_title").append(thead);	
	dijit.byId('record_row').attr('value','');
	
	<?php  if(!empty($ser_detail)) foreach ($ser_detail As $ser){?>
	r++;
	tmp='<tr style="border:1px solid #ccc;" id="row_guide'+r+'">'
	tmp+="</tr>";
		dojo.query("#t_amountmoneytype").append(tmp);

	temp='<td style="width:30px !important;text-align:center;" ><img style="cursor:pointer" onclick="deleteRecord('+r+');CalculateTotal()" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"  ></td>';	
	temp+='<td align="center">'+r+'</td>';
	temp+='<td><select  style="width:120px !important;" id="service'+r+'" name="service'+r+'" dojoType="dijit.form.FilteringSelect" onchange="getServicePopup('+r+')">'+service_booking+'</select></td>';
	temp+='<td><input   dojoType="dijit.form.NumberTextBox" class="fullside" required="true" name="price_'+r+'" id="price_'+r+'" value="" type="text" onkeyup="CalculateTotal()" ></td>';
	temp+='<td><input   dojoType="dijit.form.TextBox" class="fullside"  name="note_'+r+'" id="note_'+r+'" value="" type="text" ></td>';
	
	dojo.html.set(dojo.byId("row_guide"+r),temp, {
	    parseContent: true,
	});
	if(dijit.byId("record_row").get('value')!="") {
		var ids = dijit.byId("record_row").value;
		dijit.byId("record_row").attr('value',ids+','+r);
	} else { dijit.byId("record_row").attr('value',r);}
	dijit.byId("service"+r).attr("value",'<?php echo  $ser['service_id']?>');
	dijit.byId("price_"+r).attr("value",'<?php echo  $ser['total_amount']?>');
	dijit.byId("note_"+r).attr("value",'<?php echo  $ser['description']?>');
	
  <?php }?>
}

function deleteRecord(index){
	var ids =dijit.byId('record_row').value;
	if(ids.length=='' || ids.length==null){
		dijit.byId('record_row').attr('value','');
		dojo.query("#row_guide"+ids).remove();
	}else{
		var arrays = ids.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		dijit.byId('record_row').attr('value',strings);
		dojo.query("#row_guide"+index).remove();
	}
}

function getLocationPopUp($type){
	if($type==1){
		$("#str_value").val(1);
	}else{
		$("#str_value").val(2);
	}
	if(dijit.byId('from_location').get('value')==-1 || dijit.byId('to_location').get('value')==-1){
		dijit.byId("pop_frm_location").show();
	}
}

function getAgencyPopUp(){
	dijit.byId("a_save").attr("disabled",false);
	if(dijit.byId('agency').get('value')==-1){
		dijit.byId("pop_frm_agency").show();
	}
}

function getCustomerPopUp(){
	dijit.byId("c_save").attr("disabled",false);
	if(dijit.byId('customer').get('value')==-1){
		dijit.byId("pop_frm_customer").show();
	}
}

function hideCustomerPopUp(){
	dijit.byId("pop_frm_customer").hide();
}
function hideAgencyPopUp(){
	dijit.byId("pop_frm_agency").hide();
}
function hideLocationPopUp(){
	dijit.byId("pop_frm_location").hide();
}
function hideServicePopUp(){
	dijit.byId("pop_frm_service").hide();
}

var custype_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->cus_all));?> );
var url_customerttype = '<?php echo $this->url(array('module'=>'bookings','controller'=>'index','action'=>'addcustomer')); ?>';
function addCustomet(){
	if(dijit.byId('frm_customer').validate()){
		dijit.byId("c_save").attr("disabled",true);
		dojo.xhrPost({
			url:url_customerttype,
			form: dojo.byId("frm_customer"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data.id,
					    name: dijit.byId('name_en').get('value')+'('+data.cus_code+')',
				};			
				addDataToSelectbox(dijit.byId('customer'), custype_store, Itemmake, data.id);
				dijit.byId('frm_customer').reset();
				dijit.byId("pop_frm_customer").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}

var agency_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->agency_all));?> );
var url_agency = '<?php echo $this->url(array('module'=>'bookings','controller'=>'index','action'=>'addagency')); ?>';
function addAgency(){
	if(dijit.byId('frm_agency').validate()){
		dijit.byId("a_save").attr("disabled",true);
		dojo.xhrPost({
			url:url_agency,
			form: dojo.byId("frm_agency"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data.id,
					    name: dijit.byId('last_name').get('value')+'('+data.cus_code+')',
				};			
				addDataToSelectbox(dijit.byId('agency'), agency_store, Itemmake, data.id);
				dijit.byId('frm_agency').reset();
				dijit.byId("pop_frm_agency").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}

var location_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->location_all));?> );
var url_location = '<?php echo $this->url(array('module'=>'bookings','controller'=>'index','action'=>'addlocation')); ?>';
function addLocation(){
	if(dijit.byId('frm_location').validate()){
		dojo.xhrPost({
			url:url_location,
			form: dojo.byId("frm_location"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data.id,
					    name: dijit.byId('location_name').get('value'),
				};			
				if(data.str_value==1){
					addDataToSelectbox(dijit.byId('from_location'), location_store, Itemmake, data.id);
				}else{
					addDataToSelectbox(dijit.byId('to_location'), location_store, Itemmake, data.id);
				}
				dijit.byId('frm_location').reset();
				dijit.byId("pop_frm_location").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}

var service_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->services));?> );
var url_service = '<?php echo $this->url(array('module'=>'bookings','controller'=>'index','action'=>'addservice')); ?>';
function addSerice(){
	if(dijit.byId('frm_service').validate()){
		dijit.byId("s_save").attr("disabled",true);
		dojo.xhrPost({
			url:url_service,
			form: dojo.byId("frm_service"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
					    name: dijit.byId('service_name').get('value'),
				};			
				addDataToSelectbox(dijit.byId('service'+$("#new_index_service").val()), service_store, Itemmake, data);
				dijit.byId('frm_service').reset();
				dijit.byId("pop_frm_service").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}

function getServicePopup(r){
	dijit.byId("s_save").attr("disabled",false);
	$("#new_index_service").val(r);
	if(dijit.byId('service'+r).get('value')==-1){
		dijit.byId("pop_frm_service").show();
	}
}

function getPopupFormVehicleType(){
	dijit.byId("car_save").attr("disabled",false);
	vehicle_type = dijit.byId('vehicle_type').get('value');
	if(vehicle_type==-1){
		dijit.byId("pop_vehicle_type").show();
	}
}

var vehicletype_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->rows_veh_typasname));?> );
var url_vehicletype = '<?php echo $this->url(array('module'=>'vehicle','controller'=>'vehicletype','action'=>'addvehiceltype')); ?>';
function addvehicleType(){
	if(dijit.byId('frm_vehicle_type').validate()){
		dijit.byId("car_save").attr("disabled",true);
		dojo.xhrPost({
			url: url_vehicletype,
			form: dojo.byId("frm_vehicle_type"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
					    name: dijit.byId('vehicletype_title').get('value')
				};			
				addDataToSelectbox(dijit.byId('vehicle_type'), vehicletype_store, Itemmake, data);
				dijit.byId('frm_vehicle_type').reset();
				dijit.byId("pop_vehicle_type").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}

var urlbook_no="<?php echo $this->url(array('module'=>'bookings','controller'=>'index','action'=>'checkbookno'));?>";
function checkBookNo(){
	var book_no = dijit.byId('other_booking_no').get('value');
	if(book_no==''){
		return false;
	}
	dojo.xhrPost({
	    url: urlbook_no,
	    content:{
	     'book_no':book_no, 
	     },
	    handleAs:"json",
	    load: function(data) {
	    	if(data.id){
		    	alert("This Number have already!!!");
		    	dijit.byId("other_booking_no").attr("value","");
		    	dijit.byId("other_booking_no").focus();
	    	}else{
	    	}
	    },
	    error: function(err) {
	     alert(err);
	    }
   });
}

</script>
<!-- popup customer -->
<?php $c_typ=$this->frm_client;?>
<div class="dijitHidden" >
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_frm_customer" title="<?php echo $tr->translate("ADD_CUSTOMER")?>">
		<form id='frm_customer' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table  style="width:400px;">
			<tr>
				<td><?php echo $tr->translate("TITLE")?></td>
				<td><?php echo $c_typ->getElement('title');?><br/></td>
			</tr>
			
			<tr><td colspan="2" style="height: 5px;" ></td></tr>
			<tr>
				<td><?php echo $tr->translate("CUSTOMER_NAME")?> </td>
				<td><?php echo $c_typ->getElement('name_en');?><br/></td>
			</tr>
			<tr><td colspan="2" style="height: 5px;" ></td></tr>
			<tr>
				<td><?php echo $tr->translate("SEX")?> </td>
				<td><?php echo $c_typ->getElement('sex');?><br/></td>
			</tr>
			<tr><td colspan="2" style="height: 5px;" ></td></tr>
			<tr>
				<td><?php echo $tr->translate("PHONE")?> </td>
				<td><?php echo $c_typ->getElement('phone');?><br/></td>
			</tr>
			<tr><td colspan="2" style="height: 5px;" ></td></tr>
			<tr>
				<td><?php echo $tr->translate("EMAIL")?> </td>
				<td><?php echo $c_typ->getElement('email');?><br/></td>
			</tr>
			<tr><td colspan="2" style="height: 5px;" ></td></tr>
			<tr>
				<td colspan="2" align="center">
					<input type="button"  label="<?php echo $tr->translate("CANCEL");?>" id="cancelButton" 
					dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel" onclick="hideCustomerPopUp()"/>
				  	<input type="button"  label="<?php echo $tr->translate("SAVE")?>" dojoType="dijit.form.Button" id="c_save"
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addCustomet();"/>
				</td>
				
			</tr>
		</table>
		
		</form>
	</div>
</div>

<!-- popup agency -->
<div class="dijitHidden" >
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_frm_agency" title="<?php echo $tr->translate("ADD_AGENCY")?>">
		<form id='frm_agency' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table  style="width:400px;">
			 
			<tr><td colspan="2" style="height: 5px;" ></td></tr>
			<tr>
				<td><?php echo $tr->translate("CUSTOMER_NAME")?> </td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="last_name" name="last_name" value="" type="text" class="fullside"></td>
			</tr>
			<tr><td colspan="2" style="height: 5px;" ></td></tr>
			<tr>
				<td><?php echo $tr->translate("SEX")?> </td>
				<td><select name="a_sex" id="a_sex" dojoType="dijit.form.FilteringSelect" class="fullside" autoComplete="false" queryExpr="*${0}*" >
					       <option value="1" label=" "><?php echo $tr->translate("Male")?></option>
					        <option value="2" label=" "><?php echo $tr->translate("Female")?></option>
					</select><br/>
				</td>
			</tr>
			<tr><td colspan="2" style="height: 5px;" ></td></tr>
			<tr>
				<td><?php echo $tr->translate("PHONE")?> </td>
				<td><input dojoType="dijit.form.TextBox" required="true" id="a_phone" name="a_phone" value="" type="text" class="fullside"><br/></td>
			</tr>
			<tr><td colspan="2" style="height: 5px;" ></td></tr>
			<tr>
				<td><?php echo $tr->translate("EMAIL")?> </td>
				<td><input dojoType="dijit.form.TextBox" required="true" id="a_email" name="a_email" value="" type="text" class="fullside"><br/></td>
			</tr>
			<tr><td colspan="2" style="height: 5px;" ></td></tr>
			<tr>
				<td colspan="2" align="center">
					<input type="button" name="a_cancel" id="a_cancel" label="<?php echo $tr->translate("CANCEL");?>" id="cancelButton" 
					dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel" onclick="hideAgencyPopUp()"/>
				  	<input type="button" name="a_save" id="a_save" label="<?php echo $tr->translate("SAVE")?>" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addAgency();"/>
				</td>
			</tr>
		</table>
		
		</form>
	</div>
</div>

<!-- popup location -->
<?php $c_typ=$this->frm_location;?>
<div class="dijitHidden" >
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_frm_location" title="<?php echo $tr->translate("ADD_LOCATION")?>">
		<form id='frm_location' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table  style="width:400px;">
			<tr>
				<td><?php echo $tr->translate("Location")?></td>
				<td><?php echo $c_typ->getElement('location_name');?><br/></td>
			</tr>
			<tr><td colspan="2" style="height: 5px;" ></td></tr>
			<tr>
				<td><?php echo $tr->translate("Province")?></td>
				<td><?php echo $c_typ->getElement('province_name');?><br/></td>
			</tr>
			<tr><td colspan="2" style="height: 5px;" ></td></tr>
			<tr>
				<td><?php echo $tr->translate("Description")?> </td>
				<td><input dojoType="dijit.form.TextBox" required="true" id="descript" name="descript" value="" type="text" class="fullside"><br/></td>
			</tr>
			<tr><td colspan="2" style="height: 5px;" ></td></tr>
			 <input type="hidden" name="str_value"   id="str_value" value="" />
  			<tr>
				<td colspan="2" align="center">
					<input type="button"  name="l_cancel" id="l_cancel"  label="<?php echo $tr->translate("CANCEL");?>" id="cancelButton" 
					dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel" onclick="hideLocationPopUp()"/>
				  	<input type="button"  name="l_save" id="l_save" label="<?php echo $tr->translate("SAVE")?>" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addLocation();"/>
				</td>
				
			</tr>
		</table>
		</form>
	</div>
</div>

<!-- popup service -->
<?php $s_frm=$this->frm_service;?>
<div class="dijitHidden" >
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_frm_service" title="<?php echo $tr->translate("ADD_SERVICE")?>"  >
		<form id='frm_service' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table  style="width:400px;">
			<tr>
				<td><?php echo $tr->translate('SERVICE_NAME')?></td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="service_name" name="service_name" value="" type="text" class="fullside"><br/></td>
			</tr>
			<tr><td colspan="2" style="height: 5px;" ></td></tr>
			<tr>
				<td><?php echo $tr->translate('DESCRIPTION')?></td>
				<td><input dojoType="dijit.form.TextBox" required="true" id="s_des" name="s_des" value="" type="text" class="fullside"><br/></td>
			</tr>
			<tr><td colspan="2" style="height: 5px;" ></td></tr>
			<tr>
				<td><?php echo $tr->translate('SERVICE_TYPE')?> </td>
				<td><?php echo $s_frm->getElement('service_type');?><br/></td>
			</tr>
			<tr><td colspan="2" style="height: 5px;" ></td></tr>
			 <input type="hidden" name="new_index_service"   id="new_index_service" value="" />
  			<tr>
				<td colspan="2" align="center">
					<input type="button"  name="s_cancel" id="s_cancel"  label="<?php echo $tr->translate("CANCEL");?>" id="cancelButton" 
					dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconCancel" onclick="hideServicePopUp()"/>
				  	<input type="button"  name="s_save" id="s_save" label="<?php echo $tr->translate("SAVE")?>" dojoType="dijit.form.Button" 
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addSerice();"/>
				</td>
				
			</tr>
		</table>
		</form>
	</div>
</div>

<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_vehicle_type" title="<?php echo $tr->translate("Add Vehicle Type")?>">
		<form id='frm_vehicle_type' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td><?php echo $tr->translate("TITLE")?></td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="vehicletype_title" name="vehicletype_title" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="<?php echo $tr->translate("SAVE")?>" dojoType="dijit.form.Button" id="car_save"
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addvehicleType();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>