<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<?php $frm =  $this->frm_search;

$db_s=new Bookings_Model_DbTable_DbServiceType();
?>
<title><?php echo $tr->translate("Car Booking");?></title>
<style>
.dropdown {
    position: relative;
    display: inline-block;
}

.dropdown-content {
    display: none;
    position: absolute;
    background-color: #f1f1f1;
    min-width: 60px;
    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
    z-index: 1;
}

.dropdown-content a {
    color: black;
    padding: 12px 16px;
    text-decoration: none;
    display: block;
}

.dropdown-content a:hover {background-color: #ddd}

.dropdown:hover .dropdown-content {
    display: block;
}

.dropdown:hover .dropbtn {
    background-color: #3e8e41;
}
</style>
<script type="text/javascript">
dojo.ready(function(){
	 $('select[name="datatable-responsive_length"]').val('50');
	 $('select[name="datatable-responsive_length"]').change();
	 //dijit.byId("date_type").attr("value",2);
	 dijit.byId("status").set("value",1);
});
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.TimeTextBox");
 
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
</script>
<script type="text/javascript">
   
 

 </script>
<div class="row">
	<div class="x_panel" >
		 <div class="blog_form_title">
		 	<h4><i class="fa fa-book" aria-hidden="true"></i> <?php echo $tr->translate("Car Booking")?></h4>
		 </div>
			<form id="list" name="list" action="<?php echo $this->url(array('module'=>'bookings','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
			  	<div class="clearfix"></div>
				  <div class="form-group">
					<div class="col-md-2 col-xs-12 mg-12">
					  <?php echo $frm->getElement("search_text");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-12">
					   <?php echo $frm->getElement("agency_search");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-12">
					   <?php echo $frm->getElement("driver_search");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-12">
					   <?php echo $frm->getElement("customer");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-12">
					   <?php echo $frm->getElement("vehicle_type");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-12">
					 <?php echo $frm->getElement("working_status");?>
					</div>
				  </div>
				  <div class="clearfix"></div>
				  <div class="form-group">
					<div class="col-md-2 col-xs-12 mg-12">
					 <?php echo $frm->getElement('from_book_date');?>
					</div>
					<div class="col-md-2 col-xs-12 mg-12">
					   <?php echo $frm->getElement('to_book_date');?>
					</div>
					<div class="col-md-2 col-xs-12 mg-12">
					    <?php echo $frm->getElement("start_time");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-12">
					   <?php echo $frm->getElement("delivery_time");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-12">
					   <?php echo $frm->getElement("date_type");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-12">
					   <?php echo $frm->getElement("status");?>
					</div>
				  </div>
				   <div class="clearfix"></div>
				   
				  <div class="form-group">
					 <!-- <label class="control-label col-md-11 col-sm-11 mg-12" for="first-name">  </label> -->
					<div class="col-md-1 mg-12">
							<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				  </div>
				  <div class="clearfix"></div>
			</form>
    	 <div class="x_panel">
	    	<div class="x_content">
	    		<table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
		    		<thead>
		    		  <tr>  
		    		  	  <th><?php echo $tr->translate("NUM")?></th> 
		    		      <th><?php echo $tr->translate("BOOKING_NO")?></th> 
		    		      <th><?php echo $tr->translate("BOOKING_DATE")?> </th> 
		    	          <th><?php echo $tr->translate("DELIVERY_DATE")?></th> 
		    	          <th><?php echo $tr->translate("DELIVERY_TIME")?></th> 
		    	          <th><?php echo $tr->translate("OTHER_BOOKING_NO")?></th>
		    		      <th><?php echo $tr->translate("FROM_LOCATION")?> </th> 
		    	          <th><?php echo $tr->translate("TO_LOCATION")?></th> 
		                  <th><?php echo $tr->translate("CUSTOMER_NAME")?></th>
		                  <th><?php echo $tr->translate("CUS_PHONE")?></th> 
		    	          <th><?php echo $tr->translate("CUS_EMAIL")?></th> 
		    	          <th><?php echo $tr->translate("VEHICLE_TYPE")?></th> 
		    	          <th><?php echo $tr->translate("NoPay")?> </th> 
		    	          <th><?php echo $tr->translate("Company Price")?> </th> 
		    	          <th><?php echo $tr->translate("CARPRICE")?> </th> 
		    	          <th><?php echo $tr->translate("BALANCE")?> </th> 
		    	          <th><?php echo $tr->translate("GRAND_TOTAL")?> </th> 
		    	          <th><?php echo $tr->translate("AGENCY_NAME")?> </th> 
		    	          
		    	          <th><?php echo $tr->translate("COMMISSION_FEE")?></th> 
		    	          
		    	           <th><?php echo $tr->translate("Other Service Type")?> </th> 
		    	          
		    	          <th><?php echo $tr->translate("DRIVER")?> </th> 
		    	          <th><?php echo $tr->translate("DRIVER_FEE")?></th> 
		    	          <th><?php echo $tr->translate("BOOKING_STATUS")?> </th> 
		    	           <th><?php echo $tr->translate("NOTE")?> </th> 
		    	          <th><?php echo $tr->translate("STATUS")?> </th> 
		    	          <th><?php echo $tr->translate("USER")?></th> 
		    	          <th><?php echo $tr->translate("STATUS")?></th> 
		             </tr>
		             </thead>
			     <tbody>
				     <?php 
				     $date_late='';$duplicate='';$cus_dubplicate='';$color='';$paid_color='';$agen_color='';$drive_color='';
				     $room_no='';$cus_name='';$book_no_color=''; if(!empty($this->rows)) foreach ($this->rows As $key=>$rs){
				          if($rs['status_working']==0){
				          	if (strtotime($rs['delivey_date']) <= time() && $rs['status_working']==0) {
				          		$status_working='style="background: #ff0f0f57 !important;"';
				          		$color='#ff0f0f57';
				          	} else {
				          		$status_working='style="background:#c6ffda"';
				          		$color='#c6ffda';
				          	}
				          }else if($rs['status_working']==1){
				          	$status_working='style="background:#fff"';
				          	$color='#fff';
				          }else{
				          	$status_working='style="background:#a59e9e"';
				          	$color='#a59e9e';
				          }
				           
				          if($rs['balance_after']==0 ){
				          	$paid_color='style="background:#c2d9ef"';
				          }else{
				          	$paid_color='';
				          }
				          
				          //check agency payment 
				          if($rs['is_paid_commission']==1 ){
				          	$agen_color='style="background:#33FF6E"';
				          }else{
				          	$agen_color='';
				          }
				          
				          //check driver payment
				          if($rs['is_paid_to_driver']==1 ){
				          	$drive_color='style="background:#33FF6E"';
				          }else{
				          	$drive_color='';
				          }
				          
				          $room_no=$rs['check_book_no'];$cus_name=$rs['check_name'];
				          $doupli_cat=$db_s->checkNumberBooking($rs['numbooking']);
				          $cusdubplicate=$db_s->checkCustomerBooking($rs['check_name']);
				          if($doupli_cat['number_book']>=2 ){
				          	$duplicate='background: #ffff66 !important;';
				          }else{
				          	$duplicate='';
				          }
				          
				          if($cusdubplicate['cus_name']>=2 ){
				          	$cus_dubplicate='background: #ffff66 !important;';
				          }else{
				          	$cus_dubplicate='';
				          }
				     	?>
				     <tr class=" alternate  normal"   onclick="setColor(this,'lightgrey','<?php echo $color;?>')" <?php echo $status_working;?>>
				       <td class="text-center"> <?php echo $key+1?></td>
				       <td class="text-center"> <?php echo $rs['booking_no']?></td> 
				       <td><?php echo date("d-M-Y H:i",strtotime($rs['create_date']));?> </td> 
				       <td class="text-center"> <?php echo date("D, d-M-Y",strtotime($rs['delivey_date']));?> </td>
				       <td class="text-center"> <?php echo $rs['delivey_time']?> </td>
				       <td class="text-center" style="text-align:left; <?php echo $duplicate;?>" > 
				       				<div class="dropdown">
									  <span class="glyphicon glyphicon-triangle-bottom"></span>
									  <div class="dropdown-content">
									    <a  target="_blank" href="<?php echo $this->baseUrl();?>/bookings/index/edit/id/<?php echo $rs["id"]?>"><?php echo $tr->translate("EDIT")?></a>
									    <a  target="_blank" style="color: #333;text-decoration: none;" href="<?php echo $this->baseUrl();?>/bookings/index/bookview/id/<?php echo $rs["id"]?>"><?php echo $tr->translate("PREPARE_CAR")?></a>
									    <a  href="<?php echo $this->baseUrl();?>/bookings/index/delete/id/<?php echo $rs["id"]?>"><?php echo $tr->translate("DELETE")?></a>
									    <a   href="<?php echo $this->baseUrl();?>/bookings/index/view/id/<?php echo $rs["id"]?>"><?php echo $tr->translate("VIEW")?></a>
									  </div>
									</div>
				       <?php echo $rs['payment_booking_no']?></td> 
				       <td  > <?php echo $rs['from_location']?></td> 
				       <td  ><?php echo $rs['to_location']?> </td>
				       <td class="text-center"style="text-align:left; <?php echo $cus_dubplicate;?>" > <?php echo $rs['last_name']?></td>
				       <td class="text-center" style="text-align:left;">
				       <div class="dropdown" >
									  <span class="glyphicon glyphicon-triangle-bottom"></span>
									  <div class="dropdown-content">
									    <a  target="_blank" href="<?php echo $this->baseUrl();?>/bookings/index/edit/id/<?php echo $rs["id"]?>"><?php echo $tr->translate("EDIT")?></a>
									    <a  target="_blank" style="color: #333;text-decoration: none;" href="<?php echo $this->baseUrl();?>/bookings/index/bookview/id/<?php echo $rs["id"]?>"><?php echo $tr->translate("PREPARE_CAR")?></a>
									    <a   href="<?php echo $this->baseUrl();?>/bookings/index/delete/id/<?php echo $rs["id"]?>"><?php echo $tr->translate("DELETE")?></a>
									    <a   href="<?php echo $this->baseUrl();?>/bookings/index/view/id/<?php echo $rs["id"]?>"><?php echo $tr->translate("VIEW")?></a>
									  </div>
									</div>
				        <?php echo $rs['phone']?></td> 
				       <td class="text-center"> <?php echo $rs['email']?></td> 
				       <td class="text-center"><?php echo $rs['vehicle_type']?> </td>
				       <td class="text-center" <?php //echo $paid_color;?>> <?php echo ($rs['paid']==0)?"":"$&nbsp;".number_format($rs["paid"],2);?> </td>
				       
				       <td class="text-center"> <?php echo ($rs['total']==0)?"":"$&nbsp;".number_format($rs["total"],2);?> </td>
				       <td class="text-center"> <?php echo ($rs['price']==0)?"":"$&nbsp;".number_format($rs["price"],2);?> </td>
				       
				       <td class="text-center"> <?php echo ($rs['balance_after']==0)?"":"$&nbsp;".number_format($rs["balance_after"],2);?></td> 
				       <td class="text-center">  <?php echo ($rs['grand_total']==0)?"":"$&nbsp;".number_format($rs["grand_total"],2);?></td> 
				       <td class="text-center" <?php echo $agen_color;?>><?php echo $rs['agency_name']?> </td>
				      
				       <td class="text-center"> <?php echo ($rs['commision_fee_after']==0)?"":"$&nbsp;".number_format($rs["commision_fee_after"],2);?></td> 
				       
				       <td class="text-center"><?php echo ($rs['total_service']==0)?"":"$&nbsp;".number_format($rs["total_service"],2);?> </td>
				       <td class="text-center" <?php echo $drive_color;?>> <?php echo $rs['driver']?></td>
				       <td class="text-center"><?php echo ($rs['driver_fee_after']==0)?"":"$&nbsp;".number_format($rs["driver_fee_after"],2);?> </td>
				       <td class="text-center" style="background:#fff"><a style="color: #333;text-decoration: none;" href="<?php echo $this->baseUrl();?>/bookings/index/bookview/id/<?php echo $rs["id"]?>"> <?php echo $rs['book_status']?></a></td>
				       <td align="left"> <?php echo $rs['note']?></td>
				       <td class="text-center" nowrap="nowrap">
				        <a  target="_blank" style="color: #333;text-decoration: none;border: 2px solid #f7eded;border-radius: 3px;background: #f9f8f8;" href="<?php echo $this->baseUrl();?>/bookings/index/edit/id/<?php echo $rs["id"]?>"><span style="color: blue;line-height:0px;">Edit</span></a>&nbsp;|
				        <a   style="color: #333;text-decoration: none;border: 2px solid #f7eded;border-radius: 3px;background: #f9f8f8;" href="<?php echo $this->baseUrl();?>/bookings/index/delete/id/<?php echo $rs["id"]?>"><span style="color: red;line-height:0px;">Delete</span></a>
				        </td>
				        <td class="text-center"> <?php echo $rs['user_name']?></td>
				        <td class="text-center"> <?php echo $rs['status']?></td>
				     </tr>
				     <?php }?>
			     </tbody>
			     </table>
			   </div>
			   <table>
			     <tr>
			        <td style="background:#c6ffda;height:30px;width: 30px;border:1px solid #000;">  </td><td valign="bottom">&nbsp;=&nbsp;Pending</td>
			        <td width="5%"></td>
			        <td style="background:#fff;height:30px;width: 30px;border:1px solid #000;">  </td><td valign="bottom">&nbsp;=&nbsp;Prepaired</td>
			        <td width="5%"></td>
			        <td style="background:#a59e9e;height:30px;width: 30px;border:1px solid #000;">  </td><td valign="bottom">&nbsp;=&nbsp;Cancal</td>
			        <td width="5%"></td>
			        <td style="background:#ff0f0f57;height:30px;width: 30px;border:1px solid #000;">  </td><td valign="bottom">&nbsp;=&nbsp;Late</td>
			        <td width="5%"></td>
			        <td style="background:#ffff66;height:30px;width: 30px;border:1px solid #000;">  </td><td valign="bottom">&nbsp;=&nbsp;Duplicate</td>
			         <td width="5%"></td>
			        <td style="background:#33FF6E;height:30px;width: 30px;border:1px solid #000;">  </td><td valign="bottom">&nbsp;=&nbsp;Payment Already</td>
			     </tr>
			   </table>
			</div>
			</div>
	
		</div>
			
	
<script>
function setColor(el, BG1, BG2) {
	el.style.background = (el.style.background == BG1) ? BG2 : BG1;
	}

</script>