<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<?php $frm =  $this->frm_search;
?>
<title><?php echo $tr->translate("Car Booking");?></title>
<script type="text/javascript">
dojo.ready(function(){
	 $('select[name="datatable-responsive_length"]').val('25');
	 $('select[name="datatable-responsive_length"]').change();
	 //dijit.byId("date_type").attr("value",2);
	 dijit.byId("status").set("value",1);
});
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.TimeTextBox");
 
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
</script>
<script type="text/javascript">
   
 

 </script>
<div class="row">
	<div class="x_panel" >
		 <div class="blog_form_title">
		 	<h4><i class="fa fa-book" aria-hidden="true"></i> <?php echo $tr->translate("Car Booking")?></h4>
		 </div>
			<form id="list" name="list" action="<?php echo $this->url(array('module'=>'bookings','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
			  	<div class="clearfix"></div>
				  <div class="form-group">
					<div class="col-md-2 col-xs-12 mg-10">
					  <?php echo $frm->getElement("search_text");?>
					</div>
					 
					<div class="col-md-2 col-xs-12 mg-10">
					  <?php echo $frm->getElement('from_book_date');?>
					</div>
					 
					<div class="col-md-2 col-xs-12 mg-10">
					  <?php echo $frm->getElement('to_book_date');?>
					</div>
					<div class="col-md-2 col-xs-12 mg-10">
						  <?php echo $frm->getElement("date_type");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-10">
					   <?php echo $frm->getElement("customer");?>
					</div>
				  </div>
				  
				  <div class="clearfix"></div>
				  <div class="form-group">
					<div class="col-md-2 col-xs-12 mg-10">
					   <?php echo $frm->getElement("agency_search");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-10">
					   <?php echo $frm->getElement("driver_search");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-10">
					   <?php echo $frm->getElement("vehicle_type");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-10">
						  <?php echo $frm->getElement("working_status");?>
						</div>
					<div class="col-md-2 col-xs-12 mg-10">
						  <?php echo $frm->getElement("status");?>
						</div>
				    <div class="col-md-1 col-xs-12">
							<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				  </div>
			</form>
    	 <div class="x_panel">
	    	<div class="x_content">
	    		<table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
		    	<thead>
		    		  <tr>  
		    		  	  <th><?php echo $tr->translate("NUM")?></th> 
		    		      <th><?php echo $tr->translate("BOOKING_NO")?></th> 
		    		      <th><?php echo $tr->translate("BOOKING_DATE")?> </th> 
		    	          <th><?php echo $tr->translate("DELIVERY_DATE")?></th> 
		    	          <th><?php echo $tr->translate("DELIVERY_TIME")?></th> 
		    	          <th><?php echo $tr->translate("OTHER_BOOKING_NO")?></th>
		    		      <th><?php echo $tr->translate("FROM_LOCATION")?> </th> 
		    	          <th><?php echo $tr->translate("TO_LOCATION")?></th> 
		                  <th><?php echo $tr->translate("CUSTOMER_NAME")?></th>
		                  <th><?php echo $tr->translate("CUS_PHONE")?></th> 
		    	          <th><?php echo $tr->translate("CUS_EMAIL")?></th> 
		    	          <th><?php echo $tr->translate("VEHICLE_TYPE")?></th> 
		    	          <th><?php echo $tr->translate("TOTAL_PAID")?> </th> 
		    	          <th><?php echo $tr->translate("BALANCE")?> </th> 
		    	          <th><?php echo $tr->translate("TOTAL_PAYMENT")?> </th> 
		    	          <th><?php echo $tr->translate("AGENCY_NAME")?> </th> 
		    	          <th><?php echo $tr->translate("CAR_RENT_FEE")?> </th> 
		    	          <th><?php echo $tr->translate("COMMISSION_FEE")?></th> 
		    	          <th><?php echo $tr->translate("OTHER_FEE")?> </th> 
		    	          <th><?php echo $tr->translate("GRAND_TOTAL")?></th> 
		    	          <th><?php echo $tr->translate("DRIVER")?> </th> 
		    	          <th><?php echo $tr->translate("DRIVER_FEE")?></th> 
		    	          <th><?php echo $tr->translate("BOOKING_STATUS")?> </th> 
		    	          <th><?php echo $tr->translate("USER")?></th> 
		    	          <th><?php echo $tr->translate("STATUS")?></th> 
		             </tr>
		         </thead> 
			     <tbody>
				     <?php $room_no='';$cus_name='';$book_no_color=''; if(!empty($this->rows)) foreach ($this->rows As $key=>$rs){
				          if($rs['status_working']==0){
				          	$status_working='style="background:#c6ffda"';
				          }else if($rs['status_working']==1){
				          	$status_working='style="background:#fff"';
				          }else{
				          	$status_working='style="background:#e4e4e4"';
				          }
				          if($rs['check_book_no']==$room_no && $rs['check_name']==$cus_name){
				          	$book_no_color='style="background: #ffe5e5 !important;"';
				          }else{
				          	$book_no_color='';
				          }
				          $room_no=$rs['check_book_no'];$cus_name=$rs['check_name'];
				     	?>
				     <tr class=" alternate  normal" <?php echo $status_working;?>>
				       <td class="text-center"> <?php echo $key+1?></td>
				       <td class="text-center"> <a style="color: #333;text-decoration: none;" href="<?php echo $this->baseUrl();?>/bookings/index/edit/id/<?php echo $rs["id"]?>"><?php echo $rs['booking_no']?></a></td> 
				       <td class="text-center"><a style="color: #333;text-decoration: none;" href="<?php echo $this->baseUrl();?>/bookings/index/edit/id/<?php echo $rs["id"]?>"> <?php echo date("d-M-Y",strtotime($rs['booking_date']));?></a></td> 
				       <td class="text-center"><a style="color: #333;text-decoration: none;" href="<?php echo $this->baseUrl();?>/bookings/index/edit/id/<?php echo $rs["id"]?>"> <?php echo date("D, d-M-Y",strtotime($rs['delivey_date']));?> </a></td>
				       <td class="text-center"><a style="color: #333;text-decoration: none;" href="<?php echo $this->baseUrl();?>/bookings/index/edit/id/<?php echo $rs["id"]?>"> <?php echo $rs['delivey_time']?></a></td>
				       <td class="text-center" <?php echo $book_no_color;?>> <a style="color: #333;text-decoration: none;" href="<?php echo $this->baseUrl();?>/bookings/index/edit/id/<?php echo $rs["id"]?>"><?php echo $rs['payment_booking_no']?></a></td> 
				       <td  > <?php echo $rs['from_location']?></td> 
				       <td  ><?php echo $rs['to_location']?> </td>
				       <td class="text-center"> <?php echo $rs['last_name']?></td>
				       <td class="text-center"> <?php echo $rs['phone']?></td> 
				       <td class="text-center"> <?php echo $rs['email']?></td> 
				       <td class="text-center"><?php echo $rs['vehicle_type']?> </td>
				       <td class="text-center"> <?php echo ($rs['paid']==0)?"":"$&nbsp;".number_format($rs["paid"],2);?> </td>
				       <td class="text-center"> <?php echo ($rs['balance']==0)?"":"$&nbsp;".number_format($rs["balance"],2);?></td> 
				       <td class="text-center">  <?php echo ($rs['grand_total_after']==0)?"":"$&nbsp;".number_format($rs["grand_total_after"],2);?></td> 
				       <td class="text-center"><?php echo $rs['agency_name']?> </td>
				       <td class="text-center"><?php echo ($rs['total']==0)?"":"$&nbsp;".number_format($rs["total"],2);?>  </td>
				       <td class="text-center"> <?php echo ($rs['commision_fee']==0)?"":"$&nbsp;".number_format($rs["commision_fee"],2);?></td> 
				       <td class="text-center"><?php echo ($rs['other_fee']==0)?"":"$&nbsp;".number_format($rs["other_fee"],2);?> </td>
				       <td class="text-center"> <?php echo ($rs['grand_total']==0)?"":"$&nbsp;".number_format($rs["grand_total"],2);?></td>
				       <td class="text-center"> <?php echo $rs['driver']?></td>
				       <td class="text-center"><?php echo ($rs['driver_fee']==0)?"":"$&nbsp;".number_format($rs["driver_fee"],2);?> </td>
				       <td class="text-center" style="background:#fff"><a style="color: #333;text-decoration: none;" href="<?php echo $this->baseUrl();?>/bookings/index/bookview/id/<?php echo $rs["id"]?>"> <?php echo $rs['book_status']?></a></td>
				        <td class="text-center"> <?php echo $rs['user_name']?></td>
				        <td class="text-center"> <?php echo $rs['status']?></td>
				     </tr>
				     <?php }?>
			     </tbody>
			     </table>
			   </div>
			</div>
			</div>
		</div>
