<?php 
   $tr = Application_Form_FrmLanguages::getCurrentlanguage();
   echo $this->headTitle($tr->translate("BOOKING_VIEW"));
   $frm = $this->frm;
   $hours =array(''=>'',
   		'00:00:00'=>'12:00 AM',
   		'00:15:00'=>'12:15 AM',
   		'00:30:00'=>'12:30 AM',
   		'00:45:00'=>'12:45 AM',
   		'01:00:00'=>'1:00 AM',
   		'01:15:00'=>'1:15 AM',
   		'01:30:00'=>'1:30 AM',
   		'01:45:00'=>'1:45 AM',
   		'02:00:00'=>'2:00 AM',
   		'02:15:00'=>'2:15 AM',
   		'02:30:00'=>'2:30 AM',
   		'02:45:00'=>'2:45 AM',
   		'03:00:00'=>'3:00 AM',
   		'03:15:00'=>'3:15 AM',
   		'03:30:00'=>'3:30 AM',
   		'03:45:00'=>'3:45 AM',
   		'04:00:00'=>'4:00 AM',
   		'04:15:00'=>'4:15 AM',
   		'04:30:00'=>'4:30 AM',
   		'04:45:00'=>'4:45 AM',
   		'05:00:00'=>'5:00 AM',
   		'05:15:00'=>'5:15 AM',
   		'05:30:00'=>'5:30 AM',
   		'05:45:00'=>'5:45 AM',
   		'06:00:00'=>'6:00 AM',
   		'06:15:00'=>'6:15 AM',
   		'06:30:00'=>'6:30 AM',
   		'06:45:00'=>'6:45 AM',
   		'07:00:00'=>'7:00 AM',
   		'07:15:00'=>'7:15 AM',
   		'07:30:00'=>'7:30 AM',
   		'07:45:00'=>'7:45 AM',
   		'08:00:00'=>'8:00 AM',
   		'08:15:00'=>'8:15 AM',
   		'08:30:00'=>'8:30 AM',
   		'08:45:00'=>'8:45 AM',
   		'09:00:00'=>'9:00 AM',
   		'09:15:00'=>'9:15 AM',
   		'09:30:00'=>'9:30 AM',
   		'09:45:00'=>'9:45 AM',
   		'10:00:00'=>'10:00 AM',
   		'10:15:00'=>'10:15 AM',
   		'10:30:00'=>'10:30 AM',
   		'10:45:00'=>'10:45 AM',
   		'11:00:00'=>'11:00 AM',
   		'11:15:00'=>'11:15 AM',
   		'11:30:00'=>'11:30 AM',
   		'11:45:00'=>'11:45 AM',
   		'12:00:00'=>'12:00 PM',
   		'12:15:00'=>'12:15 PM',
   		'12:30:00'=>'12:30 PM',
   		'12:45:00'=>'12:45 PM',
   		'13:00:00'=>'1:00 PM',
   		'13:15:00'=>'1:15 PM',
   		'13:30:00'=>'1:30 PM',
   		'13:45:00'=>'1:45 PM',
   		'14:00:00'=>'2:00 PM',
   		'14:15:00'=>'2:15 PM',
   		'14:30:00'=>'2:30 PM',
   		'14:45:00'=>'2:45 PM',
   		'15:00:00'=>'3:00 PM',
   		'15:15:00'=>'3:15 PM',
   		'15:30:00'=>'3:30 PM',
   		'15:45:00'=>'3:45 PM',
   		'16:00:00'=>'4:00 PM',
   		'16:15:00'=>'4:15 PM',
   		'16:30:00'=>'4:30 PM',
   		'16:45:00'=>'4:45 PM',
   		'17:00:00'=>'5:00 PM',
   		'17:15:00'=>'5:15 PM',
   		'17:30:00'=>'5:30 PM',
   		'17:45:00'=>'5:45 PM',
   		'18:00:00'=>'6:00 PM',
   		'18:15:00'=>'6:15 PM',
   		'18:30:00'=>'6:30 PM',
   		'18:45:00'=>'6:45 PM',
   		'19:00:00'=>'7:00 PM',
   		'19:15:00'=>'7:15 PM',
   		'19:30:00'=>'7:30 PM',
   		'19:45:00'=>'7:45 PM',
   		'20:00:00'=>'8:00 PM',
   		'20:15:00'=>'8:15 PM',
   		'20:30:00'=>'8:30 PM',
   		'20:45:00'=>'8:45 PM',
   		'21:00:00'=>'9:00 PM',
   		'21:15:00'=>'9:15 PM',
   		'21:30:00'=>'9:30 PM',
   		'21:45:00'=>'9:45 PM',
   		'22:00:00'=>'10:00 PM',
   		'22:15:00'=>'10:15 PM',
   		'22:30:00'=>'10:30 PM',
   		'22:45:00'=>'10:45 PM',
   		'23:00:00'=>'11:00 PM',
   		'23:15:00'=>'11:15 PM',
   		'23:30:00'=>'11:30 PM',
   		'23:45:00'=>'11:45 PM',
   );
?>

<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dijit.form.DateTextBox");
dojo.require("dojo.data.ItemFileWriteStore"); 
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
 
dojo.require("dojo.html");
dojo.require("dojo.NodeList-manipulate");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.TimeTextBox");
dojo.require("dojo.parser");
 
</script>
<style>
div.cus_info{
	display: block;
    border: solid 1px #eee;
    clear: both;
    padding: 5px 2px;
    background: #f7f7f7;
}
.image-box.infor {
    padding: 2px;
    border: solid 1px #eee;
}		
span.span_title {
    min-width: 30%;
    display: inline-block;
    font-weight: 600;
}
h4.car_title {
    font-size: 14px;
    color: #156288;
    font-weight: 600;
    margin: 0;
    text-align: center;
    padding: 2px 0;
}

body{
	    color: #3f3f3f;
	    background: #156086;
	    font-weight: 400;
	    line-height: 1.471;
	    font-size: 96%;
	    font-family: "Helvetica Neue",Roboto,Arial,"Droid Sans",sans-serif,'Kh Battambang','Khmer Battambang';
	    font-size: 13px;
}

code {
	    color: #3f3f3f;
	    font-weight: 400;
	    line-height: 1.471;
	    font-size: 96%;
	    font-family: "Helvetica Neue",Roboto,Arial,"Droid Sans",sans-serif,'Kh Battambang','Khmer Battambang';
	    font-size: 13px;
}

</style>
<div class="clearfix"></div>
<div class="x_panel">
	<div class="row">
		<form action="" method="post" id="addbookingrental" dojoType="dijit.form.Form">
			 
      	 <div class="col-md-12 col-xs-12 forms_padding">
	          <div class="x_panel">
	              <div class="x_title">
	                 <h2><i class="fa  fa-info-circle" aria-hidden="true"></i> <?php echo $tr->translate('BOOKING_VIEW')?></h2>
	                 <ul class="nav navbar-right panel_toolbox">
	                    <li>
	                    	<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
	                    </li>
	               	</ul>
               		<div class="clearfix"></div>
          		</div>
	       		<div class="x_content">
	       		
	       		<div class="col-md-8 col-sm-8 col-xs-12">
		                <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("OTHER_BOOKING_NO")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">:
		                    	<?php echo $this->row['payment_booking_no'];?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("BOOKING_DATE")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">:
		                    	<?php echo date("D, d-M-Y",strtotime($this->row['booking_date']));?> 
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("DELIVERY_DATE")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">:
		                    	<?php echo date("D, d-M-Y",strtotime($this->row['delivey_date']));?> 
		                   </div>
		                </div>
		                 <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("DELIVERY_TIME")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">:
		                    	<?php echo $hours[$this->row['time']];?>
		                   </div>
		                </div>
		                <div class="form-group">
		                	<label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("FROM_LOCATION")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">:
		                    	<?php //echo $frm->getElement('from_location');?>
		                    	<?php echo $this->row['f_location'];?>
		                   </div>
		                </div>
		                 <div class="form-group">
		                	<label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("TO_LOCATION")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">:
		                    	<?php echo $this->row['t_location'];?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("DESCRIPTION")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12" >:
		                    	<?php echo $this->row['remark'];?>
		                   </div>
		                </div>
	       			</div>
	       			
	       			<div class="col-md-4 col-sm-4 col-xs-12">
						<div class="title_form_blog " style=" margin: 0;">
	       					<h4 style=" font-size: 14px;"><i class="fa  fa-user" aria-hidden="true"></i> <?php echo $tr->translate('Driver Infomation')?></h4>
	       				</div>
	       				<div id="driver_html" class="cus_info col-md-12 col-sm-12 col-xs-12">
		       				<div class="col-md-4 col-sm-4 col-xs-12">
				               	<div class="image-box infor">
				               		<?php 
				               		$profile = $this->baseUrl().'/images/profile.jpg';
					               		if (!empty($this->driver_info['photo'])){
					               			$profile = $this->baseUrl().'/images/driverphoto/'.$this->driver_info['photo'];
					               		}
				               		?>
									<img id="profile_wiew" src="<?php echo $profile;?>" alt=""  />
								</div>
							</div>
							<div class="col-md-8 col-sm-8 col-xs-12">
								<ul class="list-unstyled">
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('NAME')?></span> : <span class="span_value"><?php if (!empty($this->driver_info['last_name'])){ echo $this->driver_info['first_name']." ".$this->driver_info['last_name'];}?></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('Gender')?></span> : <span class="span_value"><?php if (!empty($this->driver_info['sexs'])){ echo $this->driver_info['sexs'];}?></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('Nationality')?></span> : <span class="span_value"><?php if (!empty($this->driver_info['nationality'])){ echo $this->driver_info['nationality'];}?></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('PHONE')?></span> : <span class="span_value"><?php if (!empty($this->driver_info['tel'])){ echo $this->driver_info['tel'];}?></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('Vehicle Ref.No')?></span> : <span class="span_value"><?php if (!empty($this->driver_info['vehicle_ref_no'])){ echo $this->driver_info['tel'];}?></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('VEHICLE_TYPE')?></span> : <span class="span_value"><?php if (!empty($this->driver_info['tel'])){ echo $this->driver_info['car_type'];}?></span>
                              		</li>
                              	</ul>
							</div>
						</div>
						<div class="clearfix"></div>
						
						<div class="title_form_blog " style=" margin: 0;">
	       					<h4 style=" font-size: 14px;"><i class="fa  fa-user" aria-hidden="true"></i> <?php echo $tr->translate('Customer Information')?></h4>
	       				</div>
	       				<div id="vehiclesss" class="cus_info col-md-12 col-sm-12 col-xs-12">
							<div class="col-md-8 col-sm-8 col-xs-12">
								<ul class="list-unstyled">
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('OTHER_BOOKING_NO')?></span> : <span class="span_value"><?php echo $this->row['payment_booking_no']?></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('CUSTOMER_NAME')?></span> : <span class="span_value"><?php echo $this->row['last_name']?></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('CUS_PHONE')?></span> : <span class="span_value"><?php echo $this->row['phone']?></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('CUS_EMAIL')?></span> : <span class="span_value"><?php echo $this->row['email']?></span>
                              		</li>
                              		 
                              	</ul>
							</div>
							 
							<div class="col-md-8 col-sm-8 col-xs-12">
								<ul class="list-unstyled">
								    <li>
                              			<h4 class="car_title" style="text-align: left;"><?php echo $tr->translate('Payment Information')?> :  </h4>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate("Company Price")?></span> :<span class="span_value" style="font-weight: 900;">&nbsp;<?php echo ($this->row['total']==0)?"":"$&nbsp;".number_format($this->row["total"],2);?></span>
                              		</li> 
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate("CARPRICE")?></span> :<span class="span_value"style="font-weight: 900;">&nbsp;<?php echo ($this->row['price']==0)?"":"$&nbsp;".number_format($this->row["price"],2);?></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate("OTHER_FEE")?></span> :<span class="span_value" style="font-weight: 900;">&nbsp;<?php echo ($this->row['other_fee']==0)?"":"$&nbsp;".number_format($this->row["other_fee"],2);?> </span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate("TOTAL_SERVICE")?></span> :<span class="span_value" style="font-weight: 900;">&nbsp;<?php echo ($this->row['total_service']==0)?"":"$&nbsp;".number_format($this->row["total_service"],2);?></span>
                              		</li>
                              		 <li>
                              			<span class="span_title"><?php echo $tr->translate("GRAND_TOTAL")?></span> :<span class="span_value" style="font-weight: 900;">&nbsp;<?php echo ($this->row['grand_total']==0)?"":"$&nbsp;".number_format($this->row["grand_total"],2);?></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate("NoPay")?></span> :<span class="span_value" style="font-weight: 900;">&nbsp;<?php echo ($this->row['paid']==0)?"":"$&nbsp;".number_format($this->row["paid"],2);?> </span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate("BALANCE")?></span> :<span class="span_value" style="font-weight: 900;">&nbsp;<?php echo ($this->row['balance']==0)?"":"$&nbsp;".number_format($this->row["balance"],2);?></span>
                              		</li>
                              		
                              	</ul>
							</div>
						</div>
						<div class="clearfix"></div>
						
						
	       			</div>
	       		</div>
       		</div>
  		 </div>
     </form>
</div>
</div>
