<?php 
	$product = $this->product;
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$session_lang=new Zend_Session_Namespace('lang');
	$currentlang = $session_lang->lang_id;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	//$base_url = Application_Form_FrmMessage::getUrl("/");
	$menu_info = $this->menu_info; 
	$db = new Application_Model_DbTable_DbGlobalselect();
	$articleperpage = $db->getWebsiteSetting("items_per_page");
	$loadmordata= $articleperpage['value'];
if(!empty($this->param['param'])){
?>
<title><?php echo $menu_info['title_menu'];?></title>
	 
				<?php if ($menu_info['menu_type_id']==1){ //category blog
					if(!empty($menu_info['category_id'])){
						$aticle = $db->getArcticleByCate($menu_info['category_id']);?>
								
					<?php }?>
				<?php }else if ($menu_info['menu_type_id']==2){//category list
									$article = $db->getArcticleByCateForlistAll($menu_info['category_id']);
									$countarticle = $db->countarticle($menu_info['category_id']);
									
									$limits = $db->getWebsiteSetting("items_per_page");
									$paginator = Zend_Paginator::factory($article);
									$paginator->setDefaultItemCountPerPage($limits['value']);
									$allItems = $paginator->getTotalItemCount();
									$countPages= $paginator->count();
									$p = Zend_Controller_Front::getInstance()->getRequest()->getParam('pages');
										
									if(isset($p))
									{
										$paginator->setCurrentPageNumber($p);
									} else $paginator->setCurrentPageNumber(1);
									
									$currentPage = $paginator->getCurrentPageNumber();
										
									$articless  = $paginator;
// 									$this->view->countItems = $allItems;
// 									$this->view->countPages = $countPages;
// 									$this->view->currentPage = $currentPage;
									
									if($currentPage == $countPages)
									{
										$nextPage = $countPages;
										$previousPage = $currentPage-1;
									}
									else if($currentPage == 1)
									{
										$nextPage = $currentPage+1;
										$previousPage = 1;
									}
									else {
										$nextPage = $currentPage+1;
										$previousPage = $currentPage-1;
									}
								?>
								<!-- Breadcrumb Area Start-->
								<div class="breadcrumb-area bg-8">	
									<div class="container">
										<div class="row">
											<div class="col-md-4">
												<div class="breadcrumb-text text-left">
													<h2><?php echo $menu_info['title_menu'];?></h2>
													<div class="breadcrumb-bar">
														<ul class="breadcrumb">
															<li><a href="<?php echo $this->baseUrl();?>"><?php echo $tr->translate("HOME");?></a></li>
															<li><?php echo $menu_info['title_menu'];?></li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<!-- Breadcrumb Area End -->
						        <!-- Blog Section Area Start -->
						        <div class="blog-section-area ptb-20">
						            <div class="container">
						                <div class="row">
						                	 <div class="col-lg-1 col-md-1">
						                    </div>
						                    <div class="col-lg-10 col-md-10">
						                        <div class="single-blog-post-wrapper">
						                        <?php if(!empty($articless)) foreach($articless as $article){ ?>
						                            <div class="single-blog-post">
						                                <div class="blog-image">
						                                    <a href="<?php echo $this->baseUrl()."/page/index?article=".$article['alias_article'].".html"; ?>">
						                                    <?php if(!empty($article['image_feature'])){?>
																<img src="<?php echo $this->baseUrl()."/images/article/".$article['image_feature'];?>"/>
															<?php }else{?>
																<img src="<?php echo $this->baseUrl()."/images/noimage.jpg";?>"/>
															<?php }?>
						                                    </a>
						                                </div>
						                                <div class="blog-post-text">
						                                    <h4><a href="<?php echo $this->baseUrl()."/page/index?article=".$article['alias_article'].".html"; ?>"><?php echo $article['title'];?></a></h4>
						                                     <div class="blog-post-meta">
							                                    <span><i class="fa fa-calendar"></i> <span><?php echo date("d-M-Y",strtotime($article['create_date']));?></span></span>
							                                </div>
						                                    <p><?php
																echo strip_tags($article['short_descript']);
															?> </p>
						                                    <a href="<?php echo $this->baseUrl()."/page/index?article=".$article['alias_article'].".html"; ?>" class="default-btn"><span><?php echo $tr->translate("READ_MORE")?></span></a>
						                                </div>
						                            </div>
						                            <?php }?>
						                        </div>
						                        <?php 
						                        if($countPages>1){ 
												 	$statpage = $currentPage - 5;
												 	$endpage = $currentPage + 5;
												 	if ($currentPage<=5){
												 		$statpage = 1;
												 		$endpage =10;
												 	}
						                        }
						                        if (!empty($countPages)){
												 ?> 
						                        <div class="pagination-wrapper fix">
						                            <div class="pagination-content">
						                            <?php if($countPages>1){ ?>
						                                <a class="ht-page <?php if($currentPage==1){ echo "active";}?>" href="<?php echo $this->baseUrl()."/page/index?param=".$this->param['param']."&pages=".$previousPage;?>"><i class="fa fa-angle-left"></i><?php echo $tr->translate("Prev");?></a>
					                              
						                                <ul class="pagination">
						                                    <?php  $i=0; for( $i=1; $i<=$countPages; $i++){?>
									           			 	<?php if ($statpage<=$i && $endpage>=$i){?>
		                                   					 <li class="<?php if($i==$currentPage){ echo "active";}?>">
		                                   					 	<a href="<?php echo $this->baseUrl()."/page/index?param=".$this->param['param']."&pages=".$i;?>"><?php echo $i;?></a>
		                                   					 </li>
		                                                 <?php }}?>
						                                </ul>
						                                <a class="ht-page <?php if($countPages==$currentPage){ echo "active"; }?>" href="<?php echo $this->baseUrl()."/page/index?param=".$this->param['param']."&pages=".$nextPage;?>"><?php echo $tr->translate("Next");?><i class="fa fa-angle-right"></i></a>
						                           		<?php }?>
						                            </div>
						                        </div>
						                        <?php }?>
						                    </div>
						                    <div class="col-lg-1 col-md-1">
						                    </div>
						                </div>
						            </div>
						        </div>
						        <!-- Blog Section Area End -->
				<?php }else if ($menu_info['menu_type_id']==3){//sigle aticle
						$aticle = $db->getAticleByID($menu_info['article_id']);
						$homecategory = $db->getWebsiteSetting("homecategorycontent");
						$lastestart="";
						$cateinfo='';
						if (!empty($homecategory['value'])){
							$cateinfo = $db->getCategoryByID($homecategory['value']);
						$lastestart = $db->getArcticleByCateLastesArticle($homecategory['value'],$menu_info['article_id']);
						}
						?>
				<div class="sigle_article">
				    <div class="fix-bg">
					    <div class="img" style="background-image:url('<?php echo $this->baseUrl()."/images/singlebg.jpg"?>');"></div>
					    <div class="inside">
						</div>
				 	 </div>
				 	 <div class="container siglearticle" >
						<!-- Breadcrumb Area Start-->
						<div class="breadcrumb-area bg-8">	
							<div class="container ">
								<div class="row">
									<div class="col-md-6">
										<div class="breadcrumb-text text-left">
											<h2><?php echo $menu_info['title_menu'];?></h2>
											<div class="breadcrumb-bar">
												<ul class="breadcrumb">
													<li><a href="<?php echo $this->baseUrl();?>"><?php echo $tr->translate("HOME");?></a></li>
													<li><?php echo $menu_info['title_menu'];?></li>
												</ul>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
						<!-- Breadcrumb Area End -->
				        <!-- Blog Section Area Start -->
				        <div class="blog-section-area ptb-20" >
					    
				            <div class="container">
				                <div class="row">
			                      <?php if (!empty($lastestart)){?>
		                   			 <div class="col-lg-9 col-md-8">
					              <?php }else {?>
					              	  <div class="col-lg-2 col-md-2">
					                    </div>
					                     <div class="col-lg-8 col-md-8">
						           <?php }?>
				                        <div class="single-blog-post blog-details">
				                            
				                            <div class="blog-post-text">
				                                <h4><?php echo $aticle['title'];?></h4>
				                                <div class="blog-post-meta">
					                                <span><i class="fa fa-calendar"></i> <span><?php echo date("d-M-Y",strtotime($aticle['create_date']));?></span></span>
					                            </div>
				                               <div class="article_desc">
				                               <?php echo $aticle['description'];?>
				                               </div>
				                               <?php
												$url="http://".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
												?>
				                                <div class="social-icons">
				                                    <a target="_blank"href="https://www.facebook.com/sharer/sharer.php?u=<?php echo urlencode($url);?>" class="facebook"><i class="fa fa-facebook"></i></a>
				                                    <a href="https://twitter.com/devitemsllc" class="twitter"><i class="fa fa-twitter"></i></a>
				                                    <a href="https://dribbble.com/devitemsllc" class="dribbble"><i class="fa fa-dribbble"></i></a>
				                                    <a href="https://www.pinterest.com/" class="pinterest"><i class="fa fa-pinterest"></i></a>
				                                    <a href="https://www.youtube.com/channel/UC0KLL1Ylo1JrcSUZOeX3tqQ" class="youtube"><i class="fa fa-youtube"></i></a>
				                                </div>
				                            </div>
				                        </div>
				                    </div>
				                    <!-- Load Facebook SDK for JavaScript -->
									  <div id="fb-root"></div>
									  <script>(function(d, s, id) {
									    var js, fjs = d.getElementsByTagName(s)[0];
									    if (d.getElementById(id)) return;
									    js = d.createElement(s); js.id = id;
									    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1";
									    fjs.parentNode.insertBefore(js, fjs);
									  }(document, 'script', 'facebook-jssdk'));</script>
				                     <?php if (!empty($lastestart)){?>
					                    <div class="col-lg-3 col-md-4">
					                        <div class="ht-single-widget right_blog">
					                            <h4 class="widget-title"><?php echo empty($cateinfo['title'])?$tr->translate("LASTEST_ARTICLE"):$cateinfo['title'].$tr->translate("NEW");?></h4>
					                            <div class="ht-widget-item">
					                                <div class="widget-content">
					                                <?php foreach ($lastestart as $rs){?>
					                                    <div class="popular-post">
					                                        <a href="<?php echo $this->baseUrl()."/page/index?article=".$rs['alias_article'].".html"; ?>">
					                                        <?php if(!empty($rs['image_feature'])){?>
																<img src="<?php echo $this->baseUrl()."/images/article/".$rs['image_feature'];?>" alt="<?php echo $rs['title'];?>"/>
															<?php }else{?>
																<img src="<?php echo $this->baseUrl()."/images/noimage.jpg";?>" alt="<?php echo $rs['title'];?>"/>
															<?php }?>
					                                        </a>
					                                        <div class="post-text">
					                                            <h6><a href="<?php echo $this->baseUrl()."/page/index?article=".$rs['alias_article'].".html"; ?>"><?php echo $rs['title'];?></a></h6>
					                                            <span><?php echo $tr->translate("DATE")?> <span><?php echo date("d-M-Y",strtotime($rs['create_date']));?></span></span>
					                                        </div>
					                                    </div>
					                                    <?php }?>
					                                </div>
					                            </div>
					                        </div>
					                    </div>
					                    <?php }else {?>
					                    <div class="col-lg-2 col-md-2">
					                    </div>
					                    <?php }?>
				                </div>
				            </div>
				        </div>
				        <!-- Blog Section Area End -->
			        </div>
			    </div>
				<?php }else if ($menu_info['menu_type_id']==4){//Contacts
				$session_message_session = new Zend_Session_Namespace('sentmail_msg');
				$message = $session_message_session->message;
				$session_message_session->unsetAll();
				$contact = $db->getMenuContactByMenID($menu_info['id']);?>
						<!-- Breadcrumb Area Start-->
								<div class="breadcrumb-area bg-9">	
									<div class="container">
										<div class="row">
											<div class="col-md-4">
												<div class="breadcrumb-text text-left">
													<h2><?php echo $menu_info['title_menu'];?></h2>
													<div class="breadcrumb-bar">
														<ul class="breadcrumb">
															<li><a href="<?php echo $this->baseUrl();?>"><?php echo $tr->translate("HOME");?></a></li>
															<li><?php echo $menu_info['title_menu'];?></li>
														</ul>
													</div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<!-- Breadcrumb Area End -->
						        <!-- Contact Information Area Start -->
						        <div class="contact-information-area pt-20">
						            <div class="container">
						            	<div class="row">
						                    <div class="col-lg-12 col-md-12">
						                        <div class="section-title-two">
						                            <h3><span class="icon icon-Info"></span> <?php echo $tr->translate("CONTACT_INFOMATION");?></h3>
						                        </div>
						                    </div>
						                </div>
						                <div class="row">
						                    <div class="col-md-4 col-sm-4">
						                        <div class="single-c-info">
						                            <span class="icon icon-Phone"></span>
						                            <h5><?php echo $tr->translate("PHONE");?></h5>
						                            <div class="c-divider"></div>
						                            <span><?php echo $contact['tel']?></span>
						                        </div>
						                    </div>
						                    <div class="col-md-4 col-sm-4">
						                        <div class="single-c-info">
						                            <span class="icon icon-Pointer"></span>
						                            <h5><?php echo $tr->translate("ADDRESS");?></h5>
						                            <div class="c-divider"></div>
						                            <span><?php echo $contact['address']?></span>
						                        </div>
						                    </div>
						                    <div class="col-md-4 col-sm-4">
						                        <div class="single-c-info">
						                            <span class="icon icon-Phone"></span>
						                            <h5><?php echo $tr->translate("EMAIL");?></h5>
						                            <div class="c-divider"></div>
						                            <span><?php echo $contact['email']?></span>
						                        </div>
						                    </div>
						                </div>
						            </div>
						        </div>
						        <!-- Contact Information Area End -->
						        <!-- Contact Form Area Start -->
						        <div class="contact-form-area pt-20 pb-20">
						            <div class="container">
						            	<div class="col-md-6 col-sm-6">
							                <div class="row">
							                    <div class="col-lg-12 col-md-12">
							                        <div class="section-title-two">
							                            <h3><span class="icon icon-Info"></span> <?php echo $tr->translate("CONTACT_FORM");?></h3>
							                        </div>
							                    </div>
							                </div>
							                <div class="contact-form-wrapper fix">
							                    <form id="contact-form" onsubmit="return validateFormContact(this);" action="<?php echo $this->baseUrl().'/index/contact-form-send-mail'?>" method="post">
							                        <div class="row">
							                            <div class="col-md-6">
							                                <input type="text" name="name" id="name" placeholder="<?php echo $tr->translate("NAME");?>" title="<?php echo $tr->translate("NAME");?>">
							                            </div>
							                            <div class="col-md-6">
							                                <input type="text" name="email" id="email" placeholder="<?php echo $tr->translate("EMAIL");?>" title="<?php echo $tr->translate("EMAIL");?>">
							                            </div>
							                            <div class="col-md-6">
							                                <input type="text" name="telephone" id="telephone" placeholder="<?php echo $tr->translate("PHONE");?>" title="<?php echo $tr->translate("PHONE");?>">
							                            </div>
							                            <div class="col-md-6">
							                                <input type="text" name="subject" id="subject" placeholder="<?php echo $tr->translate("SUBJECT");?>">
							                            </div>
							                        </div>
							                        <textarea name="comment" id="comment" cols="30" rows="10" placeholder="<?php echo $tr->translate("COMMENT");?>" title="<?php echo $tr->translate("COMMENT");?>"></textarea>
							                        <button type="submit" class="submit-btn default-btn gradient">
							                            <span><?php echo $tr->translate("SUBMIT");?></span>
							                        </button>
							                        <p id="message" class="form-messege"><?php if(!empty($message)){ echo $message; } ?></p>
							                    </form>
							                    <script> 
													function validateFormContact(form){
													var message = document.getElementById('message');
													  re = /^\w+$/;
													  if(form.name.value==""){
														  message.innerHTML = "Please fill your Name !";
													      form.name.focus();
													      return false;
													  }else if(form.email.value == "") {
													      message.innerHTML = "Please fill your email address !";
													      form.email.focus();
													      return false;
													  }else if(form.subject.value == "") {
													      message.innerHTML = "Please fill your subject address !";
													      form.email.focus();
													      return false;
													   }else if(form.comment.value == "") {
														      message.innerHTML = "Please fill your comment !";
														      form.comment.focus();
														      return false;
												        }
													  return true;
												}
												</script>
							                </div>
							              </div>
							              <div class="col-md-6 col-sm-6">
							              	<div class="row">
							                    <div class="col-lg-12 col-md-12">
							                        <div class="section-title-two">
							                            <h3><span class="icon icon-Pointer"></span> <?php echo $tr->translate("LOCATION");?></h3>
							                        </div>
							                    </div>
							                </div>
						                 <!-- Google Map Start -->
									        <div class="google-map-area">
									            <!--  Map Section -->
									            <?php if (!empty($contact['map'])){
														echo $contact['map'];
												 }else{?>
													<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3991901.8873551!2d102.73614393157487!3d12.292761097008988!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x310787bfd4dc3743%3A0xe4b7bfe089f41253!2sCambodia!5e0!3m2!1sen!2skh!4v1494389183880" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
												<?php }?>
									        </div>
								        <!-- Google Map End -->
						        		 </div>
						            </div>
						        </div>
						        <!-- Contact Form Area End -->
						     <?php }else if ($menu_info['menu_type_id']==5){//faq
												 $faq = $db->getAllFaq();
												 ?>  
						     <div class="sigle_article">
							    <div class="fix-bg">
								    <div class="img" style="background-image:url('<?php echo $this->baseUrl()."/images/singlebg.jpg"?>');"></div>
								    <div class="inside">
									</div>
							 	 </div>
							 	  <div class="container siglearticle" >
								     <!-- Breadcrumb Area Start-->
										<div class="breadcrumb-area bg-9">	
											<div class="container">
												<div class="row">
													<div class="col-md-4">
														<div class="breadcrumb-text text-left">
															<h2><?php echo $menu_info['title_menu'];?></h2>
															<div class="breadcrumb-bar">
																<ul class="breadcrumb">
																	<li><a href="<?php echo $this->baseUrl();?>"><?php echo $tr->translate("HOME");?></a></li>
																	<li><?php echo $menu_info['title_menu'];?></li>
																</ul>
															</div>
														</div>
													</div>
												</div>
											</div>
										</div>
										<!-- Breadcrumb Area End -->
										<!-- Blog Section Area Start -->
								        <div class="blog-section-area ptb-20">
								            <div class="">
								                <div class="row">
									                <div class="col-md-2 col-sm-12 col-xs-12">
									                </div>
									                 <!-- cd-faq-items -->
								               		 <div class="cd-faq-items  col-md-8 col-sm-12 col-xs-12">
								               		 <?php if (!empty($faq)) foreach ($faq as $rs){?>
								               		 	<button class="accordion"><?php echo $rs['title'];?></button>
														<div class="panel">
														  <p><?php echo $rs['description'];?></p>
														</div>
														<?php }?>
														
													</div> <!-- cd-faq-items -->
													<div class="col-md-2 col-sm-12 col-xs-12">
								                	</div>
								                </div>
							                </div>
							            </div>
							            <!-- Blog Section Area End -->
							          </div>
					          </div>
					            <script>
								var acc = document.getElementsByClassName("accordion");
								var i;
								
								for (i = 0; i < acc.length; i++) {
								  acc[i].onclick = function() {
								    this.classList.toggle("active");
								    var panel = this.nextElementSibling;
								    panel.classList.toggle("active");
								    if (panel.style.maxHeight){
								      panel.style.maxHeight = null;
								    } else {
								      panel.style.maxHeight = panel.scrollHeight + "px";
								    } 
								  }
								}
								</script>
							<?php }?>
	<?Php }else if(!empty($this->param['article'])){ 
	$aticle = $this->article_de;
	$lastestart = $db->getArcticleByCateLastesArticle($aticle['category_id'],$aticle['id']);
	?>	
	<div class="sigle_article">
	    <div class="fix-bg">
		    <div class="img" style="background-image:url('<?php echo $this->baseUrl()."/images/singlebg.jpg"?>');"></div>
		    <div class="inside">
			</div>
	 	 </div>
	 	 <div class="container siglearticle" >
		<!-- Breadcrumb Area Start-->
			<div class="breadcrumb-area bg-8">	
				<div class="container">
					<div class="row">
						<div class="col-md-6">
							<div class="breadcrumb-text text-left">
								<h2><?php echo $aticle['title'];?></h2>
								<div class="breadcrumb-bar">
									<ul class="breadcrumb">
										<li><a href="<?php echo $this->baseUrl();?>"><?php echo $tr->translate("HOME");?></a></li>
										<li><?php echo $aticle['title'];?></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<!-- Breadcrumb Area End -->
	        <!-- Blog Section Area Start -->
	        <div class="blog-section-area ptb-20">
	            <div class="container">
	                <div class="row">
	                <?php if (!empty($lastestart)){?>
	                    <div class="col-lg-9 col-md-8">
	                <?php }else {?>
	              	  <div class="col-lg-2 col-md-2">
	                    </div>
	                     <div class="col-lg-8 col-md-8">
	                <?php }?>
	                        <div class="single-blog-post blog-details">
	                            
	                            <div class="blog-post-text">
	                                <h4><?php echo $aticle['title'];?></h4>
	                                <div class="blog-post-meta">
		                                <span><i class="fa fa-calendar"></i> <span><?php echo date("d-M-Y",strtotime($aticle['create_date']));?></span></span>
		                            </div>
	                               <div class="article_desc">
	                               <?php echo $aticle['description'];?>
	                               </div>
	                                <div class="social-icons">
	                                    <a href="https://www.facebook.com/devitems/" class="facebook"><i class="fa fa-facebook"></i></a>
	                                    <a href="https://twitter.com/devitemsllc" class="twitter"><i class="fa fa-twitter"></i></a>
	                                    <a href="https://dribbble.com/devitemsllc" class="dribbble"><i class="fa fa-dribbble"></i></a>
	                                    <a href="https://www.pinterest.com/" class="pinterest"><i class="fa fa-pinterest"></i></a>
	                                    <a href="https://www.youtube.com/channel/UC0KLL1Ylo1JrcSUZOeX3tqQ" class="youtube"><i class="fa fa-youtube"></i></a>
	                                </div>
	                            </div>
	                        </div>
	                    </div>
	                    <?php if (!empty($lastestart)){?>
	                    <div class="col-lg-3 col-md-4">
	                        <div class="ht-single-widget right_blog">
	                            <h4 class="widget-title"><?php echo empty($aticle['cate_title'])?$tr->translate("LASTEST_ARTICLE"):$aticle['cate_title'].$tr->translate("NEW");?></h4>
	                            <div class="ht-widget-item">
	                                <div class="widget-content">
	                                <?php foreach ($lastestart as $rs){?>
	                                    <div class="popular-post">
	                                        <a href="<?php echo $this->baseUrl()."/page/index?article=".$rs['alias_article'].".html"; ?>">
	                                        <?php if(!empty($rs['image_feature'])){?>
												<img src="<?php echo $this->baseUrl()."/images/article/".$rs['image_feature'];?>" alt="<?php echo $rs['title'];?>"/>
											<?php }else{?>
												<img src="<?php echo $this->baseUrl()."/images/noimage.jpg";?>" alt="<?php echo $rs['title'];?>"/>
											<?php }?>
	                                        </a>
	                                        <div class="post-text">
	                                            <h6><a href="<?php echo $this->baseUrl()."/page/index?article=".$rs['alias_article'].".html"; ?>"><?php echo $rs['title'];?></a></h6>
	                                            <span><?php echo $tr->translate("DATE")?> <span><?php echo date("d-M-Y",strtotime($rs['create_date']));?></span></span>
	                                        </div>
	                                    </div>
	                                    <?php }?>
	                                </div>
	                            </div>
	                        </div>
	                    </div>
	                    <?php }else {?>
	                    <div class="col-lg-2 col-md-2">
	                    </div>
	                    <?php }?>
	                </div>
	            </div>
	        </div>
	        <!-- Blog Section Area End -->
	       </div>
	      </div>
	<?Php }else if(!empty($this->param['category'])){  ?>
	<title><?php echo $this->cate['title'];?></title>
	
	<?Php }?>