<?php 
	$product = $this->product;
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$session_lang=new Zend_Session_Namespace('lang');
	$currentlang = $session_lang->lang_id;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	//$base_url = Application_Form_FrmMessage::getUrl("/");
	$menu_info = $this->menu_info; 
	$db = new Application_Model_DbTable_DbGlobalselect();
	$articleperpage = $db->getWebsiteSetting("items_per_page");
	$facebook = $db->getWebsiteSetting('facebook');
	$loadmordata= $articleperpage['value'];
if(!empty($this->param['param'])){
?>
<title><?php echo $menu_info['title_menu'];?></title>
	 
				<?php if ($menu_info['menu_type_id']==1){ //category blog
					if(!empty($menu_info['category_id'])){
						$aticle = $db->getArcticleByCate($menu_info['category_id']);?>
								
					<?php }?>
				<?php }else if ($menu_info['menu_type_id']==2){//category list
									$article = $db->getArcticleByCateForlistAll($menu_info['category_id']);
									$countarticle = $db->countarticle($menu_info['category_id']);
									
									$limits = $db->getWebsiteSetting("items_per_page");
									$paginator = Zend_Paginator::factory($article);
									$paginator->setDefaultItemCountPerPage($limits['value']);
									$allItems = $paginator->getTotalItemCount();
									$countPages= $paginator->count();
									$p = Zend_Controller_Front::getInstance()->getRequest()->getParam('pages');
										
									if(isset($p))
									{
										$paginator->setCurrentPageNumber($p);
									} else $paginator->setCurrentPageNumber(1);
									
									$currentPage = $paginator->getCurrentPageNumber();
										
									$articless  = $paginator;
// 									$this->view->countItems = $allItems;
// 									$this->view->countPages = $countPages;
// 									$this->view->currentPage = $currentPage;
									
									if($currentPage == $countPages)
									{
										$nextPage = $countPages;
										$previousPage = $currentPage-1;
									}
									else if($currentPage == 1)
									{
										$nextPage = $currentPage+1;
										$previousPage = 1;
									}
									else {
										$nextPage = $currentPage+1;
										$previousPage = $currentPage-1;
									}
								?>
									<!-- Breadcrumb Area Start-->
									<section class="agriculture_breadcrumb section_50">
									        <div class="breadcromb-overlay"></div>
									        <div class="container">
									            <div class="row">
									                <div class="col-sm-6">
									                    <div class="breadcromb-left">
									                        <h3><?php echo $menu_info['title_menu'];?></h3>
									                    </div>
									                </div>
									                <div class="col-sm-6">
									                    <div class="breadcromb-right">
									                        <ul>
									                            <li><a href="<?php echo $this->baseUrl();?>"><i class="fa fa-home"></i><?php echo $tr->translate("HOME");?></a></li>
									                            <li>/</li>
									                            <li><?php echo $menu_info['title_menu'];?></li>
									                        </ul>
									                    </div>
									                </div>
									            </div>
									        </div>
									    </section>
									<!-- Breadcrumb Area End-->
									<!-- Start article Section -->
										<section class="contentcatelist padding-lg">
											<div class="container">
											 <!-- Start left Column -->
												<div class="col-sm-9">
													<div id="listarticle" class=" postlist list-article" data-role="content">
														<div class="postlist list-article">
															<?php if(!empty($articless)) foreach($articless as $article){ ?>
															<div class="list-article article row">
																<a href="<?php echo $this->baseUrl()."/page/index?article=".$article['alias_article'].".html"; ?>">
																	<div class="col-sm-4 article_moblie">
																		<?php if(!empty($article['image_feature'])){?>
																			<img src="<?php echo $this->baseUrl()."/images/article/".$article['image_feature'];?>"/>
																		<?php }else{?>
																			<img src="<?php echo $this->baseUrl()."/images/noimage.jpg";?>"/>
																		<?php }?>
																	</div>
																	<div class="col-sm-8 article_moblie">
																		<div class="article-blog-title">
																			<span class="web"><?php echo $article['title'];?></span>
																			<div class="small">
																			  <ul>
																				<li><i class="fa fa-clock-o"></i> <span class="pub-date"><?php echo date("d-M-Y",strtotime($article['create_date']));?></span></li>                            
																			  </ul>
																			  <div class="clear"></div>
																			</div>
																		</div>
																		<div class="article-list-detail web">
																			<p>
																				<?php
																					echo strip_tags($article['description_forweb']);
																				?>
																			</p>
																		</div>
																		<div class="article-list-detail mobile">
																			<p>
																				<?php
																					echo strip_tags($article['short_descript']);
																				?>
																			</p>
																		</div>
																	</div>
																</a>
															</div>
														<?php }?>
														<div class="clear"></div>
														</div>
													</div>
												</div>
											 <!-- En dleft Column -->
											 <!-- Start Right Column -->
												<div class="col-sm-3">
													<div class="blog-right">
													  	<?php if(!empty($this->menuright)){?>
													  	<div class="menu-second">
													  		<h3><?php echo $tr->translate("INFORMATION");?></h3>
														  		<ul class="sidebar-menu">
																	<?php  foreach($this->menuright as $menu){ $checksub = $db->checkSubMenuRight($menu['id']);?>
																		<li>
																			<a href="<?php echo $this->baseUrl()."/page/index?param=".$menu['alias_menu'].".html";?>">
																			  <span><?php echo $menu['title']?></span>
																			  <?php if(!empty($checksub)){?>
																			  <i class="fa fa-angle-left pull-right"></i>
																			  <?php }?>
																			</a>
																			<?php echo $db->getSubMenuRight($this->baseUrl(), $menu['id']); ?>
																		</li>
																	<?php }?>
																</ul>
													  	</div>
													  	<?php }?>
													  	<?php if (!empty($facebook['value'])){?>
															<div class="facebookpage">
															  <h3><?php echo $tr->translate("FACEBOOK");?></h3>
															  <div class="fb-page" data-href="<?php echo $facebook['value'];?>" data-tabs="timeline" data-width="280" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="<?php echo $facebook['value'];?>" class="fb-xfbml-parse-ignore"><a href="<?php echo $facebook['value'];?>">Facebook</a></blockquote></div>
															</div>
															<?php }?>
												  	</div>
												</div>
											 <!-- End Right Column -->
											</div>
										</section>
						        
						                        <?php 
						                        if($countPages>1){ 
												 	$statpage = $currentPage - 5;
												 	$endpage = $currentPage + 5;
												 	if ($currentPage<=5){
												 		$statpage = 1;
												 		$endpage =10;
												 	}
						                        }
						                        if (!empty($countPages)){
												 ?> 
												  <div class="text-center">
												   <?php if($countPages>1){ ?>
												      <ul class="pagination blue">
												        <li class="<?php if($currentPage==1){ echo "active";}?>"> <a href="<?php echo $this->baseUrl()."/page/index?param=".$this->param['param']."&pages=".$previousPage;?>" aria-label="Previous"> <span aria-hidden="true"><i class="fa fa-angle-left" aria-hidden="true"></i> <?php echo $tr->translate("Back");?></span> </a> </li>
												       <?php  $i=0; for( $i=1; $i<=$countPages; $i++){?>
									           			 	<?php if ($statpage<=$i && $endpage>=$i){?>
												        <li class="<?php if($i==$currentPage){ echo "active";}?>"><a href="<?php echo $this->baseUrl()."/page/index?param=".$this->param['param']."&pages=".$i;?>"><?php echo $i;?></a></li>
												        <?php }}?>
												        <li class="<?php if($countPages==$currentPage){ echo "active"; }?>"> <a href="<?php echo $this->baseUrl()."/page/index?param=".$this->param['param']."&pages=".$nextPage;?>" aria-label="Next"> <span aria-hidden="true"><?php echo $tr->translate("Next");?> <i class="fa fa-angle-right" aria-hidden="true"></i></span> </a> </li>
												      </ul>
												       <?php }?>
												    </div>
						                        <?php }?>
						        <!-- Blog Section Area End -->
				<?php }else if ($menu_info['menu_type_id']==3){//sigle aticle
						$aticle = $db->getAticleByID($menu_info['article_id']);
						$homecategory = $db->getWebsiteSetting("homecategorycontent");
						$lastestart="";
						$cateinfo='';
						if (!empty($homecategory['value'])){
							$cateinfo = $db->getCategoryByID($homecategory['value']);
						$lastestart = $db->getArcticleByCateLastesArticle($homecategory['value'],$menu_info['article_id']);
						}
						?>
						<!-- Breadcrumb Area Start-->
						<section class="agriculture_breadcrumb section_50">
						        <div class="breadcromb-overlay"></div>
						        <div class="container">
						            <div class="row">
						                <div class="col-sm-6">
						                    <div class="breadcromb-left">
						                        <h3><?php echo $menu_info['title_menu'];?></h3>
						                    </div>
						                </div>
						                <div class="col-sm-6">
						                    <div class="breadcromb-right">
						                        <ul>
						                            <li><a href="<?php echo $this->baseUrl();?>"><i class="fa fa-home"></i><?php echo $tr->translate("HOME");?></a></li>
						                            <li>/</li>
						                            <li><?php echo $menu_info['title_menu'];?></li>
						                        </ul>
						                    </div>
						                </div>
						            </div>
						        </div>
						    </section>
					<!-- Breadcrumb Area End-->
					<!-- Start News & Events -->
					<div class="container blog-wrapper padding-lg">
					  <div class="row"> 
					    <!-- Start Left Column -->
					    <div class="col-sm-9 blog-left">
					      <ul class="blog-listing detail">
					        <li>
					          <h2><?php echo $aticle['title'];?></h2>
					        <!--  <ul class="post-detail">
					            <li><span class="icon-calander-icon ico"></span><span class="bold"><?php //echo date("d M",strtotime($aticle['create_date']));?></span> <?php //echo date("Y",strtotime($aticle['create_date']));?></li>
					          </ul> -->
					           <?php echo $aticle['description'];?>
					        </li>
					      </ul>
					    </div>
					    <!-- End Left Column --> 
					    
					    <!-- Start Right Column -->
					    <div class="col-sm-3">
					    	
					      <div class="blog-right">
					      <?php if(!empty($this->menuright)){?>
						  	<div class="menu-second">
						  		<h3><?php echo $tr->translate("INFORMATION");?></h3>
							  		<ul class="sidebar-menu">
										<?php  foreach($this->menuright as $menu){ $checksub = $db->checkSubMenuRight($menu['id']);?>
											<li>
												<a href="<?php echo $this->baseUrl()."/page/index?param=".$menu['alias_menu'].".html";?>">
												  <span><?php echo $menu['title']?></span>
												  <?php if(!empty($checksub)){?>
												  <i class="fa fa-angle-left pull-right"></i>
												  <?php }?>
												</a>
												<?php echo $db->getSubMenuRight($this->baseUrl(), $menu['id']); ?>
											</li>
										<?php }?>
									</ul>
						  	</div>
						  	<?php }?>
						  	<?php if ($lastestart){?>
					        <div class="recent-post">
					          <h3><?php echo empty($cateinfo['title'])?$tr->translate("LASTEST_ARTICLE"):$cateinfo['title']." ".$tr->translate("NEW");?></h3>
					          <ul>
					           <?php foreach ($lastestart as $rs){?>
					            <li class="clearfix"> 
					            	<a href="<?php echo $this->baseUrl()."/page/index?article=".$rs['alias_article'].".html"; ?>">
						              <div class="img-block">
						              <?php if(!empty($rs['image_feature'])){?>
											<img  class="img-responsive" src="<?php echo $this->baseUrl()."/images/article/".$rs['image_feature'];?>" alt="<?php echo $rs['title'];?>"/>
										<?php }else{?>
											<img class="img-responsive"  src="<?php echo $this->baseUrl()."/images/noimage.jpg";?>" alt="<?php echo $rs['title'];?>"/>
										<?php }?>
						              </div>
						              <div class="detail">
						                <h4><?php echo $rs['title'];?></h4>
						                <p><span class="icon-date-icon ico"></span><span><?php echo date("d M",strtotime($rs['create_date']));?></span> <?php echo date("Y",strtotime($rs['create_date']));?></p>
						              </div>
					             	 </a> 
					              </li>
				              <?php }?>
					          </ul>
					        </div>
					         <?php }?>
					         <?php if (!empty($facebook['value'])){?>
								<div class="facebookpage">
								  <h3><?php echo $tr->translate("FACEBOOK");?></h3>
								  <div class="fb-page" data-href="<?php echo $facebook['value'];?>" data-tabs="timeline" data-width="280" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="<?php echo $facebook['value'];?>" class="fb-xfbml-parse-ignore"><a href="<?php echo $facebook['value'];?>">Facebook</a></blockquote></div>
								</div>
								<?php }?>
					      </div>
					     
					    </div>
					    <!-- End Right Column --> 
					  </div>
					</div>
					
					<!-- End News & Events --> 
				<?php }else if ($menu_info['menu_type_id']==4){//Contacts
				$session_message_session = new Zend_Session_Namespace('sentmail_msg');
				$message = $session_message_session->message;
				$session_message_session->unsetAll();
				$contact = $db->getMenuContactByMenID($menu_info['id']);?>
				<!-- Breadcrumb Area Start-->
						<section class="agriculture_breadcrumb section_50">
						        <div class="breadcromb-overlay"></div>
						        <div class="container">
						            <div class="row">
						                <div class="col-sm-6">
						                    <div class="breadcromb-left">
						                        <h3><?php echo $menu_info['title_menu'];?></h3>
						                    </div>
						                </div>
						                <div class="col-sm-6">
						                    <div class="breadcromb-right">
						                        <ul>
						                            <li><a href="<?php echo $this->baseUrl();?>"><i class="fa fa-home"></i><?php echo $tr->translate("HOME");?></a></li>
						                            <li>/</li>
						                            <li><?php echo $menu_info['title_menu'];?></li>
						                        </ul>
						                    </div>
						                </div>
						            </div>
						        </div>
						    </section>
					<!-- Breadcrumb Area End-->
					<!-- Contact Page Area Start -->
							<section class="agrigculture-contact-page-area section_50">
						        <div class="container">
						            <div class="row">
						                <div class="col-md-10">
						                    <div class="agrigculture-contact-desc">
						                        <h3><?php echo $tr->translate("CONTACT_INFOMATION");?></h3>
						                        <p></p>
						                    </div>
						                </div>
						            </div>
						            <div class="agrigculture-contact-form-bottom">
						                <div class="row">
						                    <div class="col-md-4">
						                        <div class="contact-form-left">
						                            <div class="single-contact-left">
						                                <div class="contact-icon">
						                                    <i class="fa fa-phone text-center"></i>
						                                </div>
						                                <div class="contact-text">
						                                    <h4><?php echo $tr->translate("PHONE");?></h4>
						                                    <p><?php echo $contact['tel'];?></p>
						                                </div>
						                            </div>
						                            <div class="single-contact-left">
						                                <div class="contact-icon">
						                                    <i class="fa fa-envelope text-center"></i>
						                                </div>
						                                <div class="contact-text">
						                                    <h4><?php echo $tr->translate("EMAIL");?></h4>
						                                    <p> <?php echo $contact['email'];?></p>
						                                </div>
						                            </div>
						                            <div class="single-contact-left">
						                                <div class="contact-icon">
						                                    <i class="fa fa-home text-center"></i>
						                                </div>
						                                <div class="contact-text">
						                                    <h4><?php echo $tr->translate("ADDRESS");?></h4>
						                                    <span><?php echo $contact['address'];?></span>
						                                </div>
						                            </div>
						                        </div>
						                    </div>
						                    <div class="col-md-8">
						                        <div class="agrigculture-contact-form-right">
						                            <form onsubmit="return validateFormContact(this);"  action="<?php echo $this->baseUrl().'/index/contact-form-send-mail'?>" method="post">
						                                <div class="row">
						                                    <div class="col-md-6">
						                                        <p>
						                                            <input type="text" name="name" id="name" placeholder="<?php echo $tr->translate("NAME");?>" title="<?php echo $tr->translate("NAME");?>">
						                                        </p>
						                                    </div>
						                                    <div class="col-md-6">
						                                        <p>
						                                            <input type="text" name="email" id="email" placeholder="<?php echo $tr->translate("EMAIL");?>" title="<?php echo $tr->translate("EMAIL");?>">
						                                        </p>
						                                    </div>
						                                </div>
						                                <div class="row">
						                                    <div class="col-md-6">
						                                        <p>
						                                            <input type="text" name="subject" id="subject" placeholder="<?php echo $tr->translate("SUBJECT");?>">
						                                        </p>
						                                    </div>
						                                    <div class="col-md-6">
						                                        <p>
						                                            <input type="text" name="telephone" id="telephone" placeholder="<?php echo $tr->translate("PHONE");?>" title="<?php echo $tr->translate("PHONE");?>">
						                                        </p>
						                                    </div>
						                                </div>
						                                <div class="row">
						                                    <div class="col-md-12">
						                                        <p>
						                                            <textarea name="comment" id="comment" cols="30" rows="10" placeholder="<?php echo $tr->translate("COMMENT");?>" title="<?php echo $tr->translate("COMMENT");?>"></textarea>
						                                        </p>
						                                        <p id="message" class="form-messege"><?php if(!empty($message)){ echo $message; } ?></p>
						                                        <p>
						                                            <input value="<?php echo $tr->translate("SUBMIT");?>" type="submit">
						                                        </p>
						                                    </div>
						                                </div>
						                            </form>
						                            <script> 
														function validateFormContact(form){
														var message = document.getElementById('message');
														  re = /^\w+$/;
														  if(form.name.value==""){
															  message.innerHTML = "Please fill your Name !";
														      form.name.focus();
														      return false;
														  }else if(form.email.value == "") {
														      message.innerHTML = "Please fill your email address !";
														      form.email.focus();
														      return false;
														  }else if(form.subject.value == "") {
														      message.innerHTML = "Please fill your subject address !";
														      form.email.focus();
														      return false;
														   }else if(form.comment.value == "") {
															      message.innerHTML = "Please fill your comment !";
															      form.comment.focus();
															      return false;
													        }
														  return true;
													}
												</script>
						                        </div>
						                    </div>
						                </div>
						            </div>
						        </div>
						    </section>
						    <!-- Contact Page Area End -->
						     <!-- Google Map Start -->
						     <div class="gmap_contact">
								<?php if (!empty($contact['map'])){
										echo $contact['map'];
								 }else{?>
									<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3991901.8873551!2d102.73614393157487!3d12.292761097008988!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x310787bfd4dc3743%3A0xe4b7bfe089f41253!2sCambodia!5e0!3m2!1sen!2skh!4v1494389183880" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
								<?php }?>
							</div>
							 <!-- Google Map End -->
						     <?php }else if ($menu_info['menu_type_id']==5){//faq
								 $faq = $db->getAllFaq();
								 $homecategory = $db->getWebsiteSetting("homecategorycontent");
									$lastestart="";
									$cateinfo='';
									if (!empty($homecategory['value'])){
										$cateinfo = $db->getCategoryByID($homecategory['value']);
									$lastestart = $db->getArcticleByCateLastesArticle($homecategory['value']);
									}
								 ?>  
							<!-- Breadcrumb Area Start-->
							<section class="agriculture_breadcrumb section_50">
							        <div class="breadcromb-overlay"></div>
							        <div class="container">
							            <div class="row">
							                <div class="col-sm-6">
							                    <div class="breadcromb-left">
							                        <h3><?php echo $menu_info['title_menu'];?></h3>
							                    </div>
							                </div>
							                <div class="col-sm-6">
							                    <div class="breadcromb-right">
							                        <ul>
							                            <li><a href="<?php echo $this->baseUrl();?>"><i class="fa fa-home"></i><?php echo $tr->translate("HOME");?></a></li>
							                            <li>/</li>
							                            <li><?php echo $menu_info['title_menu'];?></li>
							                        </ul>
							                    </div>
							                </div>
							            </div>
							        </div>
							    </section>
							<!-- Breadcrumb Area End-->
						     <div class="sigle_article">
							 	  <div class="container siglearticle" >
										<!-- Blog Section Area Start -->
								        <div class="blog-section-area ptb-20">
								            <div class="">
								                <div class="row">
									                 <!-- cd-faq-items -->
								               		 <div class="cd-faq-items  col-md-9 col-sm-12 col-xs-12">
								               		 <?php if (!empty($faq)) foreach ($faq as $rs){?>
								               		 	<button class="accordion"><?php echo $rs['title'];?></button>
														<div class="panel">
														  <p><?php echo $rs['description'];?></p>
														</div>
														<?php }?>
														
													</div> <!-- cd-faq-items -->
													<div class="col-md-3 col-sm-12 col-xs-12">
												      <div class="blog-right">
													      <?php if ($lastestart){?>
													        <div class="recent-post">
													          <h3><?php echo empty($cateinfo['title'])?$tr->translate("LASTEST_ARTICLE"):$cateinfo['title']." ".$tr->translate("NEW");?></h3>
													          <ul>
													           <?php foreach ($lastestart as $rs){?>
													            <li class="clearfix"> 
													            	<a href="<?php echo $this->baseUrl()."/page/index?article=".$rs['alias_article'].".html"; ?>">
														              <div class="img-block">
														              <?php if(!empty($rs['image_feature'])){?>
																			<img  class="img-responsive" src="<?php echo $this->baseUrl()."/images/article/".$rs['image_feature'];?>" alt="<?php echo $rs['title'];?>"/>
																		<?php }else{?>
																			<img class="img-responsive"  src="<?php echo $this->baseUrl()."/images/noimage.jpg";?>" alt="<?php echo $rs['title'];?>"/>
																		<?php }?>
														              </div>
														              <div class="detail">
														                <h4><?php echo $rs['title'];?></h4>
														                <p><span class="icon-date-icon ico"></span><span><?php echo date("d M",strtotime($rs['create_date']));?></span> <?php echo date("Y",strtotime($rs['create_date']));?></p>
														              </div>
													             	 </a> 
													              </li>
												              <?php }?>
													          </ul>
													        </div>
													      <?php }?>
													       <?php if (!empty($facebook['value'])){?>
															<div class="facebookpage">
															  <h3><?php echo $tr->translate("FACEBOOK");?></h3>
															  <div class="fb-page" data-href="<?php echo $facebook['value'];?>" data-tabs="timeline" data-width="280" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="<?php echo $facebook['value'];?>" class="fb-xfbml-parse-ignore"><a href="<?php echo $facebook['value'];?>">Facebook</a></blockquote></div>
															</div>
															<?php }?>
								                		</div>
								                	</div>
								                </div>
							                </div>
							            </div>
							            <!-- Blog Section Area End -->
							          </div>
					         	 </div>
					            <script>
								var acc = document.getElementsByClassName("accordion");
								var i;
								
								for (i = 0; i < acc.length; i++) {
								  acc[i].onclick = function() {
								    this.classList.toggle("active");
								    var panel = this.nextElementSibling;
								    panel.classList.toggle("active");
								    if (panel.style.maxHeight){
								      panel.style.maxHeight = null;
								    } else {
								      panel.style.maxHeight = panel.scrollHeight + "px";
								    } 
								  }
								}
								</script>
							<?php }?>
	<?Php }else if(!empty($this->param['article'])){ 
	$aticle = $this->article_de;
	$lastestart = $db->getArcticleByCateLastesArticle($aticle['category_id'],$aticle['id']);
	?>	
	<!-- Breadcrumb Area Start-->
		<section class="agriculture_breadcrumb section_50">
		        <div class="breadcromb-overlay"></div>
		        <div class="container">
		            <div class="row">
		                <div class="col-sm-6">
		                    <div class="breadcromb-left">
		                        <h3><?php echo $aticle['title'];?></h3>
		                    </div>
		                </div>
		                <div class="col-sm-6">
		                    <div class="breadcromb-right">
		                        <ul>
		                            <li><a href="<?php echo $this->baseUrl();?>"><i class="fa fa-home"></i><?php echo $tr->translate("HOME");?></a></li>
		                            <li>/</li>
		                            <li><?php echo $aticle['title'];?></li>
		                        </ul>
		                    </div>
		                </div>
		            </div>
		        </div>
		    </section>
	<!-- Breadcrumb Area End-->
	
	<!-- Start News & Events -->
		<div class="container blog-wrapper padding-lg">
		  <div class="row"> 
		    <!-- Start Left Column -->
		    <div class="col-sm-9 blog-left">
		      <ul class="blog-listing detail">
		        <li>
		          <h2><?php echo $aticle['title'];?></h2>
		          <ul class="post-detail">
		            <li><span class="icon-calander-icon ico"></span><span class="bold"><?php echo date("d M",strtotime($aticle['create_date']));?></span> <?php echo date("Y",strtotime($aticle['create_date']));?></li>
		          </ul>
		           <?php echo $aticle['description'];?>
		        </li>
		      </ul>
		    </div>
		    <!-- End Left Column --> 
		    
		    <!-- Start Right Column -->
		    <div class="col-sm-3">
		      <div class="blog-right">
		      	<?php if(!empty($this->menuright)){?>
			  	<div class="menu-second">
			  		<h3><?php echo $tr->translate("INFORMATION");?></h3>
				  		<ul class="sidebar-menu">
							<?php  foreach($this->menuright as $menu){ $checksub = $db->checkSubMenuRight($menu['id']);?>
								<li>
									<a href="<?php echo $this->baseUrl()."/page/index?param=".$menu['alias_menu'].".html";?>">
									  <span><?php echo $menu['title']?></span>
									  <?php if(!empty($checksub)){?>
									  <i class="fa fa-angle-left pull-right"></i>
									  <?php }?>
									</a>
									<?php echo $db->getSubMenuRight($this->baseUrl(), $menu['id']); ?>
								</li>
							<?php }?>
						</ul>
			  	</div>
			  	<?php }?>
		      	<?php if ($lastestart){?>
		        <div class="recent-post">
		          <h3><?php echo empty($cateinfo['title'])?$tr->translate("LASTEST_ARTICLE"):$cateinfo['title']." ".$tr->translate("NEW");?></h3>
		          <ul>
		           <?php foreach ($lastestart as $rs){?>
		            <li class="clearfix"> 
		            	<a href="<?php echo $this->baseUrl()."/page/index?article=".$rs['alias_article'].".html"; ?>">
			              <div class="img-block">
			              <?php if(!empty($rs['image_feature'])){?>
								<img  class="img-responsive" src="<?php echo $this->baseUrl()."/images/article/".$rs['image_feature'];?>" alt="<?php echo $rs['title'];?>"/>
							<?php }else{?>
								<img class="img-responsive"  src="<?php echo $this->baseUrl()."/images/noimage.jpg";?>" alt="<?php echo $rs['title'];?>"/>
							<?php }?>
			              </div>
			              <div class="detail">
			                <h4><?php echo $rs['title'];?></h4>
			                <p><span class="icon-date-icon ico"></span><span><?php echo date("d M",strtotime($rs['create_date']));?></span> <?php echo date("Y",strtotime($rs['create_date']));?></p>
			              </div>
		             	 </a> 
		              </li>
	              <?php }?>
		          </ul>
		        </div>
		         <?php }?>
	        	<?php if (!empty($facebook['value'])){?>
				<div class="facebookpage">
				  <h3><?php echo $tr->translate("FACEBOOK");?></h3>
				  <div class="fb-page" data-href="<?php echo $facebook['value'];?>" data-tabs="timeline" data-width="280" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="<?php echo $facebook['value'];?>" class="fb-xfbml-parse-ignore"><a href="<?php echo $facebook['value'];?>">Facebook</a></blockquote></div>
				</div>
				<?php }?>
		      </div>
		     
		    </div>
		    <!-- End Right Column --> 
		  </div>
		</div>
		<!-- End News & Events --> 
	<?Php }else if(!empty($this->param['category'])){  ?>
	<title><?php echo $this->cate['title'];?></title>
	
	<?Php }?>