<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();

$session_lang=new Zend_Session_Namespace('lang');
$currentlang = $session_lang->lang_id;

$vehicle = $this->vehiclesale;
?>

<!--// Main Banner \\-->
		<div class="automobile-banner">

            <!--// Slider \\-->
            <div class="automobile-banner-layer">
                <img src="<?php echo $this->baseUrl();?>/templates/extra-images/banner-1.jpg" alt="">
                <span class="blue-transparent"></span>
                <div class="automobile-banner-caption">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="automobile-banner-text">
                                    <span>Finding just the </span>
                                    <h1>car you need</h1>
                                    <ul>
                                        <li><i class="icon-check"></i>We are working around the clock</li>
                                        <li><i class="icon-check"></i>Discounts for regular customers</li>
                                        <li><i class="icon-check"></i>Delivery of spare parts</li>
                                    </ul>
                                    <a href="about-us.html" class="automobile-banner-btn automobile-bgcolor">About Us</a>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="automobile-banner-tabs">
                                    <!-- Nav tabs -->
                                    <ul class="nav-tabs" role="tablist">
                                      <li role="presentation" class="radius"><a href="#banner1" aria-controls="banner1" role="tab" data-toggle="tab">buy a car</a></li>
                                      <li role="presentation" class="active"><a href="#banner2" aria-controls="banner2" role="tab" data-toggle="tab">sell my car</a></li>
                                    </ul>
                                    <!-- Tab panes -->
                                    <div class="tab-content">
                                        <div role="tabpanel" class="tab-pane" id="banner1">
                                            <div class="automobile-banner-form">
                                                <form>
                                                    <ul>
                                                        <li>
                                                            <label>Make:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <label>Model:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Model</option>
                                                                   <option value="Model">Model</option>
                                                                   <option value="Model">Model</option>
                                                                   <option value="Model">Model</option>
                                                                   <option value="Model">Model</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <label>Body Type:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Body Types</option>
                                                                   <option value="Body">Body</option>
                                                                   <option value="Body">Body</option>
                                                                   <option value="Body">Body</option>
                                                                   <option value="Body">Body</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <label>Region:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Region</option>
                                                                   <option value="Region">Region</option>
                                                                   <option value="Region">Region</option>
                                                                   <option value="Region">Region</option>
                                                                   <option value="Region">Region</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <ul>
                                                                <li><label>Min Year:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                                <li>
                                                                    <label>Max Year:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                            </ul>
                                                        </li>
                                                        <li>
                                                            <ul>
                                                                <li><label>Min Price:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                                <li>
                                                                    <label>Max Price:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                            </ul>
                                                        </li>
                                                        <li class="banner-full-form">
                                                            <label class="banner-submit"><i class="icon-search"></i><input type="submit" value="find a car"></label>
                                                            <div class="banner-check">
                                                                <div class="automobile-check widget-check widget-true">
                                                                   <input id="banner-check1" type="checkbox">
                                                                   <label for="banner-check2">Certified</label>
                                                                </div>
                                                                <div class="automobile-check widget-check widget-true">
                                                                   <input id="banner-check2" type="checkbox">
                                                                   <label for="banner-check2">Carfax Verified</label>
                                                                </div>
                                                                <div class="automobile-check widget-check widget-true">
                                                                   <input id="banner-check3" type="checkbox">
                                                                   <label for="banner-check3">Brand New</label>
                                                                </div>
                                                            </div>
                                                        </li>
                                                    </ul>
                                                </form>
                                            </div>
                                        </div>
                                        <div role="tabpanel" class="tab-pane active" id="banner2">
                                            <div class="automobile-banner-form">
                                                <form>
                                                    <ul>
                                                        <li>
                                                            <label>Make:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <label>Model:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Model</option>
                                                                   <option value="Model">Model</option>
                                                                   <option value="Model">Model</option>
                                                                   <option value="Model">Model</option>
                                                                   <option value="Model">Model</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <label>Body Type:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Body Types</option>
                                                                   <option value="Body">Body</option>
                                                                   <option value="Body">Body</option>
                                                                   <option value="Body">Body</option>
                                                                   <option value="Body">Body</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <label>Region:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Region</option>
                                                                   <option value="Region">Region</option>
                                                                   <option value="Region">Region</option>
                                                                   <option value="Region">Region</option>
                                                                   <option value="Region">Region</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <ul>
                                                                <li><label>Min Year:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                                <li>
                                                                    <label>Max Year:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                            </ul>
                                                        </li>
                                                        <li>
                                                            <ul>
                                                                <li><label>Min Price:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                                <li>
                                                                    <label>Max Price:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                            </ul>
                                                        </li>
                                                        <li class="banner-full-form">
                                                            <label class="banner-submit"><i class="icon-search"></i><input type="submit" value="find a car"></label>
                                                            <div class="banner-check">
                                                                <div class="automobile-check widget-check widget-true">
                                                                   <input id="banner-check4" type="checkbox">
                                                                   <label for="banner-check4">Certified</label>
                                                                </div>
                                                                <div class="automobile-check widget-check widget-true">
                                                                   <input id="banner-check5" type="checkbox">
                                                                   <label for="banner-check5">Carfax Verified</label>
                                                                </div>
                                                                <div class="automobile-check widget-check widget-true">
                                                                   <input id="banner-check6" type="checkbox">
                                                                   <label for="banner-check6">Brand New</label>
                                                                </div>
                                                            </div>
                                                        </li>
                                                    </ul>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="automobile-banner-layer">
                <img src="<?php echo $this->baseUrl();?>/templates/extra-images/banner-2.jpg" alt="">
                <span class="blue-transparent"></span>
                <div class="automobile-banner-caption">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="automobile-banner-text automobile-banner-text2">
                                    <span>Your Wheels are </span>
                                    <h1>in good hands</h1>
                                    <a href="contact-us.html" class="automobile-banner-btn automobile-bgcolor">contact us</a>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="automobile-banner-tabs">
                                    <!-- Nav tabs -->
                                    <ul class="nav-tabs" role="tablist">
                                      <li role="presentation" class="radius"><a href="#banner3" aria-controls="banner3" role="tab" data-toggle="tab">buy a car</a></li>
                                      <li role="presentation" class="active"><a href="#banner4" aria-controls="banner4" role="tab" data-toggle="tab">sell my car</a></li>
                                    </ul>
                                    <!-- Tab panes -->
                                    <div class="tab-content">
                                        <div role="tabpanel" class="tab-pane" id="banner3">
                                            <div class="automobile-banner-form">
                                                <form>
                                                    <ul>
                                                        <li>
                                                            <label>Make:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <label>Model:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Model</option>
                                                                   <option value="Model">Model</option>
                                                                   <option value="Model">Model</option>
                                                                   <option value="Model">Model</option>
                                                                   <option value="Model">Model</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <label>Body Type:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Body Types</option>
                                                                   <option value="Body">Body</option>
                                                                   <option value="Body">Body</option>
                                                                   <option value="Body">Body</option>
                                                                   <option value="Body">Body</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <label>Region:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Region</option>
                                                                   <option value="Region">Region</option>
                                                                   <option value="Region">Region</option>
                                                                   <option value="Region">Region</option>
                                                                   <option value="Region">Region</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <ul>
                                                                <li><label>Min Year:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                                <li>
                                                                    <label>Max Year:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                            </ul>
                                                        </li>
                                                        <li>
                                                            <ul>
                                                                <li><label>Min Price:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                                <li>
                                                                    <label>Max Price:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                            </ul>
                                                        </li>
                                                        <li class="banner-full-form">
                                                            <label class="banner-submit"><i class="icon-search"></i><input type="submit" value="find a car"></label>
                                                            <div class="banner-check">
                                                                <div class="automobile-check widget-check widget-true">
                                                                   <input id="banner-check7" type="checkbox">
                                                                   <label for="banner-check7">Certified</label>
                                                                </div>
                                                                <div class="automobile-check widget-check widget-true">
                                                                   <input id="banner-check8" type="checkbox">
                                                                   <label for="banner-check8">Carfax Verified</label>
                                                                </div>
                                                                <div class="automobile-check widget-check widget-true">
                                                                   <input id="banner-check9" type="checkbox">
                                                                   <label for="banner-check9">Brand New</label>
                                                                </div>
                                                            </div>
                                                        </li>
                                                    </ul>
                                                </form>
                                            </div>
                                        </div>
                                        <div role="tabpanel" class="tab-pane active" id="banner4">
                                            <div class="automobile-banner-form">
                                                <form>
                                                    <ul>
                                                        <li>
                                                            <label>Make:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <label>Model:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Model</option>
                                                                   <option value="Model">Model</option>
                                                                   <option value="Model">Model</option>
                                                                   <option value="Model">Model</option>
                                                                   <option value="Model">Model</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <label>Body Type:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Body Types</option>
                                                                   <option value="Body">Body</option>
                                                                   <option value="Body">Body</option>
                                                                   <option value="Body">Body</option>
                                                                   <option value="Body">Body</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <label>Region:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Region</option>
                                                                   <option value="Region">Region</option>
                                                                   <option value="Region">Region</option>
                                                                   <option value="Region">Region</option>
                                                                   <option value="Region">Region</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <ul>
                                                                <li><label>Min Year:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                                <li>
                                                                    <label>Max Year:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                            </ul>
                                                        </li>
                                                        <li>
                                                            <ul>
                                                                <li><label>Min Price:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                                <li>
                                                                    <label>Max Price:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                            </ul>
                                                        </li>
                                                        <li class="banner-full-form">
                                                            <label class="banner-submit"><i class="icon-search"></i><input type="submit" value="find a car"></label>
                                                            <div class="banner-check">
                                                                <div class="automobile-check widget-check widget-true">
                                                                   <input id="banner-check10" type="checkbox">
                                                                   <label for="banner-check10">Certified</label>
                                                                </div>
                                                                <div class="automobile-check widget-check widget-true">
                                                                   <input id="banner-check11" type="checkbox">
                                                                   <label for="banner-check11">Carfax Verified</label>
                                                                </div>
                                                                <div class="automobile-check widget-check widget-true">
                                                                   <input id="banner-check12" type="checkbox">
                                                                   <label for="banner-check12">Brand New</label>
                                                                </div>
                                                            </div>
                                                        </li>
                                                    </ul>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="automobile-banner-layer">
                <img src="<?php echo $this->baseUrl();?>/templates/extra-images/banner-3.jpg" alt="">
                <span class="blue-transparent"></span>
                <div class="automobile-banner-caption">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="automobile-banner-text automobile-banner-text3">
                                    <span>Introducing the new </span>
                                    <h1>2016 Chevy Accelerator</h1>
                                    <p>Summer, something beautiful always on the horizon.</p>
                                    <a href="listing-detail.html" class="automobile-banner-btn automobile-bgcolor">Inventory</a>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="automobile-banner-tabs">
                                    <!-- Nav tabs -->
                                    <ul class="nav-tabs" role="tablist">
                                      <li role="presentation" class="radius"><a href="#banner5" aria-controls="banner5" role="tab" data-toggle="tab">buy a car</a></li>
                                      <li role="presentation" class="active"><a href="#banner6" aria-controls="banner6" role="tab" data-toggle="tab">sell my car</a></li>
                                    </ul>
                                    <!-- Tab panes -->
                                    <div class="tab-content">
                                        <div role="tabpanel" class="tab-pane" id="banner5">
                                            <div class="automobile-banner-form">
                                                <form>
                                                    <ul>
                                                        <li>
                                                            <label>Make:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <label>Model:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Model</option>
                                                                   <option value="Model">Model</option>
                                                                   <option value="Model">Model</option>
                                                                   <option value="Model">Model</option>
                                                                   <option value="Model">Model</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <label>Body Type:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Body Types</option>
                                                                   <option value="Body">Body</option>
                                                                   <option value="Body">Body</option>
                                                                   <option value="Body">Body</option>
                                                                   <option value="Body">Body</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <label>Region:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Region</option>
                                                                   <option value="Region">Region</option>
                                                                   <option value="Region">Region</option>
                                                                   <option value="Region">Region</option>
                                                                   <option value="Region">Region</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <ul>
                                                                <li><label>Min Year:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                                <li>
                                                                    <label>Max Year:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                            </ul>
                                                        </li>
                                                        <li>
                                                            <ul>
                                                                <li><label>Min Price:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                                <li>
                                                                    <label>Max Price:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                            </ul>
                                                        </li>
                                                        <li class="banner-full-form">
                                                            <label class="banner-submit"><i class="icon-search"></i><input type="submit" value="find a car"></label>
                                                            <div class="banner-check">
                                                                <div class="automobile-check widget-check widget-true">
                                                                   <input id="banner-check13" type="checkbox">
                                                                   <label for="banner-check13">Certified</label>
                                                                </div>
                                                                <div class="automobile-check widget-check widget-true">
                                                                   <input id="banner-check14" type="checkbox">
                                                                   <label for="banner-check14">Carfax Verified</label>
                                                                </div>
                                                                <div class="automobile-check widget-check widget-true">
                                                                   <input id="banner-check15" type="checkbox">
                                                                   <label for="banner-check15">Brand New</label>
                                                                </div>
                                                            </div>
                                                        </li>
                                                    </ul>
                                                </form>
                                            </div>
                                        </div>
                                        <div role="tabpanel" class="tab-pane active" id="banner6">
                                            <div class="automobile-banner-form">
                                                <form>
                                                    <ul>
                                                        <li>
                                                            <label>Make:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                   <option value="Makes">Makes</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <label>Model:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Model</option>
                                                                   <option value="Model">Model</option>
                                                                   <option value="Model">Model</option>
                                                                   <option value="Model">Model</option>
                                                                   <option value="Model">Model</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <label>Body Type:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Body Types</option>
                                                                   <option value="Body">Body</option>
                                                                   <option value="Body">Body</option>
                                                                   <option value="Body">Body</option>
                                                                   <option value="Body">Body</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <label>Region:</label>
                                                            <div class="automobile-banner-select">
                                                                <select>
                                                                   <option value="">All Region</option>
                                                                   <option value="Region">Region</option>
                                                                   <option value="Region">Region</option>
                                                                   <option value="Region">Region</option>
                                                                   <option value="Region">Region</option>
                                                                </select>
                                                            </div>
                                                        </li>
                                                        <li>
                                                            <ul>
                                                                <li><label>Min Year:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                                <li>
                                                                    <label>Max Year:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                            </ul>
                                                        </li>
                                                        <li>
                                                            <ul>
                                                                <li><label>Min Price:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                                <li>
                                                                    <label>Max Price:</label>
                                                                    <input type="text" value="" onblur="if(this.value == '') { this.value =''; }" onfocus="if(this.value =='') { this.value = ''; }">
                                                                </li>
                                                            </ul>
                                                        </li>
                                                        <li class="banner-full-form">
                                                            <label class="banner-submit"><i class="icon-search"></i><input type="submit" value="find a car"></label>
                                                            <div class="banner-check">
                                                                <div class="automobile-check widget-check widget-true">
                                                                   <input id="banner-check16" type="checkbox">
                                                                   <label for="banner-check16">Certified</label>
                                                                </div>
                                                                <div class="automobile-check widget-check widget-true">
                                                                   <input id="banner-check17" type="checkbox">
                                                                   <label for="banner-check17">Carfax Verified</label>
                                                                </div>
                                                                <div class="automobile-check widget-check widget-true">
                                                                   <input id="banner-check18" type="checkbox">
                                                                   <label for="banner-check18">Brand New</label>
                                                                </div>
                                                            </div>
                                                        </li>
                                                    </ul>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--// Slider \\-->
            
        </div>
		<!--// Main Banner \\-->

		<!--// Main Content \\-->
		<div class="automobile-main-content">

			<!--// Main Section \\-->
			<div class="automobile-main-section automobile-car-listfull">
				<div class="container">
					<div class="row">

                        <div class="col-md-6">
                            <div class="automobile-car-list">
                                <h2>Browse Cars By Make</h2>
                                <span>444,337 used cars available nationwide </span>
                                <ul>
                                    <li><i class="icon-arrows-1"></i><a href="listing-detail.html">Abarth <span class="automobile-color">(21)</span></a></li>
                                    <li><i class="icon-arrows-1"></i><a href="listing-detail.html">Bedford <span class="automobile-color">(2)</span></a></li>
                                    <li><i class="icon-arrows-1"></i><a href="listing-detail.html">Dacia <span class="automobile-color">(457)</span></a></li>
                                    <li><i class="icon-arrows-1"></i><a href="listing-detail.html">Aixam <span class="automobile-color">(37)</span></a></li>
                                    <li><i class="icon-arrows-1"></i><a href="listing-detail.html">Bentley <span class="automobile-color">(56)</span></a></li>
                                    <li><i class="icon-arrows-1"></i><a href="listing-detail.html">Daewoo <span class="automobile-color">(48)</span></a></li>
                                    <li><i class="icon-arrows-1"></i><a href="listing-detail.html">Alfa Romeo <span class="automobile-color">(157)</span></a></li>
                                    <li><i class="icon-arrows-1"></i><a href="listing-detail.html">BMW <span class="automobile-color">(2664)</span></a></li>
                                    <li><i class="icon-arrows-1"></i><a href="listing-detail.html">Dodge <span class="automobile-color">(286)</span></a></li>
                                    <li><i class="icon-arrows-1"></i><a href="listing-detail.html">Asia <span class="automobile-color">(3)</span></a></li>
                                    <li><i class="icon-arrows-1"></i><a href="listing-detail.html">Bristol <span class="automobile-color">(5)</span></a></li>
                                    <li><i class="icon-arrows-1"></i><a href="listing-detail.html">Ferrari <span class="automobile-color">(290)</span></a></li>
                                    <li><i class="icon-arrows-1"></i><a href="listing-detail.html">Aston Martin <span class="automobile-color">(177)</span></a></li>
                                    <li><i class="icon-arrows-1"></i><a href="listing-detail.html">Bugatti <span class="automobile-color">(27)</span></a></li>
                                    <li><i class="icon-arrows-1"></i><a href="listing-detail.html">Fiat <span class="automobile-color">(1045)</span></a></li>
                                    <li><i class="icon-arrows-1"></i><a href="listing-detail.html">Audi <span class="automobile-color">(264)</span></a></li>
                                    <li><i class="icon-arrows-1"></i><a href="listing-detail.html">Cadillac <span class="automobile-color">(29)</span></a></li>
                                    <li><i class="icon-arrows-1"></i><a href="listing-detail.html">Ford <span class="automobile-color">(3875)</span></a></li>
                                    <li><i class="icon-arrows-1"></i><a href="listing-detail.html">Austin <span class="automobile-color">(10)</span></a></li>
                                    <li><i class="icon-arrows-1"></i><a href="listing-detail.html">Chevrolet <span class="automobile-color">(45)</span></a></li>
                                    <li><i class="icon-arrows-1"></i><a href="listing-detail.html">Honda <span class="automobile-color">(309)</span></a></li>
                                </ul>
                                <a href="listing-detail.html" class="automobile-banner-btn automobile-bgcolor">see all cars</a>
                            </div>
                        </div>						
						<div class="col-md-6">
                            <img src="<?php echo $this->baseUrl();?>/templates/extra-images/car-list-img.png" alt="" class="automobile-car-list-img">
                        </div>

					</div>
				</div>
			</div>
			<!--// Main Section \\-->

            <!--// Main Section \\-->
            <div class="automobile-main-section automobile-car-dealsfull">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="automobile-fancy-title">
                                <h2>the best <span>Car deals</span></h2>
                                <span>See out latest offers on our cars.</span>
                            </div>
                            <div class="automobile-tour-filterable">
                              <ul class="filters-button-group">
                                  <li><a data-filter="*" class="is-checked" href="javascript:void(0)">Latest Cars</a></li>
                                  <li><a data-filter=".brands" href="javascript:void(0)">most popular brands</a></li>
                                  <li><a data-filter=".cheapest" href="javascript:void(0)">Cheapest cars</a></li>
                                  <li><a data-filter=".used" href="javascript:void(0)">used cars</a></li>
                              </ul>
                          </div>
                            <div class="automobile-listing automobile-car-deals automobile-car-deals-filter">
                                <ul class="row">
                                    <li class="col-md-4 element-item used cheapest">
                                        <figure><a href="listing-detail.html"><img src="<?php echo $this->baseUrl();?>/templates/extra-images/car-deals-img1.jpg" alt=""></a><span>$29.897</span>
                                            <figcaption>
                                                <h5><a href="listing-detail.html">2014 mustang Z4 M 630I</a></h5>
                                                <p>Mileage: 25,804 Miles, 3.0L I6, Manual 6-Speed, 18 city / 28 hwy, Gasoline</p>
                                            </figcaption>
                                        </figure>
                                    </li>
                                    <li class="col-md-4 element-item cheapest">
                                        <figure><a href="listing-detail.html"><img src="<?php echo $this->baseUrl();?>/templates/extra-images/car-deals-img2.jpg" alt=""></a><span>$36.900</span>
                                            <figcaption>
                                                <h5><a href="listing-detail.html">2005 NISSAN MURANO SL</a></h5>
                                                <p>Mileage: 25,804 Miles, 3.0L I6, Manual 6-Speed, 18 city / 28 hwy, Gasoline</p>
                                            </figcaption>
                                        </figure>
                                    </li>
                                    <li class="col-md-4 element-item brands used">
                                        <figure><a href="listing-detail.html"><img src="<?php echo $this->baseUrl();?>/templates/extra-images/car-deals-img3.jpg" alt=""></a><span>$45.950</span>
                                            <figcaption>
                                                <h5><a href="listing-detail.html">2016 ferrari A5 589i</a></h5>
                                                <p>Mileage: 25,804 Miles, 3.0L I6, Manual 6-Speed, 18 city / 28 hwy, Gasoline</p>
                                            </figcaption>
                                        </figure>
                                    </li>
                                    <li class="col-md-4 element-item cheapest brands">
                                        <figure><a href="listing-detail.html"><img src="<?php echo $this->baseUrl();?>/templates/extra-images/car-deals-img4.jpg" alt=""></a><span>$12.05</span>
                                            <figcaption>
                                                <h5><a href="listing-detail.html">2016 Alfa Romeo 4C Coupe</a></h5>
                                                <p>Mileage: 25,804 Miles, 3.0L I6, Manual 6-Speed, 18 city / 28 hwy, Gasoline</p>
                                            </figcaption>
                                        </figure>
                                    </li>
                                    <li class="col-md-4 element-item brands used">
                                        <figure><a href="listing-detail.html"><img src="<?php echo $this->baseUrl();?>/templates/extra-images/car-deals-img5.jpg" alt=""></a><span>$34.056</span>
                                            <figcaption>
                                                <h5><a href="listing-detail.html">2016 Aston Martin DB9</a></h5>
                                                <p>Mileage: 25,804 Miles, 3.0L I6, Manual 6-Speed, 18 city / 28 hwy, Gasoline</p>
                                            </figcaption>
                                        </figure>
                                    </li>
                                    <li class="col-md-4 element-item cheapest brands">
                                        <figure><a href="listing-detail.html"><img src="<?php echo $this->baseUrl();?>/templates/extra-images/car-deals-img1.jpg" alt=""></a><span>$25.000</span>
                                            <figcaption>
                                                <h5><a href="listing-detail.html">2015 Audi RS 5 Coupe</a></h5>
                                                <p>Mileage: 25,804 Miles, 3.0L I6, Manual 6-Speed, 18 city / 28 hwy, Gasoline</p>
                                            </figcaption>
                                        </figure>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--// Main Section \\-->

            <!--// Main Section \\-->
            <div class="automobile-main-section automobile-about-full">
                <div class="container">
                    <div class="row">
                        
                        <div class="col-md-12">
                            <div class="automobile-fancy-title">
                                <h2>Why <span>Choose Us</span></h2>
                                <span>Checkout our great advantages.</span>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="automobile-about-services-text">
                                <h3>Best Car Dealership Ever</h3>
                                <p>Get customer ratings and reviews, cars for sale contact information for local <a href="listing-list.html">new and used</a> auto dealers. Find new, certified or used car dealers by make, model, credit, or city on Accelerator. </p>
                                <p>See all our dealerships for the <a href="listing-list.html">most popular</a> vehicles near you.</p>
                                <a href="listing-detail.html" class="automobile-about-readmore automobile-bgcolor">Read About Us</a>
                            </div>
                        </div>
                        <div class="col-md-7">
                            <div class="automobile-about-services-list">
                                <ul>
                                    <li class="list-one">
                                        <i class="icon-tool5"></i>
                                        <div class="automobile-about-list-text">
                                            <h4>We have huge inventory</h4>
                                            <p>It is a long established fact that a reader will be distracted by the readable content of a page when at its layout.</p>
                                        </div>
                                    </li>
                                    <li class="list-two">
                                        <i class="icon-transport2"></i>
                                        <div class="automobile-about-list-text">
                                            <h4>Drive a car home today</h4>
                                            <p>Content here, content here', making it look like readable English. Many desktop publishing packages and web.</p>
                                        </div>
                                    </li>
                                    <li class="list-three">
                                        <i class="icon-hands"></i>
                                        <div class="automobile-about-list-text">
                                            <h4>Great Buying Experience</h4>
                                            <p>There are many variations of passages of Lorem Ipsum from available, but the majority have suffered alteration.</p>
                                        </div>
                                    </li>
                                </ul>
                            </div>                            
                        </div>
                    </div>
                </div>
            </div>
            <!--// Main Section \\-->

            <!--// Main Section \\-->
            <div class="automobile-main-section automobile-call-to-actionfull1">
                <div class="container">
                    <div class="row">
                        <div class="col-md-7">
                            <div class="automobile-call-to-action1">
                                <h2>want to  <span class="automobile-color">sell</span> a car?</h2>
                                <a href="vehicle.html" class="icon-arrows-1"></a>
                            </div>
                        </div>
                        <div class="col-md-5">
                            <div class="automobile-call-to-action1 automobile-call-to-action2">
                                <h2>want to <span>buy</span> a car?</h2>
                                <a href="vehicle.html" class="icon-arrows-1"></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--// Main Section \\-->

            <!--// Main Section \\-->
            <div class="automobile-main-section automobile-listing-listfull">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="automobile-fancy-title">
                                <h2><?php echo $tr->translate("Car For Sale");?></h2>
                            </div>
                            <div class="automobile-listing automobile-listing-list automobile-listing-list2">
                                <ul class="row">
                                	<?php if (!empty($vehicle)) foreach ($vehicle as $veh){
                                			$imgage = $this->baseUrl()."/images/vehicle/no-img.jpg";
                                			if (!empty($veh['img_front'])){
                                				$imgage = $this->baseUrl()."/images/vehicle/".$veh['img_front'];
                                			}
                                			
                                			$make_img = $this->baseUrl()."/images/vehicle/make/noavailable.png";
                                			if (!empty($veh['make_images'])){
                                				$make_img = $this->baseUrl()."/images/vehicle/make/".$veh['make_images'];
                                			}
                                		?>
                                    <li class="col-md-12">
                                        <figure><a href="<?php echo $this->baseUrl()."/index/vehicle?detail=".base64_encode($veh['id']).".html";?>"><img src="<?php echo $imgage;?>" alt=""></a></figure>
                                        <div class="automobile-listing-list-text">
                                            <h4><a href="<?php echo $this->baseUrl()."/index/vehicle?detail=".base64_encode($veh['id']).".html";?>"><?php echo $veh['year']." ".$veh['make']." ".$veh['model']." ".$veh['sub_model'];?></a></h4>
                                            <ul>
                                                <li><?php echo "$ ".number_format($veh['sale_price'],2);?></li>
                                                <li>MSRP $33.000</li>
                                            </ul>
                                            <h6>Mileage: <span>25,804 Miles</span></h6>
                                            <ul class="automobile-listing-option">
                                                <li class="highlights">
                                                    <figure><img src="<?php echo $make_img;?>" alt="<?php echo $veh['make'];?>"></figure>
                                                    <div class="automobile-listing-option-text">
                                                        <div class="new-car-info">
                                                            <h6>Specs:</h6>
                                                            <span><?php echo $veh['reffer'];?></span>
                                                            <span><?php echo $veh['transmission'];?></span>
                                                            <span><?php echo $veh['engine_title'];?></span>
                                                            <span><?php echo $tr->translate("Color");?> - <?php echo $veh['color'];?></span>
                                                        </div>
                                                        <div class="new-car-info">
                                                            <h6>highlights:</h6>
                                                            <span><?php echo $veh['car_type'];?></span>
                                                            <span><?php echo $veh['type_title'];?></span>
                                                            <span><?php echo $veh['steering'];?></span>
                                                            <span><?php echo $tr->translate("NO. OF SEATS");?> - <?php echo $veh['seat_amount'];?></span>
                                                        </div>
                                                    </div>
                                                </li>
                                                <li>
                                                    <ul class="automobile-listing-like">
                                                        <li><a href="404.html">Compare</a></li>
                                                        <li><a href="404.html"><i class="icon-favorite3"></i>Add to Favorites</a></li>
                                                        <li><a href="404.html"><i class="icon-calendar3"></i> Listed 5 days</a></li>
                                                        <li><a href="404.html"><i class="icon-eye"></i> 14 Views</a></li>
                                                        <li><a href="404.html"><i class="icon-social10"></i> 0 Inquiries</a></li>
                                                    </ul>
                                                </li>
                                            </ul>
                                        </div>
                                    </li>
                                    <?php }?>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--// Main Section \\-->

            <!--// Main Section \\-->
            <div class="automobile-main-section automobile-blog-classicfull">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="automobile-fancy-title">
                                <h2>latest <span>blog news</span></h2>
                                <span>Check our latest car-related news.</span>
                            </div>
                            <div class="automobile-blog-classic-wrap">
                                <div class="automobile-blog automobile-blog-medium">
                                    <ul>
                                        <li>
                                            <div class="automobile-single-post-tag">
                                                <div class="automobile-social-tag">
                                                    <i class="automobile-color fa fa-folder-open"></i>
                                                    <a href="404.html">Cars,</a>
                                                    <a href="404.html">Motors,</a>
                                                    <a href="404.html">Functions</a>
                                                </div>
                                                <ul class="automobile-blog-post-comment">
                                                    <li>
                                                        <i class="automobile-color fa fa-comments-o"></i>
                                                        <a href="404.html">5 Comments</a>
                                                    </li>
                                                </ul>
                                            </div>
                                            <figure><a href="blog-detail.html"><img src="<?php echo $this->baseUrl();?>/templates/extra-images/blog-medium-img1.jpg" alt=""><span>Read Article</span></a></figure>
                                            <div class="automobile-blog-classic-text">
                                                <time datetime="2008-02-14 20:00">10 <span>may</span></time>
                                                <div class="automobile-blog-heading">
                                                    <h2><a href="blog-detail.html">get it functional right now</a></h2>
                                                    <p>Hyperloop Transportation Technologies plans to a form of passive repulsion technology to make its pods to go cheaper and easier to maintain.</p>
                                                </div>
                                            </div>
                                        </li>
                                        <li>
                                            <div class="automobile-single-post-tag">
                                                <div class="automobile-social-tag">
                                                    <i class="automobile-color fa fa-folder-open"></i>
                                                    <a href="404.html">Drive,</a>
                                                    <a href="404.html"> Test,</a>
                                                    <a href="404.html"> Learning</a>
                                                </div>
                                                <ul class="automobile-blog-post-comment">
                                                    <li>
                                                        <i class="automobile-color fa fa-comments-o"></i>
                                                        <a href="404.html">12 Comments</a>
                                                    </li>
                                                </ul>
                                            </div>
                                            <figure><a href="blog-detail.html"><img src="<?php echo $this->baseUrl();?>/templates/extra-images/blog-medium-img2.jpg" alt=""><span>Read Article</span></a></figure>
                                            <div class="automobile-blog-classic-text">
                                                <time datetime="2008-02-14 20:00">09 <span>may</span></time>
                                                <div class="automobile-blog-heading">
                                                    <h2><a href="blog-detail.html">we learn you how to drive</a></h2>
                                                    <p>A study launched by VW and Shell looks to biofuels as a better way to achieve climate goals. Others see it as an attempt to block fuel-economy targets.</p>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--// Main Section \\-->

            <!--// Main Section \\-->
            <div class="automobile-main-section">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="automobile-about-newsletter-wrap">
                                <div class="automobile-about-newsletter-text">
                                    <i class="icon-interface7"></i>
                                    <h2>Sign up to our newsletter</h2>
                                    <p>And receive our latest deals &amp; offers on both new and used cars.</p>
                                </div>
                                <form class="automobile-about-newsletter-form">
                                    <input value="Your e-mail address" onblur="if(this.value == '') { this.value ='Your e-mail address'; }" onfocus="if(this.value =='Your e-mail address') { this.value = ''; }" type="text">
                                    <label><input value="" type="submit"><i class="icon-sent-mail"></i></label>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--// Main Section \\-->

		</div>
		<!--// Main Content \\-->
