<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('Add New Driver'));
?>	
<?php  $frm = $this->frm_client;?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<style>
	.form-groupsa {
	    margin-bottom: 5px;
	}
	.account-image {
	    border: solid 1px #eee;
	}
	.image-box {
	    display: inherit;
	    position: relative;
	    text-align: center;
	}
	.image-box img {
	    width: 150px;
	    border-radius: 60%;
	    height: 150px;
	    margin-top: 10px;
	    border: solid 1px #eee;
	}
	.button_browse span {
	    line-height: 33px;
	    font-weight: 600;
	    cursor: pointer;
	}
	
.blog_car {
    padding: 10px;
    background: #f7f7f7;
    border: solid 1px #eee;
}
.blog_car .image_car img.preview_carlist {
    border-radius: 10px;
    border: solid 4px #ffffff;
    width: 100%;
    box-shadow: 1px 1px 3px #f1f1f1;
}
ul.list-unstyled li span.span_title {
    font-weight: bold;
}
h4.car_title {
    font-weight: 600;
    color: #156288;
}
ul.list-unstyled li span.span_value {
    color: #114f73;
}
</style>
<form id='add_client' action="<?php echo $this->url(array('module'=>'driverguide','controller'=>'index','action'=>'add')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
	<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if(dijit.byId('province').get('value')==0){
					alert('Province required');
					dijit.byId('province').focus();
					return false;
			    }
				loading();
				return true;
			} else {
				return false;
			}
	</script>
	<div class="clearfix"></div>
	<div class="row">
      	 <div class="col-md-12 col-xs-12 forms_padding">
	          <div class="x_panel">
	              <div class="x_title">
	                 <h2><i class="fa  fa-plus-circle" aria-hidden="true"></i> <?php echo $tr->translate('Add New Driver')?></h2>
	                 <ul class="nav navbar-right panel_toolbox">
	                    <li>
	                    	<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
	                    </li>
	               	</ul>
	               <div class="clearfix"></div>
	          	</div>
	       		<div class="x_content">
	       			<div class="" role="tabpanel" data-example-id="togglable-tabs">
                      <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                        <li role="presentation" class="active"><a href="#tab_content1" id="home-tab" role="tab" data-toggle="tab" aria-expanded="true"><?php echo $tr->translate('Driver Infomation')?></a></li>
                      </ul>
                      <div id="myTabContent" class="tab-content">
                      		<div role="tabpanel" class="tab-pane fade active in" id="tab_content1" aria-labelledby="home-tab">
	                      		<div class="form-groupsa">
				               		<div class="col-md-3 col-sm-3 col-xs-12">
					               		<div class="account-image">
											<div class="image-box">
												<img id="profile_wiew" src="<?php echo $this->baseUrl().'/images/profile.jpg';?>" alt=""  />
											</div>
											<div class="button_browse">
											<div id='preview'></div>	
													<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
													<input class="btn_borwse_image fullside" type="file" id="photo" name="photo"  onchange="loadFile(event)"/>
											</div>
										</div>
									</div>
									<div class="col-md-9 col-sm-9 col-xs-12">
										<div class="form-group">
						                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Driver's ID")?></label>
						                   <div class="col-md-4 col-sm-4 col-xs-12">
						                   		<?php echo $frm->getElement('client_no');?>
						                   </div>
						                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Gender")?>
							                </label>
							                <div class="col-md-4 col-sm-4 col-xs-12">
							                  		<?php echo $frm->getElement('sex');?>
							                 </div>
						                </div>
						                <div class="form-group">
						                	<label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("DRIVER_NAME")?></label>
							                   <div class="col-md-4 col-sm-4 col-xs-12">
							                   		<?php  echo $frm->getElement('name_en');?>
							                   </div> 
						                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Nationality")?>
							                 </label>
							                 <div class="col-md-4 col-sm-4 col-xs-12">
							                   		<?php echo $frm->getElement('nationality');?>
							                 </div>
						                </div>
						                 <div class="form-group">
						                 	
							                <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Document Type")?>
						                   </label>
						                   <div class="col-md-4 col-sm-4 col-xs-12">
						                   		<input id="client_d_type" required="true"/>
						                   </div>
						                 </div>
						                 <div class="form-group">
						                  	<label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("DOB")?></label>
							                 <div class="col-md-4 col-sm-4 col-xs-12">
							                 		<?php  echo $frm->getElement('dob_client');?>
							                 </div>
							                  <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Document Number")?>
						                   </label>
						                   <div class="col-md-4 col-sm-4 col-xs-12">
						                   		<?php  echo $frm->getElement('national_id');?>
						                   </div>
						                 </div>
						                  <div class="form-group">
						                 	 <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("POB")?></label>
							                 <div class="col-md-4 col-sm-4 col-xs-12">
							                 		<?php  echo $frm->getElement('pob');?>
							                 </div>
							                 <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Note")?>
							                   </label>
							                   <div class="col-md-4 col-sm-4 col-xs-12">
							                   		<?php  echo $frm->getElement('desc');?>
							                   </div>
						                  </div>
						                  <div class="form-group">
						                 	 <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Experience")?></label>
							                   <div class="col-md-10 col-sm-10 col-xs-12">
							                   	<?php  echo $frm->getElement('experience');?>
							                   </div>
						                   </div>
									</div>
									<div class="clearfix"></div>
								</div>
								<div class="col-md-4 col-sm-4 col-xs-12">
									 <div class="title_form_blog">
					               		<h4><i class="fa  fa-user" aria-hidden="true"></i> <?php echo $tr->translate('ID Card Info')?></h4>
					               </div>
					               <div class="form-group">
					                   <label class="control-label col-md-4 col-sm-4 col-xs-12" for="first-name"><?php echo $tr->translate("ID Card")?>
					                   </label>
					                   <div class="col-md-8 col-sm-8 col-xs-12">
					                   		<?php echo $frm->getElement('id_card');?>
					                   </div>
					               </div>
				            	   <div class="form-group">
					                   <label class="control-label col-md-4 col-sm-4 col-xs-12" for="first-name"><?php echo $tr->translate("Issued Date")?>
					                   </label>
					                   <div class="col-md-8 col-sm-8 col-xs-12">
					                   		<?php  echo $frm->getElement('issued_date');?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-4 col-sm-4 col-xs-12" for="first-name"><?php echo $tr->translate("Expired Date")?>
					                   </label>
					                   <div class="col-md-8 col-sm-8 col-xs-12">
					                   		<?php  echo $frm->getElement('expired_date');?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-4 col-sm-4 col-xs-12" for="first-name"><?php echo $tr->translate("Registered Date")?>
					                   </label>
					                   <div class="col-md-8 col-sm-8 col-xs-12">
					                   		<?php echo $frm->getElement('registered_date');?>
					                   </div>
				                   </div>
					                <div class="form-group">   
					                   <label class="control-label col-md-4 col-sm-4 col-xs-12" for="first-name"><?php echo $tr->translate("Document File")?>
					                   </label>
					                   <div class="col-md-8 col-sm-8 col-xs-12">
					                   		<?php  echo $frm->getElement('att_file');?>
					                   </div>
					                </div>
								</div>
								<div class="col-md-8 col-sm-8 col-xs-12">
									<div class="title_form_blog">
					               		<h4><i class="fa  fa-phone" aria-hidden="true"></i> <?php echo $tr->translate('Contact Info')?></h4>
					               </div>
					               <div class="form-group">
					                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Phone")?>
					                   </label>
					                   <div class="col-md-4 col-sm-4 col-xs-12">
					                   		<?php echo $frm->getElement('phone');?>
					                   </div>
					                  <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Street No")?>
					                   </label>
					                   <div class="col-md-4 col-sm-4 col-xs-12">
					                   		<?php  echo $frm->getElement('street');?>
					                   </div>
					                </div>
					                <div class="form-group">
					                	 <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Email")?>
					                   </label>
					                   <div class="col-md-4 col-sm-4 col-xs-12">
					                   		<?php  echo $frm->getElement('email');?>
					                   </div>
					                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Commune")?>
					                   </label>
					                   <div class="col-md-4 col-sm-4 col-xs-12">
					                   		<?php  echo $frm->getElement('commune');?>
					                   </div>
					                </div>
					               <div class="form-group">
					                	<label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Group No")?>
					                   </label>
					                   <div class="col-md-4 col-sm-4 col-xs-12">
					                   		<?php  echo $frm->getElement('group');?>
					                   </div>
					                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("District")?>
					                   </label>
					                   <div class="col-md-4 col-sm-4 col-xs-12">
					                   		<?php echo $frm->getElement('district');?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("House No")?>
					                   </label>
					                   <div class="col-md-4 col-sm-4 col-xs-12">
					                   		<?php echo $frm->getElement('home');?>
					                   </div>
					                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Province")?>
					                   </label>
					                   <div class="col-md-4 col-sm-4 col-xs-12">
					                   		<?php  echo $frm->getElement('province');?>
					                   </div>
					                </div>
					                <div class="form-group">
					                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS")?>
					                   </label>
					                   <div class="col-md-4 col-sm-4 col-xs-12">
					                   		<?php  echo $frm->getElement('status');?>
					                   </div>
					                </div>
								</div>
				               <div class="col-md-12 col-sm-12 col-xs-12">
									<div class="title_form_blog" style=" margin-bottom: 0;">
					               		<h4><i class="fa  fa-car" aria-hidden="true"></i> <?php echo $tr->translate("Vehicle's Information")?></h4>
					               </div>
					                <div class="col-md-12 col-sm-12 col-xs-12" style=" padding-top: 10px;  background: #f7f7f7;">
						              	 <div class="form-group">
							                 <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("VEHICLE")?>
							                   </label>
							                   <div class="col-md-4 col-sm-4 col-xs-12">
							                   		<?php  echo $frm->getElement('vehicle');?>
							                   </div>
						                  </div>
					                </div>
					                <div id="blog_car" class=" blog_car col-md-12 col-sm-12 col-xs-12">
				                            <div class="col-xs-3">
				                            	<div class=" col-xs-12">
				                            		<div class="image_car">
                            							<img src="<?php echo $this->baseUrl()?>/images/no_car.png" class="preview_carlist" alt="">
													</div>
												</div>
												<div class="clearfix"></div>
				                            </div>
				                            <div class=" col-xs-9  text-left">
				                            	<h4 class="car_title">
						                         </h4>
				                            	<ul class="list-unstyled">
					                              		<li>
					                              			<div class="col-md-2 col-sm-2 col-xs-12">
					                              				<span class="span_title"><?php echo $tr->translate('Vehicle Ref.No.')?></span>
					                              			</div> 
					                              			<div class="col-md-4 col-sm-4 col-xs-12">: 
					                              			<span class="span_value"></span>
					                              			</div>
					                              			<div class="col-md-2 col-sm-2 col-xs-12">
					                              				<span class="span_title"><?php echo $tr->translate('YEAR')?></span>
					                              			</div> 
					                              			<div class="col-md-4 col-sm-4 col-xs-12">: 
					                              				<span class="span_value"></span>
					                              			</div>
					                              			<div class="clearfix"></div>
					                              		</li>
														<li>
															<div class="col-md-2 col-sm-2 col-xs-12">
																<span class="span_title"><?php echo $tr->translate('Color')?></span>
															</div> 
															<div class="col-md-4 col-sm-4 col-xs-12">: 
																<span class="span_value"></span>
															</div>
															<div class="col-md-2 col-sm-2 col-xs-12">
																<span class="span_title"><?php echo $tr->translate("No. of Seats")?></span>
															</div> 
															<div class="col-md-4 col-sm-4 col-xs-12">: 
																<span class="span_value"></span>
															</div>
															<div class="clearfix"></div>
														</li>
														<li>
															<div class="col-md-2 col-sm-2 col-xs-12">
																<span class="span_title"><?php echo $tr->translate("Transmission Type")?></span>
															</div> 
															<div class="col-md-4 col-sm-4 col-xs-12">: 
																<span class="span_value"></span>
															</div>
															<div class="col-md-2 col-sm-2 col-xs-12"><span class="span_title"><?php echo $tr->translate("Type")?></span></div> 
															<div class="col-md-4 col-sm-4 col-xs-12">: <span class="span_value"></span></div>
															<div class="clearfix"></div>
														</li>
					                              </ul>
				                            </div>
			                          </div>
					            </div>
                      		</div>
                      </div>
                    </div>
                    <div class="clearfix"></div>
				    <div class="col-md-12 col-xs-12 forms_padding text-center">
				    	<input type="reset" style="color:#000;" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" 
							iconClass="dijitIconClear" /> 
						<input type="submit" value="SAVE_CLOSE" label="<?php echo $tr->translate('SAVECLOSE');?>" style="color:#000;" id="save_close" dojoType="dijit.form.Button" name="save_close"
							iconClass="dijitEditorIcon dijitEditorIconSave" /> 
						<input type="submit" value="SAVE_NEW" label="<?php echo $tr->translate('SAVENEW');?>" id="save_new" style="color:#000;" dojoType="dijit.form.Button" name="save_new"
							iconClass="dijitEditorIcon dijitEditorIconSave"/>
				    </div>
	       		</div>
	       	</div>
	     </div>
	 </div>
</form>
<?php 
echo $this->frm_popup_clienttype;
?>
<script>
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dijit.form.Textarea"); 
require(["dijit/form/DateTextBox","dijit/form/NumberTextBox",
          "dijit/Dialog","dijit/layout/TabContainer"]);
</script>
<script type="text/javascript">
var loadFile = function(event) {
    var output = document.getElementById('profile_wiew');
    output.src = URL.createObjectURL(event.target.files[0]);
  };
var d_datastore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->clienttype));?> );

dojo.ready(function(){
	
	try{
	new dijit.form.FilteringSelect({
		store: d_datastore,
		autoComplete: true,
		required: false,		           
		name: "client_d_type",
		id: "client_d_type",
		searchAttr: "name",
		class: 'fullside',
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះភូមិ!",	
			onChange: function() {
				client_d_type = dijit.byId('client_d_type').get('value');
				if(client_d_type==-1){
					doc_type=1;
					showPopupclientdtype();
				}
			}
		}, "client_d_type");

	
	}catch(e){
	}
});
var document_type_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insert-document-type'));?>';
function addNewDocumentType(){
	dojo.xhrPost({
		url:document_type_url,	
		//form:dojo.byId('form_clienttype'),
		content:{ 
		    'title_en':dijit.byId('document_kh').get('value'),
		    'title_kh':dijit.byId('document_en').get('value'),
		    'type':6,
		},
		handleAs:"json",
		load: function(data) {	
			clienttypeen = dijit.byId('document_kh').get('value');
			clienttypekh = dijit.byId('document_en').get('value');
			/*if(doc_type==1){
				document_type = dijit.byId('client_d_type');
				
			}else if(doc_type==2){
				document_type = dijit.byId('join_d_type');
			}else{
				document_type = dijit.byId('guarantor_d_type');
			}*/

			 var myNewItem1 = {					
						id: data,
						name: clienttypekh+'-'+clienttypeen
				};			
				addDataToSelectbox(dijit.byId('client_d_type'), d_datastore, myNewItem1, data);

				/*var Itemmake = {					
						id: data,
					    name: dijit.byId('txt_make').get('value')
				};			
				addDataToSelectbox(dijit.byId('makename'), make_store, Itemmake, data);*/
				
			dijit.byId('frm_clienttype').reset();
			dijit.byId('frm_clienttype').hide();
	
		},
		error: function(err) {
			alert(err);
		}
	});	
}
function showPopupclientdtype(){
	dijit.byId('frm_clienttype').show();
}
var url_getVehicle = '<?php echo $this->url(array('module'=>'driverguide','controller'=>'index','action'=>'getvehicle')); ?>';
function getVehicleInfo(){
	vehicle = dijit.byId('vehicle').get('value');
	loading();
	dojo.xhrPost({
		url: url_getVehicle,
		content:{
 			'vehicle':vehicle
 			},
		handleAs:"json",
		load: function(data) {
			document.getElementById('blog_car').innerHTML =data;
			document.getElementsByClassName("overlay")[0].style.display="none";
			
		},
		error: function(err) {
			alert(err);
		}
	});
}
</script>