<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("DRIVER_AND_GUIDE")?></title>
<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<?php $frm =  $this->frm_search;?>
<div class="row">
	<div class="x_panel" >
		 <div class="blog_form_title">
		 	<h4><i class="fa fa-car" aria-hidden="true"></i> <?php echo $tr->translate("DRIVER_AND_GUIDE")?></h4>
		 </div>
		<form id="list" name="list" action="<?php echo $this->url(array('module'=>'driverguide','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
		   <div class="clearfix"></div>
		  	<div class="form-group">
			  	<div class="col-md-2 col-xs-12 mg-10">
		  			<?php echo $frm->getElement("title");?>
		  		</div>
		  		<div class="col-md-2 col-xs-12 mg-10">
		  			<?php echo $frm->getElement("vehicle_type");?>
		  		</div>
		  		<div class="col-md-2 col-xs-12 mg-10">
		  			<?php echo $frm->getElement("province");?>
		  		</div>
		  		<div class="col-md-2 col-xs-12 mg-10">
		  		<?php echo $frm->getElement('status_search');?>
		  		</div>
		  		<div class="col-md-2 col-xs-12 mg-10">
		  		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
		  		</div>
		  	</div>
		</form>
		<?php echo $this->list;?>
	</div>
</div>

