<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm =  $this->frm_search;?>
<title><?php echo $tr->translate("CITYTOURBOOKING");?></title>
<script type="text/javascript">
dojo.ready(function(){
});
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea");
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
</script>
<div class="row">
	<div class="x_panel" >
		 <div class="blog_form_title">
		 	<h4><i class="fa fa-book" aria-hidden="true"></i> <?php echo $tr->translate("CITYTOURBOOKING")?></h4>
		 </div>
		<form id="list" name="list" action="<?php echo $this->url(array('module'=>'booking','controller'=>'citytourbooking','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
		  	<div class="clearfix"></div>
			  <div class="form-group">
				<div class="col-md-2 col-xs-12">
				  <?php echo $frm->getElement("search_text");?>
				</div>
				<div class="col-md-1 col-xs-12">
					<label class="control-label" style="padding-left: 5px;"><?php echo $tr->translate('Booking From')?>
		            </label>
				</div>
				<div class="col-md-2 col-xs-12">
				  <?php echo $frm->getElement('from_book_date');?>
				</div>
				<div class="col-md-1 col-xs-12">
					<label class="control-label" style="padding-left: 5px;"><?php echo $tr->translate('To Booking')?>
		            </label>
				</div>
				<div class="col-md-2 col-xs-12">
				  <?php echo $frm->getElement('to_book_date');?>
				</div>
				<div class="col-md-2 col-xs-12">
					<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				</div>
			  </div>
		</form>
		<?php echo $this->list;?>
	</div>
</div>
