<?php //$filter = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$url = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-groupmember'));
$url_client = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-paymentschedules'));
$frm=$this->frm_search;

//print_r($this->d_payment[0]);
if($this->search['is_paid']==1){
    $ispaid='('.$tr->translate("Is Paid").')';
}else{
    $ispaid='('.$tr->translate("Not Paid").')';
}
 

?>
<script type="text/javascript">
dojo.ready(function(){
	dijit.byId("status").attr("value",1);
});
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea");
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("RPT_COMMISSION_PAYMENT");?></title>
<form method="post">
	
	</form>
<div class="row">
	<div class="x_panel " >
		
		<div style=" width:28cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
		 <form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
			  	<div class="clearfix"></div>
				  <div class="form-group">
					<div class="col-md-2 col-xs-12 mg-10">
					  <?php echo $frm->getElement("search_text");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-10">
					  <?php echo $frm->getElement("driver_search");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-10">
					  <?php echo $frm->getElement('start_date');?>
					</div>
					<div class="col-md-2 col-xs-12 mg-10">
					  <?php echo $frm->getElement('end_date');?>
					</div>
					<div class="col-md-2 col-xs-12 mg-10">
					  <?php echo $frm->getElement('status');?>
					</div>
					
				  </div>
				  <div class="clearfix"></div>
				  
				  <div class="form-group">
				  <div class="col-md-2 col-xs-12">
						<?php echo $frm->getElement('is_paid');?>
					</div>
				  <div class="col-md-2 col-xs-12">
						<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				  </div>
				</div>
			</form>
			<div id="divPrint" style="width: 100%;">
				<style>
				.style{
					line-height: 20px;font-size: 10px !important;
					font-family: 'Khmer OS Battambang';
				}
				th{padding: 5px;}
				tr.header {
				    font-weight: bold;
				    line-height: 14px;
				    font-size: 12px;
				    background: #eee;
				    text-align: center;
				}
				tr.header td {
				    padding: 5px;
				}
				table { page-break-inside:auto }
				tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
					 display: table-header-group;
					 page-break-inside:avoid; page-break-after:auto;
				}
				</style>
				<table style="font-family: 'Khmer OS Content'; width:100%;">
					<tr>
				    	<td align="center">
				    		<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
				            	<tr>
				                	<td width="20%"  valign="top"><img src="<?php echo $this->baseUrl()?>/images/lang/logo.png" height="70px"></td>
				                	<td width="60%" valign="top">
				                	<h2 style="text-align:center; font-size:18px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRANCH_TITLE");?></label></h2>
				                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("RPT_DRIVER_PAID").$ispaid; ?></h2>
				                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo date("d-M-Y",strtotime($this->search['start_date'])) ?> To <?php echo date("d-M-Y",strtotime($this->search['end_date'])) ?></h2>
				                	</td>
				                    <td width="20%"></td>
				                </tr> 
				                <tr>
				                	<td colspan="3">
						              </td>
						           </tr>   
				            </table>
				        </td>
				    </tr>
				    <tr>
				    	<td id="exportExcel" >
				    	<br/>
				            <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:11px; white-space: nowrap;" width="100%" cellspacing="0">
				                 <thead> 
				                 <tr class="header">
				                    <td>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
				                    <td><?php echo $tr->translate("BOOKING_NO");?></td>
				                    <th><?php echo $tr->translate("DRIVER_NAME")?> </th> 
				                    <td><?php echo $tr->translate("Date");?></td>
				                    <td><?php echo $tr->translate("Time");?></td>
				                   <!-- 
				                    <td width="5%"><?php echo $tr->translate("From");?></td>
				                    <td width="5%"><?php echo $tr->translate("To");?></td>
				                     -->
				                    <td><?php echo $tr->translate("Car");?></td>
				                    <td><?php echo $tr->translate("NoPay");?></td>
				                    <td><?php echo $tr->translate("Company Price");?></td>
				                    <td><?php echo $tr->translate("BALANCE");?></td>
				                   <th><?php echo $tr->translate("Other Service Type")?> </th> 
        		    	           <th><?php echo $tr->translate("GRAND_TOTAL")?> </th> 
		    	          		   <th><?php echo $tr->translate("DRIVER_FEE")?></th>
				                   <td><?php echo $tr->translate("USER_NAME");?></td>
				                  <td><?php echo $tr->translate("STATUS");?></td>
				                </tr>
				                 </thead> 
				               <?php  $status_drinver='';  
				               if(!empty($this->d_payment)) foreach($this->d_payment as $key =>$row){
// 				                       if($row['is_paid_commission']==1){
// 				                       	$status_drinver=$tr->translate("COMPLETE");
// 				                       }else{
// 				                       	$status_drinver=$tr->translate("NOT_COMPLETE");
// 				                       }
				               	?>
									<tr align="center" style="line-height: 18px; background: #fff;">
										<td>&nbsp;<?php echo $key+1; ?>&nbsp;</td>
										<td align="left" style="line-height:15px;">&nbsp;<?php echo $row['booking_no'];?></td>	
										<td align="left" style="line-height:15px;">&nbsp;<?php echo $row['driver'];?></td>
										<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo date("d-m-Y",strtotime($row['delivey_date']))?>&nbsp;</td>
										
										
										<td align="left" style="line-height:15px;">&nbsp;<?php echo $row['time'];?></td>
										<!-- 
										<td align="left" style="line-height:15px;">&nbsp;<?php echo $row['from_location'];?></td>
										<td align="left" style="line-height:15px;">&nbsp;<?php echo $row['to_location'];?></td>
										 -->
										<td align="left" style="line-height:15px;">&nbsp;<?php echo $row['vehicle_type'];?></td>
										<td align="left" style="line-height:15px;">&nbsp;<?php if($row['paid']!=0) echo '$&nbsp;'.number_format($row['paid'],2);?></td>
										<td align="left" style="line-height:15px;">&nbsp;<?php echo $row['total'];?></td>
											
										<td align="left" style="line-height:15px;background-color: #fefbd8;">&nbsp;<?php if($row['balance_after']!=0) echo '$&nbsp;'.number_format($row['balance_after'],2);?></td>	
										<td align="left" style="line-height:15px;">&nbsp;<?php if($row['total_service']!=0) echo '$&nbsp;'.number_format($row['total_service'],2);?></td>	
										<td align="left" style="line-height:15px;">&nbsp;<?php if($row['grand_total']!=0) echo '$&nbsp;'.number_format($row['grand_total'],2);?></td>
										<td align="center" style="line-height:15px; background-color: #fefbd8;">&nbsp;<?php if($row['driver_fee_after']!=0) echo '$&nbsp;'.number_format($row['driver_fee_after'],2);?></td>
										<td align="center" style="line-height:15px;">&nbsp;<?php echo $row['user_name'];?></td>
										<td align="center" style="line-height:15px;">&nbsp;<?php echo $row['status'];?></td>
									</tr>
								<?php }?>
				            </table>
				            <br />
				               <table align="center" width="100%">
								   <tr style="font-size: 12px;">
								        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
								        <th></th>
								        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
								   </tr>
							</table>
				    	</td>
				    </tr>
				</table>
			</div>
		</div>
	</div>
</div>