<?php $filter = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$url = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-groupmember'));
$url_client = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-paymentschedules'));
$frm=$this->frm;
?>
<meta charset="utf-8">
<title><?php echo $tr->translate("RPT_CUSTOMER_PAYMENT");?></title>
<script type="text/javascript">
dojo.ready(function(){
});
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea");
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
</script>
<div class="row">
	<div class="x_panel " >
	<div style=" margin:0 auto; padding:0px 0.2cm">
		<form method="post"  action="">
			<div class="form-group">
				  <div class="col-md-2 col-xs-12 mg-10">
				  	<?php echo $frm->getElement('adv_search');?>
				  </div>
				  <div class="col-md-2 col-xs-12 mg-10">
					  <?php echo $frm->getElement('start_date');?>
				  </div>
				  <div class="col-md-2 col-xs-12 mg-10">
					  <?php echo $frm->getElement('end_date');?>
				  </div>
				   <div class="col-md-2 col-xs-12 mg-10">
					  <?php echo $frm->getElement('status');?>
				  </div>
				  <div class="col-md-2 col-xs-12 mg-10">
					  <?php echo $frm->getElement('btn_search');?>
				  </div>
				   <div class="col-md-2 col-xs-12 mg-10">
				 	 
				  </div>
				  <div class="col-md-2 col-xs-12 mg-10">
					   
				  </div>
			  </div>
		</form>
	</div>
		<div style=" width:28cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
			<div id="divPrint" style="width: 100%;">
				<style>
				.style{
					line-height: 20px;font-size: 10px !important;
					font-family: 'Khmer OS Battambang';
				}
				th{padding: 5px;}
				tr.header {
				    font-weight: bold;
				    line-height: 14px;
				    font-size: 12px;
				    background: #eee;
				    text-align: center;
				}
				tr.header td {
				    padding: 5px;
				}
				table { page-break-inside:auto }
				tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
					 display: table-header-group;
					 page-break-inside:avoid; page-break-after:auto;
				}
				</style>
				<table style="font-family: 'Khmer OS Content'; width:100%;">
					<tr>
				    	<td align="center">
				    		<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
				            	<tr>
				                	<td width="20%"  valign="top"><img src="<?php echo $this->baseUrl()?>/images/lang/logo.png" height="70px"></td>
				                	<td width="60%" valign="top">
				                	<h2 style="text-align:center; font-size:18px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRANCH_TITLE");?></label></h2>
				                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("RPT_CUSTOMER_PAYMENT");?></h2>
				                	</td>
				                    <td width="20%"></td>
				                </tr> 
				                <tr>
				                	<td colspan="3">
						              </td>
						           </tr>   
				            </table>
				        </td>
				    </tr>
				    <tr>
				    	<td>
				    	<br/>
				            <table id="exportExcel" border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:11px; white-space: nowrap;" width="100%" cellspacing="0">
				                 <thead> 
				                 <tr class="header">
				                    <td>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
				                    <td><?php echo $tr->translate("RECIEPT_NO");?></td>
				                    <td><?php echo $tr->translate("CUSTOMER");?></td>
				                    <td><?php echo $tr->translate("CUS_PHONE");?></td>
				                    <td><?php echo $tr->translate("PAYMENT_DATE");?></td>
				                    <td><?php echo $tr->translate("PAYMENT_METHOD");?></td>
				                    <td><?php echo $tr->translate("BALANCE");?></td>
				                    <td><?php echo $tr->translate("PAID");?></td>
				                    <td><?php echo $tr->translate("TOTAL_DUE");?></td>
				                    <td><?php echo $tr->translate("USER_NAME");?></td>
				                     <td><?php echo $tr->translate("STATUS");?></td>
				                </tr>
				                 </thead> 
				               <?php  $status_drinver='';
				               if(!empty($this->d_customer)) foreach($this->d_customer as $key =>$row){
// 				                       if($row['s_driver_paid']==1){
// 				                       	$status_drinver=$tr->translate("COMPLETE");
// 				                       }else{
// 				                       	$status_drinver=$tr->translate("NOT_COMPLETE");
// 				                       }
				               	?>
									<tr align="center" style="line-height: 18px; background: #fff;">
										<td>&nbsp;<?php echo $key+1; ?>&nbsp;</td>
										<td align="left" >&nbsp;<a target="_blank" style="color: #333;text-decoration: none;" href="<?php echo $this->baseUrl();?>/report/bookingpayment/rpt-customer-payment-detail/id/<?php echo $row["id"]?>"><?php echo $row['payment_no']; ?></a>&nbsp;</td>
										<td align="left">&nbsp;<a target="_blank" style="color: #333;text-decoration: none;" href="<?php echo $this->baseUrl();?>/report/bookingpayment/rpt-customer-payment-detail/id/<?php echo $row["id"]?>"><?php echo $row['customer'];?></a>&nbsp;</td>
										<td align="left" style="line-height:15px;">&nbsp;<?php echo $row['phone'];?></td>	
										<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo date("d-m-Y",strtotime($row['payment_date']))?>&nbsp;</td>
										<td align="left" style="line-height:15px;">&nbsp;<?php echo $row['payment_method'];?></td>	
										<td align="left" style="line-height:15px;">&nbsp;<?php if($row['balance']!=0) echo '$&nbsp;'.number_format($row['balance'],2);?></td>
										<td align="left" style="line-height:15px;">&nbsp;<?php if($row['paid']!=0) echo '$&nbsp;'.number_format($row['paid'],2);?></td>	
										<td align="left" style="line-height:15px;">&nbsp;<?php if($row['grand_total']!=0) echo '$&nbsp;'.number_format($row['grand_total'],2);?></td>
										<td align="center" style="line-height:15px;">&nbsp;<?php echo $row['user_name'];?></td>
										<td align="center" style="line-height:15px;">&nbsp;<?php echo $row['status'];?></td>
									</tr>
								<?php }?>
				            </table>
				            <br />
				               <table align="center" width="100%">
								   <tr style="font-size: 12px;">
								        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
								        <th></th>
								        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
								   </tr>
							</table>
				    	</td>
				    </tr>
				</table>
			</div>
		</div>
	</div>
</div>