<?php $filter = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$url = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-groupmember'));
$url_client = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-paymentschedules'));
$frm=$this->frm_search;
 
?>
<script type="text/javascript">
dojo.ready(function(){
});
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea");
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("RPT_CUSTOMER_ALERT_TIME");?></title>
<form method="post">
	
	</form>
<div class="row">
	<div class="x_panel " >
		<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
			  	<div class="clearfix"></div>
				  <div class="form-group">
					<div class="col-md-2 col-xs-12 mg-10">
					  <?php echo $frm->getElement("search_text");?>
					</div>
					 
					<div class="col-md-2 col-xs-12 mg-10">
					  <?php echo $frm->getElement('from_book_date');?>
					</div>
					 
					<div class="col-md-2 col-xs-12 mg-10">
					  <?php echo $frm->getElement('to_book_date');?>
					</div>
					<div class="col-md-2 col-xs-12 mg-10">
					   <?php echo $frm->getElement("customer");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-10">
					   <?php echo $frm->getElement("driver_search");?>
					</div>
					
				  </div>
				  <div class="clearfix"></div>
				  <div class="form-group">
					<div class="col-md-2 col-xs-12 mg-10">
						  <?php echo $frm->getElement("working_status");?>
						</div>
					<div class="col-md-2 col-xs-12 mg-10">
						  <?php echo $frm->getElement("status");?>
						</div>
				    <div class="col-md-1 col-xs-12">
							<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				  </div>
			</form>
		<div style=" width:28cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
			<div id="divPrint" style="width: 100%;">
				<style>
				.style{
					line-height: 20px;font-size: 10px !important;
					font-family: 'Khmer OS Battambang';
				}
				th{padding: 5px;}
				tr.header {
				    font-weight: bold;
				    line-height: 14px;
				    font-size: 12px;
				    background: #eee;
				    text-align: center;
				}
				tr.header td {
				    padding: 5px;
				}
				table { page-break-inside:auto }
				tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
					 display: table-header-group;
					 page-break-inside:avoid; page-break-after:auto;
				}
				</style>
				<table style="font-family: 'Khmer OS Content'; width:100%;">
					<tr>
				    	<td align="center">
				    		<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
				            	<tr>
				                	<td width="20%"  valign="top"><img src="<?php echo $this->baseUrl()?>/images/lang/logo.png" height="70px"></td>
				                	<td width="60%" valign="top">
				                	<h2 style="text-align:center; font-size:18px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRANCH_TITLE");?></label></h2>
				                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("RPT_CUSTOMER_ALERT_TIME");?></h2>
				                	</td>
				                    <td width="20%"></td>
				                </tr> 
				                <tr>
				                	<td colspan="3">
						              </td>
						           </tr>   
				            </table>
				        </td>
				    </tr>
				    <tr>
				    	<td>
				    	<br/>
				            <table id="exportExcel" border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:11px; white-space: nowrap;" width="100%" cellspacing="0">
				                 <thead> 
				                 <tr class="header">
				                    <td>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
				                    <td><?php echo $tr->translate("BOOKING_NO");?></td>
				                    <td><?php echo $tr->translate("CUSTOMER_NAME");?></td>
				                    <td><?php echo $tr->translate("CUS_PHONE");?></td>
				                    <td><?php echo $tr->translate("FROM_LOCATION");?></td>
				                    <td><?php echo $tr->translate("TO_LOCATION");?></td>
				                    <td><?php echo $tr->translate("BOOKING_DATE");?></td>
				                    <td><?php echo $tr->translate("DELIVERY_DATE");?></td>
				                    <td><?php echo $tr->translate("DRIVER");?></td>
				                    <td><?php echo $tr->translate("PHONE");?></td>
			                        <td><?php echo $tr->translate("BOOKING_STATUS");?></td>
			                        <td><?php echo $tr->translate("TIME_STATUS");?></td>
			                        <th><?php echo $tr->translate("DELIVERY_TIME")?></th> 
			                        <th><?php echo $tr->translate("ACTIVE")?></th> 
				                </tr>
				                 </thead> 
				               <?php  $status_drinver='';	
				               $offet=strtotime("+2 hours");
				               $gogletime=date("H:i:s",$offet);
				               $time_now=date("H:i:s");
				               
				               $hour=0;
				               if(!empty($this->d_customer)) foreach($this->d_customer as $key =>$row){
				               	if($gogletime >= $row['time_zone'] && strtotime(date("Y-m-d"))==strtotime($row['delivey_date'])){
				               		if($gogletime >= $row['time_zone']){
				               			$time=$tr->translate("Nearly hours");
				               		}
				               		if($time_now >= $row['time_zone']){
				               			$time=$tr->translate("Late hours");
				               		}
				               	?>
									<tr align="center" style="line-height: 18px; background: #fff;">
										<td>&nbsp;<?php echo $key+1;  ?>&nbsp;</td>
										<td align="left" >&nbsp;<?php echo $row['booking_no']?>&nbsp;</td>
										<td align="left">&nbsp;<?php  echo $row['cus_name'];?>&nbsp;</td>
										<td align="left">&nbsp;<?php  echo $row['cus_phone'];?>&nbsp;</td>
										<td align="left">&nbsp;<?php  echo $row['from_location'];?>&nbsp;</td>
										<td align="left"><span style="line-height:15px;">&nbsp;<?php echo $row['to_location']; ?></span>&nbsp;</td>	
										<td style="white-space:nowrap; text-align: right;">&nbsp;<?php echo date("D, d-M-Y",strtotime($row['booking_date']));?>&nbsp;</td>
										<td align="left" style="line-height:15px;">&nbsp;<?php echo date("D, d-M-Y",strtotime($row['delivey_date']));?> </td>	
										<td align="center" style="line-height:15px;">&nbsp; <?php echo $row['driver'];?></td>
										<td align="center" style="line-height:15px;">&nbsp; <?php echo $row['driver_phone'];?></td>
										<td align="center" style="line-height:15px;">&nbsp;<?php  echo $row['book_status'];?></td>
										<td align="center" style="border: 1px solid #000;color: red;font-weight: bold;">&nbsp;<?php echo $time;?> </td>
										<td align="center" style="line-height:15px;">&nbsp;<?php  echo $row['delivey_time'];?></td>
										<td align="center" style="line-height:15px;">&nbsp;<?php  echo $row['status'];?></td>
									</tr>
								<?php }
				              }?>
				            </table>
				            <br />
				               <table align="center" width="100%">
								   <tr style="font-size: 12px;">
								        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
								        <th></th>
								        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
								   </tr>
							</table>
				    	</td>
				    </tr>
				</table>
			</div>
		</div>
	</div>
</div>