<?php $filter = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$url = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-groupmember'));
$url_client = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-paymentschedules'));
$frm=$this->frm;
$commission = $this->commision_payment;
?>
<meta charset="utf-8">
<title><?php echo $tr->translate("RPT_COMMISSION_DETAIL");?></title>
<style>
span.label_title {
    color: #4e5e6b;
    font-weight: 600;
}
span.label_value {
    color: #000;
    font-weight: 600;
}
 
</style>
<div class="row">
	<div class="x_panel " >
		<div style=" width:28cm;min-height:28cm;margin:0 auto;border: 1px dotted #ccc;padding: 0.2cm 0.2cm;">
			<div id="divPrint" style="width: 100%;">
				<style>
					tr.header td {
					    font-weight: 700;
					    padding: 5px;
					    text-align: center;
					}
					.row-value{
					    padding: 5px 0;
					    border-left: solid 1px #000;
						border-bottom: solid 1px #000;
						border-top: solid 1px #000;
					}
					.one-td{
					    padding: 5px 0;
					    border-left: solid 1px #000;
						border-bottom: solid 1px #000;
						border-right: solid 1px #000;
					}
					.row-td{
					    padding: 5px 0;
					    border-left: solid 1px #000;
						border-bottom: solid 1px #000;
					}
 
				</style>
				<table width="100%"  class="print" cellspacing="0"  cellpadding="0" style=" font-family: 'Khmer OS Battambang' !important; white-space:nowrap;">
					<tr >
						<td colspan="3"  style="" align="center" valign="top">
							<table width="100%" style=" line-height: 18px;font-size: 14px;margin-bottom: 0px;background: #8495a2;    color: #fff;" >
								<tr>
									<td width="40%" valign="middle">
										<h2 style="margin: 10px 0; padding-left: 20px; font-weight: 700; vertical-align: middle;  font-size: 30px;">RECIEPT</h2>
									</td>
									<td width="35%" valign="top" >
										012 999 888 / 010 999 888<br />
										carrental@gmail.com
									</td>
									<td width="25%" valign="top">
										Porsen Chey, Dang Kor, Phnom Penh Cambodia.
									</td>
								</tr>
							</table>
						</td>
					</tr>
					<tr>
						<td colspan="3"  valign="top">
							<table width="100%" style=" line-height: 18px; font-size: 14px; margin: 5px 0; " >
								<tr>
									<td width="40%" style=" line-height: 18px;" valign="top">
										<span class="label_title"><?php echo $tr->translate("DRIVER_NAME");?>&nbsp;:&nbsp;&nbsp;<?php echo $commission['driver_name'];?></span><br />
										<span class="label_title"><?php echo $tr->translate("PHONE");?>&nbsp;:&nbsp;&nbsp;<?php echo $commission['phone'];?></span><br />
										<span class="label_title"><?php echo $tr->translate("EMAIL");?>&nbsp;:&nbsp;&nbsp;<?php echo $commission['email'];?></span><br /> 
									</td>
									<td width="40%" valign="top" style=" line-height: 18px;" valign="top">
										<span class="label_title">Receipt N<sup>o</sup>&nbsp;:&nbsp;&nbsp;<?php echo $commission['payment_no'];?></span><br />
										<span class="label_title">Payment Date&nbsp;:&nbsp;&nbsp;<?php echo date("d-M-Y",strtotime($commission['payment_date']));?></span><br />
									</td>
									<td width="20%" valign="top" align="right" style=" line-height: 18px;">
										<span class="label_title">Total Payment</span><br />
										<span class="label_value" style=" font-size: 20px;   font-weight: 700;    color: #0c0c0c;"><?php echo "$ ".number_format($commission['paid'],2);?></span>
									</td>
								</tr>
							</table>
						</td>
					</tr>
					<tr>
						<td  valign="top" colspan="3" style="  border-top: solid 2px #8495a2;height: 0px;">&nbsp;</td>
					</tr>
					<tr>
						<td colspan="3" valign="top">
							<table width="100%" style=" line-height: 14px; font-size: 14px; margin: 0; "    cellspacing="0" >
								<tr class="header" style="background: #e4e4e4">
									<td class="row-value">No</td>
									<td class="row-value">Booking No</td>
									<td class="row-value">Driver Fee</td>
									<td class="row-value">Paid</td>
									<td class="one-td row-value" >Balance</td>
								</tr>
								<?php $i=0; 
								$total_paid=0;
								$total_remain=0;
								foreach ($this->commision_detail as $com){ $i++;
								$total_remain = $total_remain + $com['remain'];
								$total_paid = $total_paid + $com['paid'];
								?>
								<tr>
									<td  class="row-td" align="center" ><?php echo $i;?></td>
									<td  class="row-td" align="center"><?php echo $com['booking_no'];?></td>
									<td  class="row-td" align="center"><?php echo "$ ".number_format($com['due_amount'],2);?></td>
									<td  class="row-td" align="center"><?php echo "$ ".number_format($com['paid'],2);?></td>
									<td  class="one-td "  align="center"><?php echo "$ ".number_format($com['remain'],2);?></td>
								</tr>
								<?php }?>
								<tr>
									<td colspan="2">&nbsp;</td>
									<td colspan="2" align="right"><span class="label_title">Total Paid&nbsp;</span></td>
									<td align="center" class="one-td" ><?php echo "$ ".number_format($total_paid,2);?></td>
								</tr>
								<tr>
									<td colspan="2">&nbsp;</td>
									<td colspan="2" align="right"><span class="label_title">Total Balance&nbsp;</span></td>
									<td align="center" class="one-td"><?php echo "$ ".number_format($total_remain,2);?></td>
								</tr>
								<tr>
									<td colspan="2">&nbsp;</td>
									<td colspan="2" align="right" ><span class="label_title">Payment Type&nbsp;</span></td>
									<td align="center" class="one-td"><?php echo $commission['payment_method'];?></td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>