<?php $filter = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$url = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-groupmember'));
$url_client = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-paymentschedules'));
$frm=$this->frm;
$commission = $this->commision_payment;
?>
<meta charset="utf-8">
<title><?php echo $tr->translate("RPT_COMMISSION_DETAIL");?></title>
<style>
span.label_title {
    color: #4e5e6b;
    font-weight: 600;
}
span.label_value {
    color: #000;
    font-weight: 600;
}
</style>
<div class="row">
	<div class="x_panel " >
		<div style=" width:28cm;min-height:28cm;margin:0 auto;border: 1px dotted #ccc;padding: 0.2cm 0.2cm;">
			<div id="divPrint" style="width: 100%;">
				<style>
					tr.header td {
					    font-weight: 700;
					    padding: 5px;
					    text-align: center;
					}
					tr.row-value td {
					    padding: 10px 0;
					    border-bottom: solid 1px #eee;
					}
				</style>
				<table width="100%"  class="print" cellspacing="0"  cellpadding="0" style=" font-family: 'Khmer OS Battambang' !important; white-space:nowrap;">
					<tr >
						<td colspan="3"  style="" align="center" valign="top">
							<table width="100%" style=" line-height: 18px;font-size: 14px;margin-bottom: 0px;background: #8495a2;    color: #fff;" >
								<tr>
									<td width="40%" valign="middle">
										<h2 style="margin: 10px 0; padding-left: 20px; font-weight: 700; vertical-align: middle;  font-size: 30px;">RECIEPT</h2>
									</td>
									<td width="35%" valign="top" >
										012 999 888 / 010 999 888<br />
										carrental@gmail.com
									</td>
									<td width="25%" valign="top">
										Porsen Chey, Dang Kor, Phnom Penh Cambodia.
									</td>
								</tr>
							</table>
						</td>
					</tr>
					<tr>
						<td colspan="3"  valign="top">
							<table width="100%" style=" line-height: 18px; font-size: 14px; margin: 40px 0; " >
								<tr>
									<td width="40%" valign="middle">
										<span class="label_title">Bill To Agency :</span><br />
										<span class="label_value"><?php echo $commission['first_name']." ".$commission['last_name'];?></span><br />
										<span class="label_value"><?php echo $commission['phone'];?></span><br />
										<span class="label_value"><?php echo $commission['email'];?></span><br />
									</td>
									<td width="40%" valign="top" >
										<span class="label_title">Receipt N<sup>o</sup> :</span><br />
										<span class="label_value"><?php echo $commission['payment_no'];?></span><br />
										<span class="label_title">Payment Date :</span><br />
										<span class="label_value"><?php echo date("d-M-Y",strtotime($commission['payment_date']));?></span><br />
									</td>
									<td width="20%" valign="top" align="right">
										<span class="label_title">Total Payment</span><br />
										<h2 class="label_value" style=" font-size: 28px;   font-weight: 700;    color: #0c0c0c;"><?php echo "$ ".number_format($commission['paid'],2);?></h2>
									</td>
								</tr>
							</table>
						</td>
					</tr>
					<tr>
						<td colspan="3" style="  border-top: solid 2px #8495a2;">&nbsp;</td>
					</tr>
					<tr>
						<td colspan="3">
							<table width="100%" style=" line-height: 14px; font-size: 14px; margin: 0; " >
								<tr class="header">
									<td>No</td>
									<td>Booking No</td>
									<td>Comission Fee</td>
									<td>Paid</td>
									<td>Balance</td>
								</tr>
								<?php $i=0; 
								$total_paid=0;
								$total_remain=0;
								foreach ($this->commision_detail as $com){ $i++;
								$total_remain = $total_remain + $com['remain'];
								$total_paid = $total_paid + $com['paid'];
								?>
								<tr class="row-value">
									<td align="center"><?php echo $i;?></td>
									<td align="center"><?php echo $com['booking_no'];?></td>
									<td align="center"><?php echo "$ ".number_format($com['due_amount'],2);?></td>
									<td align="center"><?php echo "$ ".number_format($com['paid'],2);?></td>
									<td align="center"><?php echo "$ ".number_format($com['remain'],2);?></td>
								</tr>
								<?php }?>
								<tr>
									<td colspan="2">&nbsp;</td>
									<td colspan="2" align="right"><span class="label_title">Total Paid</span></td>
									<td align="center"><?php echo "$ ".number_format($total_paid,2);?></td>
								</tr>
								<tr>
									<td colspan="2">&nbsp;</td>
									<td colspan="2" align="right"><span class="label_title">Total Balance</span></td>
									<td align="center"><?php echo "$ ".number_format($total_remain,2);?></td>
								</tr>
								<tr>
									<td colspan="2">&nbsp;</td>
									<td colspan="2" align="right"><span class="label_title">Payment Type</span></td>
									<td align="center"><?php echo $commission['payment_method'];?></td>
								</tr>
							</table>
						</td>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>