<?php  
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$url = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-groupmember'));
$url_client = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-paymentschedules'));
$frm=$this->frm_search;
//print_r($this->d_payment);
 
?>
<script type="text/javascript">

dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea");
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
dojo.ready(function(){
	 
	dijit.byId("to_book_date").attr("value","<?php echo $this->search['to_book_date']?>");
});
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("RPT_BOOKING_CLEARED");?></title>
<form method="post">
	
	</form>
<div class="row" style="width:100%;background: #fff;">
	<div class="x_panel " >
	 
		<div style=" width:28cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm;">
			 <form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
			  	<div class="clearfix"></div>
				  <div class="form-group">
					<div class="col-md-2 col-xs-12 mg-12">
					  <?php echo $frm->getElement("search_text");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-12">
					   <?php echo $frm->getElement("agency_search");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-12">
					   <?php echo $frm->getElement("driver_search");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-12">
					   <?php echo $frm->getElement("customer");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-12">
					   <?php echo $frm->getElement("vehicle_type");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-12">
					 <?php echo $frm->getElement("working_status");?>
					</div>
				  </div>
				  <div class="clearfix"></div>
				  <div class="form-group">
					<div class="col-md-2 col-xs-12 mg-12">
					 <?php echo $frm->getElement('from_book_date');?>
					</div>
					<div class="col-md-2 col-xs-12 mg-12">
					   <?php echo $frm->getElement('to_book_date');?>
					</div>
					<div class="col-md-2 col-xs-12 mg-12">
					    <?php echo $frm->getElement("start_time");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-12">
					   <?php echo $frm->getElement("delivery_time");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-12">
					   <?php echo $frm->getElement("date_type");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-12">
					   <?php echo $frm->getElement("status");?>
					</div>
				  </div>
				   <div class="clearfix"></div>
				   
				  <div class="form-group">
					 <!-- <label class="control-label col-md-11 col-sm-11 mg-12" for="first-name">  </label> -->
					<div class="col-md-1 mg-12">
							<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				  </div>
				  <div class="clearfix"></div>
			</form>
			<div id="divPrint" style="width: 100%;">
				<style>
				.style{
					line-height: 20px;font-size: 10px !important;
					font-family: 'Khmer OS Battambang';
				}
				th{padding: 5px;}
				tr.header {
				    font-weight: bold;
				    line-height: 14px;
				    font-size: 12px;
				    background: #eee;
				    text-align: center;
				}
				tr.header td {
				    padding: 5px;
				}
				</style>
				<table style="font-family: 'Khmer OS Content'; width:100%;background: #fff;">
					<tr>
				    	<td align="center">
				    		<table width="100%" style="font-family: 'Khmer OS Battambang';margin:0; padding:0;border:none;background: #fff;"  >
				            	<tr>
				                	<td width="20%"  valign="top"><img src="<?php echo $this->baseUrl()?>/images/lang/logo.png" height="70px"></td>
				                	<td width="60%" valign="top">
				                	<h2 style="text-align:center; font-size:18px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRANCH_TITLE");?></label></h2>
				                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("RPT_BOOKING_CLEARED");?></h2>
				                	</td>
				                    <td width="20%"></td>
				                </tr> 
				                <tr>
				                	<td colspan="3">
						              </td>
						           </tr>   
				            </table>
				        </td>
				    </tr>
				    <tr>
				    	<td id="exportExcel">
				    	<br/>
				            <table  border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:11px; white-space: nowrap;background: #fff;" width="100%" cellspacing="0">
				               <thead>
				    			  <tr>  
				    		  	  <th><?php echo $tr->translate("NUM")?></th> 
				    		      <th><?php echo $tr->translate("BOOKING_NO")?></th> 
				    		      <th><?php echo $tr->translate("BOOKING_DATE")?> </th> 
				    	          <th><?php echo $tr->translate("DELIVERY_DATE")?></th> 
				    	          <th><?php echo $tr->translate("DELIVERY_TIME")?></th> 
				    	          <th><?php echo $tr->translate("OTHER_BOOKING_NO")?></th>
				    		      <th><?php echo $tr->translate("FROM_LOCATION")?> </th> 
				    	          <th><?php echo $tr->translate("TO_LOCATION")?></th> 
				                  
				                  
				    	          <th><?php echo $tr->translate("VEHICLE_TYPE")?></th> 
				    	          <th><?php echo $tr->translate("NoPay")?> </th> 
				    	          <th><?php echo $tr->translate("Company Price")?> </th> 
				    	          <th><?php echo $tr->translate("CARPRICE")?> </th> 
				    	          <th><?php echo $tr->translate("BALANCE")?> </th> 
				    	           <th><?php echo $tr->translate("Other Service Type")?> </th> 
				    	          <th><?php echo $tr->translate("GRAND_TOTAL")?> </th> 
				    	          <th><?php echo $tr->translate("AGENCY_NAME")?> </th> 
				    	          
				    	          <th><?php echo $tr->translate("COMMISSION_FEE")?></th> 
				    	          
				    	          <th><?php echo $tr->translate("DRIVER")?> </th> 
				    	          <th><?php echo $tr->translate("DRIVER_FEE")?></th> 
				    	          <th><?php echo $tr->translate("BOOKING_STATUS")?> </th> 
				    	           <th><?php echo $tr->translate("NOTE")?> </th> 
				    	          <th><?php echo $tr->translate("USER")?></th> 
				    	          <th><?php echo $tr->translate("STATUS")?></th> 
				             </tr>
				             </thead>
				               <?php  $status_drinver='';
				               if(!empty($this->rows)) foreach($this->rows as $key =>$rs){
				                       if($rs['status']==1){
				                       	$status=$tr->translate("ACTIVE");
				                       }else{
				                       	$status=$tr->translate("DEACTIVE");
				                       }
				                       $d=strtotime($rs['delivey_time']);
				                       
				               	?>
									 <tr class=" alternate  normal"    >
								       <td class="text-center"> <?php echo $key+1?></td>
								       <td class="text-center"> <?php echo $rs['booking_no']?></td> 
								       <td><?php echo date("d-M-Y",strtotime($rs['booking_date'])).'&nbsp;'.date("H:i",strtotime($rs['create_date']));?> </td> 
								       <td class="text-center"> <?php echo date("D, d-M-Y",strtotime($rs['delivey_date']));?> </td>
								       <td class="text-center"> <?php echo date("H:i:a", $d);?> </td>
								       <td class="text-center" style="text-align:left;  " > <?php echo $rs['payment_booking_no']?></td> 
								       <td  > <?php echo $rs['from_location']?></td> 
								       <td  ><?php echo $rs['to_location']?> </td>
								      
								       <td class="text-center"><?php echo $rs['vehicle_type']?> </td>
								       <td class="text-center" <?php //echo $paid_color;?>> <?php echo ($rs['paid']==0)?"":"$&nbsp;".number_format($rs["paid"],2);?> </td>
								       <td class="text-center"> <?php echo ($rs['total']==0)?"":"$&nbsp;".number_format($rs["total"],2);?> </td>
								       <td class="text-center"> <?php echo ($rs['price']==0)?"":"$&nbsp;".number_format($rs["price"],2);?> </td>
								       <td class="text-center"> <?php echo ($rs['balance_after']==0)?"":"$&nbsp;".number_format($rs["balance_after"],2);?></td> 
								        <td class="text-center"><?php echo ($rs['total_service']==0)?"":"$&nbsp;".number_format($rs["total_service"],2);?> </td>
								       <td class="text-center">  <?php echo ($rs['grand_total']==0)?"":"$&nbsp;".number_format($rs["grand_total"],2);?></td> 
								       <td class="text-center"  ><?php echo $rs['agency_name']?> </td>
								       <td class="text-center"> <?php echo ($rs['commision_fee_after']==0)?"":"$&nbsp;".number_format($rs["commision_fee_after"],2);?></td> 
								       <td class="text-center"  > <?php echo $rs['driver']?></td>
								       <td class="text-center"><?php echo ($rs['driver_fee_after']==0)?"":"$&nbsp;".number_format($rs["driver_fee_after"],2);?> </td>
								       <td class="text-center" style="background:#fff"> <?php echo $rs['book_status']?> </td>
								       <td align="left"> <?php 	echo(empty($rs['note']))?"":"".substr($rs['note'],0,30)."..."?></td>
								        <td class="text-center"> <?php echo $rs['user_name']?></td>
								        <td class="text-center"> <?php echo $status?></td>
								     </tr>
								<?php }?>
				            </table>
				            <br />
				               <table align="center" width="100%">
								   <tr style="font-size: 12px;">
								        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
								        <th></th>
								        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
								   </tr>
							</table>
				    	</td>
				    </tr>
				</table>
			</div>
		</div>
	</div>
</div>