<?php $filter = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$url = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-groupmember'));
$url_client = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-paymentschedules'));
$frm=$this->frm;
$commission = $this->commision_payment;
//print_r($commission);
?>
<meta charset="utf-8">
<title><?php echo $tr->translate("RPT_COMMISSION_DETAIL");?></title>
<style>
span.label_title {
    color: #4e5e6b;
    font-weight: 600;
}
span.label_value {
    color: #000;
    font-weight: 600;
}
 
</style>
<div class="row">
	<div class="x_panel " >
		<div style=" width:28cm;min-height:28cm;margin:0 auto;border: 1px dotted #ccc;padding: 0.2cm 0.2cm;">
			<div id="divPrint" style="width: 100%;">
				<style>
					tr.header td {
					    font-weight: 700;
					    padding: 5px;
					    text-align: center;
					}
					.row-value{
					    padding: 5px 0;
					    border-left: solid 1px #000;
						border-bottom: solid 1px #000;
						border-top: solid 1px #000;
					}
					.one-td{
					    padding: 5px 0;
					    border-left: solid 1px #000;
						border-bottom: solid 1px #000;
						border-right: solid 1px #000;
					}
					.row-td{
					    padding: 5px 0;
					    border-left: solid 1px #000;
						border-bottom: solid 1px #000;
					}
					
				table { page-break-inside:auto }
                tr{ page-break-inside:avoid; page-break-after:auto }
			   #header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					}
 
				</style>
				<table width="100%"  class="print" cellspacing="0"  cellpadding="0" style=" font-family: 'Khmer OS Battambang' !important; white-space:nowrap;background: #fff;">
					<tr >
						<td colspan="3"  style="" align="center" valign="top">
							<table width="100%" style=" line-height: 18px;font-size: 14px;margin-bottom: 0px;background: #e4e4e4;color: #000;" >
								<tr>
									<td width="20%" valign="middle">
										<h2 style="margin: 10px 0; padding-left: 0px; font-weight: 700; vertical-align: middle;  font-size: 30px;"><?php echo $tr->translate("INVOICE");?></h2>
									</td>
									<td width="50%" valign="top" align="center">
									    <?php echo $this->tel['value'];?><br/>
										<!-- 012 999 888 / 010 999 888<br /> carrental@gmail.com-->
										<?php echo $this->email['value'];?>
									</td>
									<td width="30%" valign="top"  align="center">
									<?php echo $this->address['value'];?>
									<!-- Porsen Chey, Dang Kor, Phnom Penh Cambodia. -->	
									</td>
								</tr>
							</table>
						</td>
					</tr>
					<tr>
						<td colspan="3"  valign="top">
							<table width="100%" style=" line-height: 18px; font-size: 14px; margin: 5px 0; " >
								<tr>
									<td width="40%" style=" line-height: 18px;" valign="top">
										<span class="label_title"><?php echo $tr->translate("AGENCY_NAME");?>&nbsp;:&nbsp;&nbsp;<?php echo $commission['agency_name'];?></span><br />
										<span class="label_title"><?php echo $tr->translate("PHONE");?>&nbsp;:&nbsp;&nbsp;<?php echo $commission['agency_phone'];?></span><br />
										<span class="label_title"><?php echo $tr->translate("EMAIL");?>&nbsp;:&nbsp;&nbsp;<?php echo $commission['agency_email'];?></span><br /> 
									</td>
									<td width="30%" valign="top" align="right" style=" line-height: 18px;">
										<span class="label_title"> </span><br />
										<span class="label_value" style=" font-size: 20px;   font-weight: 700;    color: #0c0c0c;"><?php //echo "$ ".number_format($commission['paid'],2);?></span>
									</td>
									<td width="20%" valign="top" style=" line-height: 18px;" valign="top">
										<span class="label_title">Receipt N<sup>o</sup>&nbsp;:&nbsp;&nbsp;<?php echo $commission['payment_no'];?></span><br />
										<span class="label_title"><?php echo $tr->translate("DATE_​PAYMENT");?>&nbsp;:&nbsp;&nbsp;<?php echo date("d-M-Y",strtotime($commission['payment_date']));?></span><br />
									</td>
									
								</tr>
							</table>
						</td>
					</tr>
					<tr>
						<td  valign="top" colspan="3" style="  border-top: solid 2px #8495a2;height: 0px;">&nbsp;</td>
					</tr>
					<tr>
						<td colspan="3" valign="top" id="exportExcel">
							<table width="100%" style=" line-height: 14px; font-size: 14px; margin: 0; "    cellspacing="0"  >
								<thead>
								<tr class="header" style="background: #e4e4e4">
									<td class="row-value"  style="width: 2%;"><?php echo $tr->translate("NUM");?></td>
									<td class="row-value"  style="width: 5%;"><?php echo $tr->translate("Date");?></td>
									<td class="row-value"  style="width: 5%;"><?php echo $tr->translate("Time");?></td>
									<td class="row-value"  style="width: 5%;"><?php echo $tr->translate("Code or Room");?></td>
									
									<td class="row-value " style="width: 20%;" ><?php echo $tr->translate("From");?></td>
									<td class="row-value"  style="width: 20%;" ><?php echo $tr->translate("To");?></td>
									<td class="row-value"  style="width: 5%;"><?php echo $tr->translate("Car");?></td>
									
									<td class="row-value"  style="width: 5%;"><?php echo $tr->translate("Pay");?></td>
									<td class="row-value"  style="width: 5%;"><?php echo $tr->translate("NOPAY");?></td>
									<td class="row-value"   nowrap><?php echo $tr->translate("COMMISSION_FEE");?> </td>
									<td class="row-value " style="border-right: solid 1px #000;"><?php echo $tr->translate("Remark");?> </td>​
								</tr>
								</thead>
								<?php $i=0; 
								$total_paid=0;
								$total_remain=0;$total_commistion=0;$total_all_a_re=0;
								$paid=0;$com_price=0;
								foreach ($this->commision_detail as $com){ $i++;
								$paid=$paid+$com['paid'];
								$com_price=$com_price+$com['conpany_price'];
								?>
								<tr>
									<td  class="row-td" align="center" >&nbsp;<?php echo $i;?></td>
									 
									<td  class="row-td" nowrap>&nbsp;<?php echo date("d-M-Y",strtotime($com['delivey_date']));?>&nbsp;</td>
									<td  class="row-td" >&nbsp;<?php echo $com['time'];?></td>
									<td  class="row-td" >&nbsp;<?php echo $com['payment_booking_no'];?></td>
									<td  class="row-td" >&nbsp;<?php echo $com['from_loc'];?></td>
									<td  class="row-td" >&nbsp;<?php echo $com['to_loc'];?></td>
									<td  class="one-td" >&nbsp;<?php echo $com['vehicle_type'];?></td>
									<td  class="row-td" nowrap>&nbsp;<?php echo ($com['paid']==0)?"":"$&nbsp;".number_format($com['paid'],2);?> </td>
									<td  class="row-td"  >&nbsp;<?php echo ($com['conpany_price']==0)?"":"$&nbsp;".number_format($com['conpany_price'],2);?>  </td>
									<td  class="row-td" nowrap>&nbsp;<?php echo ($com['gency_fee']==0)?"":"$&nbsp;".number_format($com['gency_fee'],2);?> </td>
									<td  class="one-td" >&nbsp;<?php echo $com['note'];?></td>
								</tr>
								<?php }?>
								 <tr>
									<td colspan="7">&nbsp;</td>
									<td colspan="2" align="right"><span class="label_title"><?php echo $tr->translate("TOTAL_NOPAY");?>&nbsp;</span></td>
									<td colspan="2" align="left" class="one-td" >&nbsp;<?php echo "$ ".number_format($paid,2);?></td>
								</tr>
								<tr>
									<td colspan="7">&nbsp;</td>
									<td colspan="2" align="right"><span class="label_title"><?php echo $tr->translate("TOTAL_COMPANY_PRICE");?>&nbsp;</span></td>
									<td colspan="2" align="left" class="one-td"> &nbsp;<?php echo "$ ".number_format( $com_price,2);?></td>
								</tr>
								<tr>
								<?php $paid=0;
// 								    if($total_commistion<$total_all_a_re){
// 								    	$str='Agency Paid';
// 								    	$paid=$total_all_a_re-$total_commistion;
// 								    }else{
// 								    	$str='Payment To Agency';
// 								    	$paid=$total_commistion-$total_all_a_re;
// 								    }
								?>
									<td colspan="7">&nbsp;</td>
									<td colspan="2" align="right" ><span class="label_title"><?php echo $this->commision_payment['paid_type'];?>&nbsp;</span></td>
									<td colspan="2" align="left" class="one-td">&nbsp;<?php echo "$ ".number_format($this->commision_payment['paid_agen'],2);?></td>
								</tr>
								<tr>
									<td colspan="7">&nbsp;</td>
									<td colspan="2" align="right"><span class="label_title"><?php echo $tr->translate("Debit");?>&nbsp;</span></td>
									<td colspan="2" align="left" class="one-td"> &nbsp;<?php echo "$ ".number_format($this->commision_payment['balance'],2);?></td>
								</tr>
								<tr>
								    <td height="50px;"  colspan="8"></td>
								</tr>
								<tr>
				                   <td nowrap style="padding-left: 60px;line-height: normal;" align="left"​ colspan="3" >
				                   			<hr>
				                       		Customer's signature<br/><br/><br/><br/>  
				                       <?php  echo $tr->translate("DATE").':.......................................'?>
				                       
				                   </td>
				                   <td colspan="4"></td>
				                   <td  style="padding-left: 100px;line-height: normal;" align="left"  colspan="3" nowrap>
				                     <?php $session_user=new Zend_Session_Namespace('auth');
								           //$last_name=$session_user->username;
								           $username = $session_user->fullname;
						       			?>
				                        <?php //echo $tr->translate("USER_NAME");?><?php //echo $username ?> 
				                       		<!--  ហត្ថលេខា និងឈ្មោះអ្នកគិតលុយ<br/> --> 
				                       		<hr>
				                       		 Receiver's Signature<br/><br/><br/><br/>  
				                       <?php  echo $tr->translate("DATE").':.......................................'?>
				                   </td>
				                </tr>
								
							</table>
						</td>
					</tr>
				</table>
			</div>
		</div>
	</div>
</div>