<?php $filter = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$url = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-groupmember'));
$url_client = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-paymentschedules'));
$frm=$this->frm_search;
 
?>
<script type="text/javascript">
dojo.ready(function(){
});
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea");
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("RPT_CAR_BOOKING");?></title>
<form method="post">
	
	</form>
<div class="row">
	<div class="x_panel " >
		<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
			  	<div class="clearfix"></div>
				  <div class="form-group">
					<div class="col-md-2 col-xs-12 mg-10">
					  <?php echo $frm->getElement("search_text");?>
					</div>
					 
					<div class="col-md-2 col-xs-12 mg-10">
					  <?php echo $frm->getElement('from_book_date');?>
					</div>
					 
					<div class="col-md-2 col-xs-12 mg-10">
					  <?php echo $frm->getElement('to_book_date');?>
					</div>
					<div class="col-md-2 col-xs-12 mg-10">
						  <?php echo $frm->getElement("date_type");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-10">
					   <?php echo $frm->getElement("customer");?>
					</div>
				  </div>
				  
				  <div class="clearfix"></div>
				  <div class="form-group">
					<div class="col-md-2 col-xs-12 mg-10">
					   <?php echo $frm->getElement("agency_search");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-10">
					   <?php echo $frm->getElement("driver_search");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-10">
					   <?php echo $frm->getElement("vehicle_type");?>
					</div>
					<div class="col-md-2 col-xs-12 mg-10">
						  <?php echo $frm->getElement("working_status");?>
						</div>
					<div class="col-md-2 col-xs-12 mg-10">
						  <?php echo $frm->getElement("status");?>
						</div>
				    <div class="col-md-1 col-xs-12">
							<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				  </div>
			</form>
		<div style=" width:28cm;min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
			<div id="divPrint" style="width: 100%;">
				<style>
				.style{
					line-height: 20px;font-size: 10px !important;
					font-family: 'Khmer OS Battambang';
				}
				th{padding: 5px;}
				tr.header {
				    font-weight: bold;
				    line-height: 14px;
				    font-size: 12px;
				    background: #eee;
				    text-align: center;
				}
				tr.header td {
				    padding: 5px;
				}
				</style>
				<table style="font-family: 'Khmer OS Content'; width:100%;">
					<tr>
				    	<td align="center">
				    		<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
				            	<tr>
				                	<td width="20%"></td>
				                	<td width="60%" valign="top">
				                	<h2 style="text-align:center; font-size:18px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("BRANCH_TITLE");?></label></h2>
				                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("RPT_CAR_BOOKING");?></h2>
				                	</td>
				                    <td width="20%"></td>
				                </tr> 
				                <tr>
				                	<td colspan="3">
						              </td>
						           </tr>   
				            </table>
				        </td>
				    </tr>
				    <tr>
				    	<td>
				            <table id="exportExcel" border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:11px; white-space: nowrap;" width="100%" cellspacing="0">
				                <tr class="header">  
				    		  	  <th><?php echo $tr->translate("NUM")?></th> 
				    		      <th><?php echo $tr->translate("BOOKING_NO")?></th> 
				    		      <th><?php echo $tr->translate("BOOKING_DATE")?> </th> 
				    	          <th><?php echo $tr->translate("DELIVERY_DATE")?></th> 
				    	          <th><?php echo $tr->translate("DELIVERY_TIME")?></th> 
				    	          <th><?php echo $tr->translate("OTHER_BOOKING_NO")?></th>
				    		      <th><?php echo $tr->translate("FROM_LOCATION")?> </th> 
				    	          <th><?php echo $tr->translate("TO_LOCATION")?></th> 
				                  <th><?php echo $tr->translate("CUSTOMER_NAME")?></th>
				                  <th><?php echo $tr->translate("CUS_PHONE")?></th> 
				    	          <th><?php echo $tr->translate("CUS_EMAIL")?></th> 
				    	          <th><?php echo $tr->translate("VEHICLE_TYPE")?></th> 
				    	          <th><?php echo $tr->translate("TOTAL_PAID")?> </th> 
				    	          <th><?php echo $tr->translate("BALANCE")?> </th> 
				    	          <th><?php echo $tr->translate("TOTAL_PAYMENT")?> </th> 
				    	          <th><?php echo $tr->translate("AGENCY_NAME")?> </th> 
				    	          <th><?php echo $tr->translate("CAR_RENT_FEE")?> </th> 
				    	          <th><?php echo $tr->translate("COMMISSION_FEE")?></th> 
				    	          <th><?php echo $tr->translate("OTHER_FEE")?> </th> 
				    	          <th><?php echo $tr->translate("GRAND_TOTAL")?></th> 
				    	          <th><?php echo $tr->translate("DRIVER")?> </th> 
				    	          <th><?php echo $tr->translate("DRIVER_FEE")?></th> 
				    	          <th><?php echo $tr->translate("BOOKING_STATUS")?> </th> 
				    	           <th><?php echo $tr->translate("USER")?></th> 
				    	          <th><?php echo $tr->translate("STATUS")?></th> 
		                         </tr>
				               <?php  $status_drinver='';
				               if(!empty($this->result)) foreach($this->result as $key =>$rs){
				               	?> 
									<tr class=" alternate  normal" style="background:#fff" >
								       <td class="text-center">&nbsp;<?php echo $key+1?></td>
								       <td class="text-center">&nbsp;<?php echo $rs['booking_no']?> </td> 
								       <td class="text-center">&nbsp; <?php echo date("d-M-Y",strtotime($rs['booking_date']));?> </td> 
								       <td class="text-center">&nbsp; <?php echo date("D, d-M-Y",strtotime($rs['delivey_date']));?>  </td>
								       <td class="text-center">&nbsp;  <?php echo $rs['delivey_time']?> </td>
								       <td class="text-center">&nbsp; <?php echo $rs['payment_booking_no']?></td> 
								       <td class="text-center">&nbsp; <?php echo $rs['from_location']?></td> 
								       <td class="text-center">&nbsp;<?php echo $rs['to_location']?> </td>
								       <td class="text-center">&nbsp; <?php echo $rs['last_name']?></td>
								       <td class="text-center">&nbsp; <?php echo $rs['phone']?></td> 
								       <td class="text-center">&nbsp; <?php echo $rs['email']?></td> 
								       <td class="text-center">&nbsp;<?php echo $rs['vehicle_type']?> </td>
								       <td class="text-center">&nbsp; <?php echo ($rs['paid']==0)?"":"$&nbsp;".number_format($rs["paid"],2);?> </td>
								       <td class="text-center">&nbsp; <?php echo ($rs['balance']==0)?"":"$&nbsp;".number_format($rs["balance"],2);?></td> 
								       <td class="text-center">&nbsp;  <?php echo ($rs['grand_total_after']==0)?"":"$&nbsp;".number_format($rs["grand_total_after"],2);?></td> 
								       <td class="text-center">&nbsp;<?php echo $rs['agency_name']?> </td>
								       <td class="text-center">&nbsp;<?php echo ($rs['total']==0)?"":"$&nbsp;".number_format($rs["total"],2);?>  </td>
								       <td class="text-center">&nbsp; <?php echo ($rs['commision_fee']==0)?"":"$&nbsp;".number_format($rs["commision_fee"],2);?></td> 
								       <td class="text-center">&nbsp;<?php echo ($rs['other_fee']==0)?"":"$&nbsp;".number_format($rs["other_fee"],2);?> </td>
								       <td class="text-center">&nbsp; <?php echo ($rs['grand_total']==0)?"":"$&nbsp;".number_format($rs["grand_total"],2);?></td>
								       <td class="text-center">&nbsp; <?php echo $rs['driver']?></td>
								       <td class="text-center">&nbsp;<?php echo ($rs['driver_fee']==0)?"":"$&nbsp;".number_format($rs["driver_fee"],2);?> </td>
								       <td class="text-center" >&nbsp;  <?php echo $rs['book_status']?> </td>
								       <td class="text-center">&nbsp; <?php echo $rs['user_name']?></td>
								        <td class="text-center">&nbsp; <?php echo $rs['status']?></td>
								     </tr>
								<?php }?>
				            </table>
				            <br />
				               <table align="center" width="100%">
								   <tr style="font-size: 12px;">
								        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
								        <th></th>
								        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
								   </tr>
							</table>
				    	</td>
				    </tr>
				</table>
			</div>
		</div>
	</div>
</div>