<?php $tr=Application_Form_FrmLanguages::getCurrentlanguage();
 echo '<title>'. $tr->translate("Add City Tour Rental Price").'</title>';
 $status_view=$this->status_view;
?>
<style>
.fixed_lable{ 
	min-width: 80px; float: left;margin: 3px 5px;
}
.fixed_value{ 
	min-width: 160px;
    background: #fff;
    margin: 1px 5px;
    padding: 4px 3px;
    border: 1px solid #ccc;
    min-height: 27px;
}
</style>
<form id="vehicleprice" action="<?php echo $this->url(array('module'=>'driverguide','controller'=>'citytourprice','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				 if(dijit.byId('record_row').get('value')==''){
                    alert('Can not submit without record !');
                    return false;
                 }
				loading();
				return true;
			} else {
				return false;
			}
	</script>
	<div class="clearfix"></div>
	<div class="row">
      	<div class="col-md-12 col-xs-12 forms_padding">
          <div class="x_panel">
              <div class="x_title">
                 <h2><i class="fa  fa-plus-circle" aria-hidden="true"></i> <?php echo $tr->translate('Add City Tour Rental Price')?></h2>
                 <ul class="nav navbar-right panel_toolbox">
	                  <li>
	                   	<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
	                   </li>
	               	</ul>
               		<div class="clearfix"></div>
         	 	</div>
	       		<div class="x_content">
	       			<div class="form-group">
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Vehicle Ref')?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                    	<select name="reference_id" id="reference_id" dojoType="dijit.form.FilteringSelect" required="true"  class="fullside" onChange="getAllVehicle(1);">
								<?php if(!empty($this->vehicle))foreach ($this->vehicle as $rows){?>
									<option value="<?php echo $rows['id'];?>"><?php echo $rows['reffer'];?></option>
								<?php }?>
							</select>
	                   </div>
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Frame No")?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                    	<select name="frame_id" id="frame_id" dojoType="dijit.form.FilteringSelect" required="true"  class="fullside" onChange="getAllVehicle(2);">
								<?php if(!empty($this->vehicle))foreach ($this->vehicle as $rows){?>
									<option value="<?php echo $rows['id'];?>"><?php echo $rows['frame_no'];?></option>
								<?php }?>
							</select>
	                   </div>
	                </div>
	                <div class="title_form_blog">
		               		<h4><i class="fa  fa-car" aria-hidden="true"></i> <?php echo $tr->translate('CAR_INFO')?></h4>
		               </div>
		               <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Vehicle Ref')?>
		                   </label>
		                   <div class="col-md-2 col-sm-2 col-xs-12">
		                    	<label class="fixed_value" id='lbl_refer'></label>
		                   </div>
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Frame No")?>
		                   </label>
		                   <div class="col-md-2 col-sm-2 col-xs-12">
		                    	<label class="fixed_value" id='lbl_frame'></label>
		                   </div>
		                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Licence Plate")?>
		                   </label>
		                   <div class="col-md-2 col-sm-2 col-xs-12">
		                    	<label class="fixed_value" id='lbl_licence'></label>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Make')?>
		                   </label>
		                   <div class="col-md-2 col-sm-2 col-xs-12">
		                    	<label class="fixed_value" id='lbl_make'></label>
		                   </div>
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Model")?>
		                   </label>
		                   <div class="col-md-2 col-sm-2 col-xs-12">
		                    	<label class="fixed_value" id='lbl_model'></label>
		                   </div>
		                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Sub Model")?>
		                   </label>
		                   <div class="col-md-2 col-sm-2 col-xs-12">
		                    	<label class="fixed_value" id='lbl_submodel'></label>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Year')?>
		                   </label>
		                   <div class="col-md-2 col-sm-2 col-xs-12">
		                    	<label class="fixed_value" id='lbl_year'></label>
		                   </div>
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Seat")?>
		                   </label>
		                   <div class="col-md-2 col-sm-2 col-xs-12">
		                    	<label class="fixed_value" id='lbl_seat'></label>
		                   </div>
		                </div>
		                 <div class="title_form_blog">
		               		<h4><i class="fa fa-hand-o-right" aria-hidden="true"></i></h4>
		               </div>
		               <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Tax')?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<select name="tax" id="tax" dojoType="dijit.form.FilteringSelect" class="fullside"> 
								<?php if(!empty($this->rs_tax))foreach ($this->rs_tax as $key=> $row){?>
									<option value="<?php echo $row['id'];?>"><?php echo $row['title'];?></option>
								<?php }?>
								</select>
		                   </div>
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<select name="status" id="status" dojoType="dijit.form.FilteringSelect" required="true"  class="fullside">
								    <?php foreach ($status_view as $rs){?>
								    <option value="<?php echo $rs['key_code'];?>" label="<?php echo $rs['name_en'];?>"><?php echo $rs['name_en'];?></option>
								    <?php }?>
								</select>
		                   </div>
		                </div>
		                <div class="form-group">
		               		 <div style="clear: both;"></div>
							<input type="hidden" dojoType="dijit.form.TextBox" id="record_row" name="record_row" />
							<div  id="store_record"></div>
							<input iconClass="dijitIconClear" type="button" onClick="addPockage();" label="Add Record" dojoType="dijit.form.Button"/>
		                </div>
	       		</div>
	       	</div>
	    </div>
	    <div class="col-md-12 col-sm-12 col-xs-12 text-center">
	        <input type="reset" style="color:#000;" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" 
					iconClass="dijitIconClear" /> 
			<input type="submit" value="SAVE_CLOSE" label="<?php echo $tr->translate('SAVECLOSE');?>" style="color:#000;" id="save_close" dojoType="dijit.form.Button" name="save_close"
				iconClass="dijitEditorIcon dijitEditorIconSave" /> 
			<input type="submit" value="SAVE_NEW" label="<?php echo $tr->translate('SAVENEW');?>" id="save_new" style="color:#000;" dojoType="dijit.form.Button" name="save_new"
				iconClass="dijitEditorIcon dijitEditorIconSave"/>					
	    </div>
	</div>
</form>

<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
	dojo.require("dojo.html");
	dojo.require("dijit.form.NumberTextBox");
require(["dojo/ready"], function(ready){
	ready(function(){
		addNewRecord();
	});
});
province_option = '<?php echo $this->pro_option;?>';
function addNewRecord(){
	dojo.query("#store_record").append('');
	tmp='<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
	tmp+='<tr style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	tmp+='</table>';
	dojo.query("#store_record").append(tmp);
	thead='<th><?php echo $tr->translate('Location Package');?></th>';
	thead+='<th><?php echo $tr->translate('PRICE');?></th>';
	thead+='<th><?php echo $tr->translate('Extra Price/Hour');?></th>';
	thead+='<th><?php echo $tr->translate('Max Visite Hour');?></th>';
	thead+='<th><?php echo $tr->translate('NOTE');?></th>';
	thead+='<th><?php echo $tr->translate('DELETE');?></th>';
	fund_title=1;
	dojo.query("#head_title").append(thead);	
	dijit.byId('record_row').attr('value','');
	addPockage();
}
r=0;
function addPockage(){
	r++;
	tmp='<tr style="border:1px solid #ccc;" id="row_guide'+r+'">'
	tmp+="</tr>";
		dojo.query("#t_amountmoneytype").append(tmp);
		
	temp='<td><select style="width:230px;"  id="package_id'+r+'" name="package_id'+r+'" dojoType="dijit.form.FilteringSelect" onchange="getLocation('+r+')">'+province_option+'</select></td>';
	temp+='<td><input style="width:200px;" dojoType="dijit.form.NumberTextBox" class="fullside" required="true" name="price_'+r+'" id="price_'+r+'" value="" type="text"></td>';
	temp+='<td><input style="width:200px;" dojoType="dijit.form.NumberTextBox" class="fullside" required="true" name="extracharge_'+r+'" id="extracharge_'+r+'" value="" type="text"></td>';
	temp+='<td><input style="width:200px;" dojoType="dijit.form.NumberTextBox" class="fullside" name="max_hour_'+r+'" id="max_hour_'+r+'" value="" type="text"></td>';
	temp+='<td><input style="width:200px;" dojoType="dijit.form.TextBox" class="fullside" name="note_'+r+'" id="note_'+r+'" value="" type="text"></td>';
	temp+='<td style="width:30px !important;text-align:center;" ><img style="cursor:pointer" onclick="deleteRecord('+r+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png" ></td>';
	
	dojo.html.set(dojo.byId("row_guide"+r),temp, {
	    parseContent: true,
	});
	if(dijit.byId("record_row").get('value')!="") {
		var ids = dijit.byId("record_row").value;
		dijit.byId("record_row").attr('value',ids+','+r);
	} else { dijit.byId("record_row").attr('value',r);}
}
function deleteRecord(index){
	var ids =dijit.byId('record_row').value;
	if(ids.length=='' || ids.length==null){
		dijit.byId('record_row').attr('value','');
		dojo.query("#row_guide"+ids).remove();
	}else{
		var arrays = ids.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		dijit.byId('record_row').attr('value',strings);
		dojo.query("#row_guide"+index).remove();
	}
}
var url_getmake = '<?php echo $this->url(array('module'=>'driverguide','controller'=>'vehicleprice','action'=>'get-vehicle')); ?>';
function getAllVehicle(type){
	if(type==1){
		dijit.byId('frame_id').attr('value',dijit.byId('reference_id').get('value')) ;
	}else{
		dijit.byId('reference_id').attr('value',dijit.byId('frame_id').get('value')) ;
	}
	dojo.byId('lbl_refer').innerHTML ='';
	dojo.byId('lbl_frame').innerHTML ='';
	dojo.byId('lbl_licence').innerHTML ='';
	dojo.byId('lbl_make').innerHTML ='';
	dojo.byId('lbl_model').innerHTML ='';
	dojo.byId('lbl_submodel').innerHTML ='';
	dojo.byId('lbl_seat').innerHTML ='';
	dojo.byId('lbl_year').innerHTML ='';
	dojo.byId('lbl_seat').innerHTML ='';
	dojo.xhrPost({
				url:url_getmake,
				content:{
					'vehicle_id':dijit.byId("reference_id").get('value')
					},
				handleAs:"json",
				load: function(data) {
					dojo.byId('lbl_refer').innerHTML =data.reffer;
					dojo.byId('lbl_frame').innerHTML =data.frame_no;
					dojo.byId('lbl_licence').innerHTML =data.licence_plate;
					dojo.byId('lbl_make').innerHTML =data.make_id;
					dojo.byId('lbl_model').innerHTML =data.model_id;
					dojo.byId('lbl_submodel').innerHTML =data.sub_model;
					dojo.byId('lbl_seat').innerHTML =data.seat;
					dojo.byId('lbl_year').innerHTML =data.year;
					dojo.byId('lbl_seat').innerHTML =data.seat_amount;

				},
				error: function(err) {
					alert(err);
				}
			});
}

</script>
