<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("Location Type"));
?>	
<?php $frm =  $this->frm_search;?>
<div class="row">
	<div class="x_panel" >
		<form id="list" name="list" action="<?php echo $this->url(array('module'=>'location','controller'=>'locationtype','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
		  <div class="clearfix"></div>
		  	<div class="form-group">
			  <div class="col-md-2 col-xs-12 mg-10">
			  <?php echo $frm->getElement("title");?>
			  </div>
			  <div class="col-md-2 col-xs-12 mg-10">
			  <?php echo $frm->getElement('status_search');?>
			  </div>
			  <div class="col-md-2 col-xs-12">
			    <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</div>
		 </div>
		<?php echo $this->list;?>
		</form>
	</div>
</div>