 
<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();

?>
 
   <meta charset="utf-8" />
   <title><?php echo $tr->translate("COMPANY_NAME");?></title>
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <meta content="" name="description" />
   <meta content="" name="author" />
  
   <link href="<?php echo $this->baseUrl()?>/assets/bootstrap/css/bootstrap-fileupload.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/css/style.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/css/style-responsive.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/css/style-default.css" rel="stylesheet" id="style_color" />
   <link rel="shortcut icon" href="<?php echo $this->baseUrl()?>/images/icon.ico" type="image/x-icon"/>
 <style>
body {
     
    font-family: "Helvetica Neue",Roboto,Arial,"Droid Sans",sans-serif,'Kh Battambang','Khmer Battambang';
    font-size: 12px;
}
 
 </style>
 <?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<?php $frm =  $this->frm_search;?>
<title><?php echo $tr->translate("CARRENTAL");?></title>
<script type="text/javascript">
dojo.ready(function(){
});
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea");
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
</script>
<div class="row">
	<div class="x_panel" >
		 <div class="blog_form_title">
		 	<h4><i class="fa fa-book" aria-hidden="true"></i> <?php echo $tr->translate("Home")?></h4>
		 </div>
			<!-- 
			<div class="metro-nav metro-fix-view">
                    <div class="metro-nav-block nav-block-green long">
                        <a href="<?php echo $this->baseUrl()."/group";?>" style="text-align: center;" class="text-center" data-original-title="">
                            <span class="value">
                                <i class="fa  fa-user"></i>
                            </span>
                        </a>
                         <div class="status" align="center"><?php echo $tr->translate('CLIENT_INFO');?></div>
                    </div>
                    <div class="metro-nav-block nav-block-red double">
                        <a href="<?php echo $this->baseUrl()."/product";?>" data-original-title="">
                            <i class="fa fa-cubes" aria-hidden="true"></i>
                            <div class="info"></div>
                            <div class="status"><?php echo $tr->translate('PRODUCT');?></div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-blue double">
                        <a href="<?php echo $this->baseUrl()."/group/invoice";?>" data-original-title="">
                            <i class="fa  fa-newspaper-o" ></i>
                            <div class="info">	</div>
                            <div class="status"><?php echo $tr->translate('INVOICE');?></div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-purple double">
                        <a href="<?php echo $this->baseUrl()."/group/reciept";?>" class="text-center" data-original-title="">
                           <i class="fa fa-money" aria-hidden="true"></i>
                            <div class="status"><?php echo $tr->translate('RECIEPT');?></div>
                        </a>
                    </div>
                    
                   
                    <div class="metro-nav-block nav-block-orange double">
                        <a href="<?php echo $this->baseUrl()."/other/slide";?>" data-original-title="" class="text-center">
                            <i class="fa fa fa-file-image-o" aria-hidden="true"></i>
                            <div class="status"><?php echo $tr->translate('SLIDE_MANAGEMENT');?></div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-blue double">
                        <a href="<?php echo $this->baseUrl()."/menu-manager/category";?>" class="text-center" data-original-title="">
                          <i class="fa fa-cubes" aria-hidden="true"></i>
                            <div class="status"><?php echo $tr->translate('CATEGORY');?></div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-grey double">
                        <a href="<?php echo $this->baseUrl()."/setting/general";?>" data-original-title="">
                             <i class="fa  fa-cogs"></i>
                            <div class="info"></div>
                            <div class="status"><?php echo $tr->translate('GENERAL_SETTING');?></div>
                        </a>
                    </div>
                </div>
                -->
		</div>
		 
</div>