<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<!-- BEGIN HEAD -->
<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();

?>
<head>
   <meta charset="utf-8" />
   <title><?php echo $tr->translate("COMPANY_NAME");?></title>
   <meta content="width=device-width, initial-scale=1.0" name="viewport" />
   <meta content="" name="description" />
   <meta content="" name="author" />
   <link href="<?php echo $this->baseUrl()?>/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/assets/bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/assets/bootstrap/css/bootstrap-fileupload.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/css/style.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/css/style-responsive.css" rel="stylesheet" />
   <link href="<?php echo $this->baseUrl()?>/css/style-default.css" rel="stylesheet" id="style_color" />
   <link rel="shortcut icon" href="<?php echo $this->baseUrl()?>/images/icon.ico" type="image/x-icon"/>
<style>
.tundra .dijitBorderContainer-child{
	 overflow: hidden;
}
</style>

<style type="text/css">
.metro-nav {
    font-family: 'Kh Battambang','Khmer Battambang' !important;
}
</style>
</head>
<body class="fixed-top" style="font-family:'Kh Battambang','Khmer Battambang' !important;">
   <div id="container" class="row-fluid" style="margin: 0 auto;">
      <!-- BEGIN PAGE -->  
      <div id="main-content">
         <!-- BEGIN PAGE CONTAINER-->
         <div class="container-fluid">
            <!-- BEGIN PAGE CONTENT-->
            <div class="row-fluid">
                <!--BEGIN METRO STATES-->
                <div class="metro-nav metro-fix-view">
                    <div class="metro-nav-block nav-block-green long">
                        <a href="<?php echo $this->baseUrl()."/group";?>" style="text-align: center;" class="text-center" data-original-title="">
                            <span class="value">
                                <i class="fa  fa-user"></i>
                            </span>
                        </a>
                         <div class="status" align="center"><?php echo $tr->translate('CLIENT_INFO');?></div>
                    </div>
                    <div class="metro-nav-block nav-block-red double">
                        <a href="<?php echo $this->baseUrl()."/product";?>" data-original-title="">
                            <i class="fa fa-cubes" aria-hidden="true"></i>
                            <div class="info"></div>
                            <div class="status"><?php echo $tr->translate('PRODUCT');?></div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-blue double">
                        <a href="<?php echo $this->baseUrl()."/group/invoice";?>" data-original-title="">
                            <i class="fa  fa-newspaper-o" ></i>
                            <div class="info">	</div>
                            <div class="status"><?php echo $tr->translate('INVOICE');?></div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-purple double">
                        <a href="<?php echo $this->baseUrl()."/group/reciept";?>" class="text-center" data-original-title="">
                           <i class="fa fa-money" aria-hidden="true"></i>
                            <div class="status"><?php echo $tr->translate('RECIEPT');?></div>
                        </a>
                    </div>
                    
                   
                    <div class="metro-nav-block nav-block-orange double">
                        <a href="<?php echo $this->baseUrl()."/other/slide";?>" data-original-title="" class="text-center">
                            <i class="fa fa fa-file-image-o" aria-hidden="true"></i>
                            <div class="status"><?php echo $tr->translate('SLIDE_MANAGEMENT');?></div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-blue double">
                        <a href="<?php echo $this->baseUrl()."/menu-manager/category";?>" class="text-center" data-original-title="">
                          <i class="fa fa-cubes" aria-hidden="true"></i>
                            <div class="status"><?php echo $tr->translate('CATEGORY');?></div>
                        </a>
                    </div>
                    <div class="metro-nav-block nav-block-grey double">
                        <a href="<?php echo $this->baseUrl()."/setting/general";?>" data-original-title="">
                             <i class="fa  fa-cogs"></i>
                            <div class="info"></div>
                            <div class="status"><?php echo $tr->translate('GENERAL_SETTING');?></div>
                        </a>
                    </div>
                   
                    <div class="metro-nav-block nav-block-purple double">
                        <a href="<?php echo $this->baseUrl()."/rsvacl/useraccess";?>" data-original-title="" class="text-center">
                           <i class="fa fa-users" aria-hidden="true"></i>
                            <div class="status"><?php echo $tr->translate('USERACCESS');?></div>
                        </a>
                    </div>

                </div>

                <div class="space10"></div>
                <!--END METRO STATES-->
            </div>
            <!-- END PAGE CONTENT-->
         </div>
         <!-- END PAGE CONTAINER-->
      </div>
      <!-- END PAGE -->  
   </div>
   <!-- END CONTAINER -->

   <!-- BEGIN FOOTER -->
   <div id="footer">
      &copy;CopyRight by Cam App Technology.
   </div>
   <!-- END FOOTER -->

   <!-- BEGIN JAVASCRIPTS -->
   <!-- Load javascripts at bottom, this will reduce page load time -->
   <script src="<?php echo $this->baseUrl()?>/js/jquery-1.8.3.min.js"></script>
   <script src="<?php echo $this->baseUrl()?>/js/jquery.nicescroll.js" type="text/javascript"></script>
   <script src="<?php echo $this->baseUrl()?>/assets/bootstrap/js/bootstrap.min.js"></script>

   <!-- ie8 fixes -->
   <!--[if lt IE 9]>
   <script src="js/excanvas.js"></script>
   <script src="js/respond.js"></script>
   <![endif]-->

   <!--common script for all pages-->
   <script src="<?php echo $this->baseUrl()?>/js/common-scripts.js"></script>
   <!-- END JAVASCRIPTS -->   
</body>
<!-- END BODY -->
</html>