<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("Add Rank Day");?></title>
<script>
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.CheckBox");
</script>
<form id="add_province" action="<?php echo $this->url(array('module'=>'other','controller'=>'day','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				loading();
				return true;
			} else {
				return false;
			}
	</script>
	<div class="clearfix"></div>
	<div class="row">
	 	<div class="col-md-3 col-xs-12 forms_padding">
	 	</div>
      	 <div class="col-md-6 col-xs-12 forms_padding">
	          <div class="x_panel">
	              <div class="x_title">
	                 <h2><i class="fa  fa-plus-circle" aria-hidden="true"></i> <?php echo $tr->translate('Add Rank Day')?></h2>
	                 <ul class="nav navbar-right panel_toolbox">
	                    <li>
	                    	<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
	                    </li>
	               	</ul>
	               <div class="clearfix"></div>
	          	</div>
	       		<div class="x_content">
	       			<div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-12" for="first-name"><?php echo $tr->translate('Package Day Name')?>
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-12">
	                   		<input dojoType="dijit.form.ValidationTextBox" class="fullside" required="true" id="package_day" name="package_day" value="" type="text">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-12" for="first-name"><?php echo $tr->translate('From Amount Day')?>
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-12">
	                   		<input dojoType="dijit.form.NumberTextBox" required="true" class="fullside" id="from_amount" name="from_amount" value="" type="text">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-12" for="first-name"><?php echo $tr->translate('To Amount Day')?>
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-12">
	                   		<input dojoType="dijit.form.NumberTextBox" required="true" class="fullside" id="to_amount" name="to_amount" value="" type="text">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-12" for="first-name"><?php echo $tr->translate('Is More Than')?>
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-12">
	                   		<input onclick="CheckIsMore();" dojoType="dijit.form.CheckBox" class="fullside" id="is_morethan" name="is_morethan" value="" type="text">
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-12" for="first-name"><?php echo $tr->translate('More Than')?>
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-12">
	                   		<input dojoType="dijit.form.NumberTextBox" readonly="readonly" class="fullside" id="morethan_amount" name="morethan_amount" value="" type="text">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-12" for="first-name"><?php echo $tr->translate('STATUS')?>
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-12">
	                    	<select name="status" id="status" dojoType="dijit.form.FilteringSelect" required="true" missingMessage="Invalid Module!" class="fullside">
							    <?php foreach($this->status_view as $rs){?>
									    <option value="<?php echo $rs['key_code'];?>"  label="<?php echo $rs['name_en'];?>"><?php echo $rs['name_en'];?></option>
							    <?php }?>
							</select>
	                   </div>
	                </div>
	                <div class="clearfix"></div>
			       	<div class="ln_solid"></div>
				     <div class="col-md-12 col-sm-12 col-xs-12 text-center">
				        <input type="reset" style="color:#000;" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" 
								iconClass="dijitIconClear" /> 
						<input type="submit" value="SAVE_CLOSE" label="<?php echo $tr->translate('SAVECLOSE');?>" style="color:#000;" id="save_close" dojoType="dijit.form.Button" name="save_close"
							iconClass="dijitEditorIcon dijitEditorIconSave" /> 
						<input type="submit" value="SAVE_NEW" label="<?php echo $tr->translate('SAVENEW');?>" id="save_new" style="color:#000;" dojoType="dijit.form.Button" name="save_new"
							iconClass="dijitEditorIcon dijitEditorIconSave"/>					
				    </div>
	       		</div>
	       	</div>
	       	
	     </div>
	     <div class="col-md-3 col-xs-12 forms_padding">
	 	</div>
	 </div>
</form>
<script>
function CheckIsMore(){
	if(dijit.byId('is_morethan').checked){
		dijit.byId('from_amount').attr('value',0);
		dijit.byId('from_amount').set('readOnly',true);
		dijit.byId('to_amount').attr('value',0);
		dijit.byId('to_amount').set('readOnly',true);
		dijit.byId('morethan_amount').set('readOnly',false);
		}else{
			dijit.byId('from_amount').set('readOnly',false);
			dijit.byId('to_amount').set('readOnly',false);
			dijit.byId('morethan_amount').attr('value',0);
			dijit.byId('morethan_amount').set('readOnly',true);
		}
}
</script>