<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('OUR_PARTNER_SLIDE')); 
echo $this->headTitle();
?>
<style>
div.cke_contents.cke_reset {
    height: 200px !important;
}
</style>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.FilteringSelect');
	dojo.require("dijit.Dialog");
	require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
	dojo.require("dojo.parser");
	dojo.require("dojo.NodeList-manipulate");
</script>

<style>

img.image_view {
    width: 80px;
}

</style>
 <div class="title_left">
 	<h3><?php echo $tr->translate("OUR_PARTNER_SLIDE")?></h3>
 </div>
<form class="form-horizontal form-label-left" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				loading();
				return true;
			}
			return false;
	</script>
		<div class="clearfix"></div>
	<div class="row">
       <div class="col-md-12 col-xs-12">
          <div class="x_panel">
              <div class="x_title">
                 <h2><i class="fa fa-file-image-o" aria-hidden="true"></i> <?php echo $tr->translate('OUR_PARTNER_SLIDE')?> (150px X 110px)</h2>
                 <ul class="nav navbar-right panel_toolbox">
                    <li>
                    	<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
               	</ul>
               <div class="clearfix"></div>
          	</div>
          	<div class="x_content">
               <br />
               <div>
               	<table id="table_parent" style="margin: 0 auto; width: 100%;"   >
					<thead>
						<tr>
							<td colspan="8">
								<table  class="table table-striped jambo_table bulk_action">
									<thead>
										<tr id="head-title" class="headings" align="right"></tr>
									</thead>
								</table>
								<table id="table_row" style="margin: 0 auto; width: 100%; border-collapse: collapse; border: 1px #ccc solid;">
								</table>
							</td>
						</tr>
						<tr>
							<td align="left">
								<input type="button" label="<?php echo $tr->translate('ADD_MORE');?>" dojoType="dijit.form.Button" 
									 	iconClass="dijitIconEditProperty" onclick="addRow();" />
								<input type="hidden" name="identity" id="identity"  value="" >
							</td>
						</tr>
					</thead>
				</table>
               </div>
                <div class="clearfix"></div>
                <div class="ln_solid"></div>
                 <div class="form-group">
                     <div class="col-md-12 col-sm-12 col-xs-12 col-md-offset-4">
                          	<input type="button" value="GO_BACK" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
							iconClass="dijitIconUndo" onclick="window.history.back();" />
							<input class="button_success" type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE');?>" id="save_close" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
                     </div>
                      <div class="clearfix"></div>
                </div>
            </div>
         </div>
      </div>
    </div>	
     <div class="clearfix"></div>
</form>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'<?php echo $tr->translate("DO_YOU_WANT_TO_DEL")?>'"  id="deleteForm" style="width:350px;" >
		<div style=" text-align: center;">
			<h4><?php echo $tr->translate("DO_YOU_WANT_TO_DEL")?></h4>
			<input type="hidden" name="recorddelete" id="recorddelete" dojoType="dijit.form.TextBox" />
			<button onclick="closeForm();" dojoType="dijit.form.Button" showLabel="true" type="button"><?php echo $tr->translate("CANCEL");?></button>
			<button onclick="deleteRecord('',1);" iconclass="dijitIconDelete" dojoType="dijit.form.Button" showLabel="true" type="button"><?php echo $tr->translate("DELETE");?></button>
		</div>
	</div>
</div>
<script>
require(["dojo/ready"], function(ready){
	ready(function(){
		initailize();
	});
});
var col = 0;
var no = 0;
var title = 0;
func='';
tmp = '';
var temp='';
function addRow() {
		col++;no++;
		template='';
		if(title!=1){
			temp+='<th><?php echo $tr->translate("IMAGE");?></th>';
			temp+='<th ><?php //echo $tr->translate("VALUE");?></th>';
			temp+='<th><?php //echo $tr->translate("DEL");?></th>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			template+='<td style="text-align: center;  padding: 10px;"><img class="image_view" id="image_view'+col+'" src="<?php echo $this->baseUrl().'/images/slide/no-photo.png';?>" alt=""  /></td>';
			template+='<td><div class="button_browse"><span>Upload <span><i class="fa fa-camera" aria-hidden="true"></i></span></span><input class="btn_borwse_image" required="true" type="file" id="photo'+col+'" name="photo'+col+'" onchange="loadImage('+col+')"></div></td>';
			template+='<td width="3%" align="center" style="padding: 10px 25px;"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		tmp='<tr id="row'+col+'" style="background: #fff; border: solid 1px #bac;">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);
		if($("#identity").val()!='') {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
 }
<?php $image = explode(",", $this->slide['value']);
?>
function initailize() {
	<?php if (!empty($image)) foreach ($image as $rs){?>
	col++;no++;
	template='';
	if(title!=1){
		temp+='<th><?php echo $tr->translate("IMAGE");?></th>';
		temp+='<th >&nbsp;<?php //echo $tr->translate("VALUE");?></th>';
		temp+='<th>&nbsp;<?php //echo $tr->translate("DEL");?></th>';
		dojo.query("#head-title").append(temp);
		title=1;
	}
		template+='<td style="text-align: center;  padding: 10px;"><input type="hidden" id="old_phoyto'+col+'" name="old_photo'+col+'" value="<?php echo $rs;?>"><img class="image_view" id="image_view'+col+'" src="<?php echo $this->baseUrl().'/images/slide/partner/'.$rs;?>" alt=""  /></td>';
		template+='<td><div class="button_browse"><span>Upload <span><i class="fa fa-camera" aria-hidden="true"></i></span></span><input class="btn_borwse_image" type="file" id="photo'+col+'" name="photo'+col+'" onchange="loadImage('+col+')"></div></td>';
		template+='<td width="3%" align="center" style="padding: 10px 25px;"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
	tmp='<tr id="row'+col+'" style="background: #fff; border: solid 1px #bac;"">';
	tmp+="</tr>";
	dojo.query("#table_row").append(tmp);
	if($("#identity").val()!='') {
		var identity = $("#identity").val();
		$("#identity").val(identity+','+col);
	} else {$("#identity").val(col);}
	dojo.html.set(dojo.byId("row"+col),template , {
	     parseContent: true,
	});
	<?php }?>
}
function deleteRecord(index,type=''){
	 if(type==''){
		 dijit.byId("recorddelete").attr('value',index);
		 dijit.byId('deleteForm').show();
	 }else{
		index = dijit.byId("recorddelete").get('value');
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
		dijit.byId('deleteForm').hide();
	 }
}
 function loadImage(index){
	 var output = document.getElementById('image_view'+index);
    output.src = URL.createObjectURL(event.target.files[0]);
 }
 </script>