<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("DRIVER_GUIDE_AGREEMENT"));
?>
<div class="row">
	<div class="x_panel" >
		<div class="blog_form_title">
			<h4><i class="fa fa-file-text" aria-hidden="true"></i> <?php echo $tr->translate("DRIVER_GUIDE_AGREEMENT")?></h4>
		</div>
		<form id="list" name="list" action="<?php echo $this->url(array('module'=>'other','controller'=>'holiday','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
			<div class="clearfix"></div>
		  	<div class="form-group">
			  <div class="col-md-2 col-xs-12">
			  		<?php //echo $frm->getElement("adv_search");?>
			  </div>
			   <div class="col-md-2 col-xs-12">
			   		<?php //echo $frm->getElement("start_date");?>
			  </div>
			   <div class="col-md-2 col-xs-12">
			   		<?php //echo $frm->getElement("end_date");?>
			  </div>
			   <div class="col-md-2 col-xs-12">
			   		<?php // $frm->getElement('search_status');?>
			  </div>
			   <div class="col-md-2 col-xs-12">
			   		<!-- <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php //echo $tr->translate("SEARCH");?></button> --> 
			  </div>
			</div>
		</form>
		<?php echo $this->list;?>
	</div>
</div>
