  <?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();
  // report
  $rpt_sale_agreement=$this->url(array('module'=>'report','controller'=>'carsale','action'=>'rpt-sale-agreement'), null, true);
  
  $rpt_sale_invoice=$this->url(array('module'=>'report','controller'=>'carsale','action'=>'rpt-sale-invoice'), null, true);
  $rpt_sale_reciept=$this->url(array('module'=>'report','controller'=>'carsale','action'=>'rpt-sale-reciept'), null, true);
  
  
  ?>
  <style>
  ul.link-rpt li a {
	color: #FFFFFF;
    height: 50px;
    width: 180px;
    display: block;
    padding: 10px;
    background: #9206A2;
    font-family: calibri,Arial, Helvetica, sans-serif;
    text-align: center;
    word-wrap: break-word;
  	font-weight: bold;
  } 
    ul.link-rpt li {
	float:left; margin:10px;
    list-style: none;
    border:1px solid #B1B0AF;
    word-wrap: break-word;
    
  } 
  .dijitReset, .dijitInline  ,.dijitButton {
	width: 200px !important;
  }
  </style>
  <div style="background:#ccc; width: 100%;">
  	<ul class="link-rpt">
  		<li><a href="<?php echo $rpt_sale_agreement;?>"><?php echo $tr->translate('Sale Agreement');?></a></li>
  		<li><a href="<?php echo $rpt_sale_invoice;?>"><?php echo $tr->translate('Sale Invoice');?></a></li>
  		<li><a href="<?php echo $rpt_sale_reciept;?>"><?php echo $tr->translate('Sale Reciept');?></a></li>
  	</ul>
  </div>
  <div style="clear: both;"></div>