<?php 
     $url_save = $this->url(array('module'=>'vehicle','controller'=>'vehicletype','action'=>'edit'));
     $status_view=$this->status_view;
     $row=$this->row;
?>
<?php $tr=Application_Form_FrmLanguages::getCurrentlanguage();
echo '<title>'. $tr->translate("Edit Vehicle Type").'</title>';
?> 
<form id="add_province" action="<?php echo $url_save;?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
	</script>
	<div class="clearfix"></div>
	<div class="row">
	 	<div class="col-md-3 col-xs-12 forms_padding">
	 	</div>
      	 <div class="col-md-6 col-xs-12 forms_padding">
	          <div class="x_panel">
	              <div class="x_title">
	                 <h2><i class="fa  fa-edit" aria-hidden="true"></i> <?php echo $tr->translate('Edit Vehicle Type')?></h2>
	                 <ul class="nav navbar-right panel_toolbox">
	                    <li>
	                    	<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
	                    </li>
	               	</ul>
	               <div class="clearfix"></div>
	          	</div>
	       		<div class="x_content">
	       			<div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-12" for="first-name"><?php echo $tr->translate('VEHICLETYPE')?>
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-12">
	                    	<input type="hidden" name="id" value="<?php echo $row['id'];?>">
							<input dojoType="dijit.form.ValidationTextBox" class="fullside" id="vehicle_type" name="vehicle_type" value="<?php echo $row['title'];?>" type="text" required="required">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-12" for="first-name"><?php echo $tr->translate('STATUS')?>
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-12">
	                    	<select name="status" id="status" dojoType="dijit.form.FilteringSelect" required="true" missingMessage="Invalid Module!" class="fullside">
							    <?php foreach($status_view as $rs){?>
									    <option value="<?php echo $rs['key_code'];?>" <?php if ($rs['key_code']==$row['id']){ echo 'selected="Selected"';}?>  label="<?php echo $rs['name_en'];?>"><?php echo $rs['name_en'];?></option>
							    <?php }?>
							</select>
	                   </div>
	                </div>
	                <div class="clearfix"></div>
			       	<div class="ln_solid"></div>
				     <div class="col-md-12 col-sm-12 col-xs-12 text-center">
				        <input type="reset" style="color:#000;" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" 
								iconClass="dijitIconClear" /> 
						<input type="submit" value="SAVE_CLOSE" label="<?php echo $tr->translate('SAVECLOSE');?>" style="color:#000;" id="save_close" dojoType="dijit.form.Button" name="save_close"
							iconClass="dijitEditorIcon dijitEditorIconSave" /> 
				    </div>
	       		</div>
	       	</div>
	       	
	     </div>
	     <div class="col-md-3 col-xs-12 forms_padding">
	 	</div>
	 </div>
</form> 

<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-type="dijit.Dialog" id="pop_vehicle_type" title="<?php echo $tr->translate("Add Vehicle Type")?>">
		<form id='frm_vehicle_type' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
		<table class="height" >
			<tr>
				<td><?php echo $tr->translate("TITLE")?></td>
				<td><input dojoType="dijit.form.ValidationTextBox" required="true" id="vehicletype_title" name="vehicletype_title" value="" type="text"></td>
			</tr>
			<tr>
				<td colspan="2" align="center">
				  	<input type="button"  label="<?php echo $tr->translate("SAVE")?>" dojoType="dijit.form.Button" id="car_save"
				 	iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addvehicleType();"/>
				</td>
			</tr>
		</table>
		</form>
	</div>
</div>