<?php $tr=Application_Form_FrmLanguages::getCurrentlanguage();
echo '<title>'. $tr->translate("VEHICLETYPE").'</title>';
$frm = $this->frm_search;
?> 
<div class="row">
	<div class="x_panel" >
		<div class="blog_form_title">
		 	<h4><i class="fa fa-crosshairs" aria-hidden="true"></i> <?php echo $tr->translate("VEHICLETYPE")?></h4>
		 </div>
		<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
			  <div class="clearfix"></div>
			  	<div class="form-group">
				  <div class="col-md-2 col-xs-12 mg-10">
				  <?php echo $frm->getElement("adv_search");?>
				  </div>
				  <div class="col-md-2 col-xs-12 mg-10">
				  <?php echo $frm->getElement('status');?>
				  </div>
				  <div class="col-md-2 col-xs-12">
				    <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				</div>
			 </div>
		</form>
		<?php echo $this->list;?>
	</div>
</div>