
<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$session_user=new Zend_Session_Namespace('authcar');
	
?>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.FilteringSelect');
</script>
<title><?php echo $tr->translate('Change Password')?></title>
 <div class="title_left">
 	<h3><i class="fa fa-user" aria-hidden="true"></i> <?php echo $tr->translate("USER");?></h3>
 </div>
<form class="form-horizontal form-label-left" action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
					if(dojo.byId('password').value != dojo.byId('con_password').value ){
					alert('សូម​ពិនិត្រ ពាក្យ​​សំងាត់​ទាំង​ 2 របស់​អ្នក មិន​ដូច​គ្នា​ទេ, សូម​បញ្ចូល ​ម្តង​ទៀត..');
					dojo.byId('password').value = '';
					dojo.byId('con_password').value = '';
					dijit.byId('password').focus();
					return false;
				}				
				return true;
			}
			return false;
	</script>
	<div class="clearfix"></div>
	<div class="row">
		<div class="col-md-2 col-xs-12"></div>
       <div class="col-md-8 col-xs-12">
          <div class="x_panel">
              <div class="x_title">
                 <h2><i class="fa fa-key" aria-hidden="true"></i> <?php echo $tr->translate('Change Password')?></h2>
                <?php if (!empty($this->msg)){?> <p style="clear: both;  color: #f00;"><?php echo $this->msg; ?></p><?php }?>
                 <ul class="nav navbar-right panel_toolbox">
                    <li>
                    	<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
               	</ul>
               <div class="clearfix"></div>
          	</div>
          	<div class="x_content">
               <br />
                <div class="form-group">
                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('OLD_PASSWORD')?><span class="required">*</span>
                   </label>
                   <div class="col-md-8 col-sm-8 col-xs-8">
                      <input type="password" required="required" name="current_password" id="current_password" placeholder="<?php echo $tr->translate('PASSWORD')?>" 
											regExp="\w{6,}" invalidMessage="ពាក្យ​​សម្ងាត់យ៉ាង​តិច មាន 6​ តួអក្សរ"
											dojoType="dijit.form.ValidationTextBox" missingMessage="អ្នក​ភ្លេច​បំពេញ​ ពាក្យ​​សម្ងាត់!" class='fullside'/>
                   </div>
                </div>
                <div class="form-group">
                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('PASSWORD')?><span class="required">*</span>
                   </label>
                   <div class="col-md-8 col-sm-8 col-xs-8">
                     <input type="password" required="required" name="password" id="password" placeholder="<?php echo $tr->translate('PASSWORD')?>" 
											regExp="\w{6,}" invalidMessage="ពាក្យ​​សម្ងាត់យ៉ាង​តិច មាន 6​ តួអក្សរ"
											dojoType="dijit.form.ValidationTextBox" missingMessage="អ្នក​ភ្លេច​បំពេញ​ ពាក្យ​​សម្ងាត់!" class='fullside'/>
                   </div>
                </div>
                 <div class="form-group">
                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('CONFIRM_PASSWORD')?><span class="required">*</span>
                   </label>
                   <div class="col-md-8 col-sm-8 col-xs-8">
                    <input type="password" required="required" name="confirm_password" id="confirm_password" placeholder="បញ្ជាក់ពាក្យ​​សម្ងាត់" 
											regExp="\w{6,}" invalidMessage="ពាក្យ​​សម្ងាត់យ៉ាង​តិច មាន 6​ តួអក្សរ"
											dojoType="dijit.form.ValidationTextBox"  missingMessage="អ្នក​ភ្លេច​បំពេញ​ បញ្ជាក់ ពាក្យ​​សម្ងាត់!" class='fullside'/>
                   </div>
                </div>
                <div class="clearfix"></div>
                <div class="ln_solid"></div>
                 <div class="form-group">
                     <div class="col-md-12 col-sm-12 col-xs-12 col-md-offset-4">
                          	<input type="button" value="GO_BACK" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
						iconClass="dijitIconUndo" onclick="window.location = '<?php echo $this->url(array('module'=>'rsvacl','controller'=>"user",'action'=>'index'),null,true); ?>';" />
						<input type="submit" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE');?>" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
                     </div>
                </div>
          	</div>
          </div>
        </div>
        <div class="col-md-2 col-xs-12"></div>
   	</div>
</form>