<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('EDIT_USER'));
echo $this->headTitle();
?>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');
	dojo.require('dijit.form.FilteringSelect');	
	dojo.require('dijit.form.Button');
	dojo.require("dijit.form.CheckBox");
</script>
 <div class="title_left">
 	<h3><i class="fa fa-user" aria-hidden="true"></i> <?php echo $tr->translate("USER")?></h3>
 </div>
<form class="form-horizontal form-label-left" action="<?php echo $this->url(array('module'=>'rsvacl','controller'=>'user','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">										
			if(this.validate()) {
				if(dojo.byId('password').value != dojo.byId('con_password').value ){
					alert('សូម​ពិនិត្រ ពាក្យ​​សំងាត់​ទាំង​ 2 របស់​អ្នក មិន​ដូច​គ្នា​ទេ, សូម​បញ្ចូល ​ម្តង​ទៀត..');
					dojo.byId('password').value = '';
					dojo.byId('con_password').value = '';
					dijit.byId('password').focus();
					return false;
				}	
				loading();			
				return true;
			}

			return false;
	</script>
	<div class="clearfix"></div>
	<div class="row">
		<div class="col-md-2 col-xs-12"></div>
	    <div class="col-md-8 col-xs-12">
	        <div class="x_panel">
	              <div class="x_title">
	                 <h2><i class="fa fa-edit aria-hidden="true"></i> <?php echo $tr->translate('EDIT_USER')?></h2>
	                 <ul class="nav navbar-right panel_toolbox">
	                    <li>
	                    	<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
	                    </li>
	               	</ul>
	               <div class="clearfix"></div>
	          	</div>
	          	<div class="x_content">
	               <br />
	               <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('FULL_NAME')?><span class="required">*</span>
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                    	<input type="text" required="true" name="first_name" id="first_name" placeholder="នាមខ្លួន" value="<?php echo $this->user_edit['first_name'];?>"
							dojoType="dijit.form.ValidationTextBox" missingMessage="អ្នក​ភ្លេច​បំពេញ​ នាមខ្លួន!" class='fullside' />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('USER_NAME')?><span class="required">*</span>
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-8">
	                      <input type="text" required="true" name="user_name" id="user_name" placeholder="ឈ្នោះ​អ្នក​ប្រើ​ប្រាស់"  value="<?php echo $this->user_edit['user_name'];?>" 
												dojoType="dijit.form.ValidationTextBox" missingMessage="អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ​អ្នក​ប្រើ​ប្រាស់!" class='fullside'/>
	                   </div>
	                </div>
	                <div class="form-group">
                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('PASSWORD')?> <input dojoType='dijit.form.CheckBox' id="check_change" name="check_change" onChange="Checkchange();" />
                   </label>
                   <div class="col-md-8 col-sm-8 col-xs-8">
                     <input type="password" required="true" name="password" id="password" placeholder="ពាក្យ​​សំងាត់" 
											regExp="\w{6,}" invalidMessage="ពាក្យ​សំងាត់យ៉ាង​តិច មាន 6​ តួអក្សរ"
											dojoType="dijit.form.ValidationTextBox" missingMessage="អ្នក​ភ្លេច​បំពេញ​ ពាក្យ​​សំងាត់!" class='fullside'/>
                   </div>
                </div>
                 <div class="form-group">
                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('CONFIRM_PASSWORD')?><span class="required">*</span>
                   </label>
                   <div class="col-md-8 col-sm-8 col-xs-8">
                    <input type="password" required="true" name="con_password" id="con_password" placeholder="បញ្ជាក់ពាក្យ​​សំងាត់" 
											regExp="\w{6,}" invalidMessage="ពាក្យ​សំងាត់យ៉ាង​តិច មាន 6​ តួអក្សរ"
											dojoType="dijit.form.ValidationTextBox"  missingMessage="អ្នក​ភ្លេច​បំពេញ​ បញ្ជាក់ ពាក្យ​​សំងាត់!" class='fullside'/>
                   </div>
                </div>
                 <div class="form-group">
                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('USER_TYPE')?><span class="required">*</span>
                   </label>
                   <div class="col-md-8 col-sm-8 col-xs-8">
                   <select onchange="disabledAgent(this.value);" name="user_type" class='fullside' required="true" id="user_type" 
						 missingMessage="អ្នក​ភ្លេច​បំពេញ​  តំណែង!" dojoType="dijit.form.FilteringSelect"> 
							<?php foreach ($this->user_typelist as $key => $ust) : ?>
								<option value="<?php echo $key;?>"  <?php if($this->user_edit['user_type'] == $key) echo 'selected';?> ><?php echo $ust;?></option>
							<?php endforeach;?>																				
						</select> 
                   </div>
                </div>
                <div class="form-group">
                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('STATUS')?><span class="required">*</span>
                   </label>
                   <div class="col-md-8 col-sm-8 col-xs-8">
                   		<select name="active" required="true" id="active" class='fullside' dojoType="dijit.form.FilteringSelect"  missingMessage="អ្នក​ភ្លេច​បំពេញ​  ស្ថាន​ភាព!"> 
							<option value="1" <?php if($this->user_edit['active'] == 1) echo 'selected';?> >ប្រើ​ប្រាស់</option>
							<option value="0" <?php if($this->user_edit['active'] == 0) echo 'selected';?> >មិនប្រើ​ប្រាស់</option>																					
						</select> 
                   </div>
                </div>
                <div class="clearfix"></div>
                <div class="ln_solid"></div>
                 <div class="form-group">
                        <div class="col-md-12 col-sm-12 col-xs-12 col-md-offset-4">
                          	<input type="button" value="GO_BACK" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
							iconClass="dijitIconUndo" onclick="window.location = '<?php echo $this->url(array('module'=>'rsvacl','controller'=>"user",'action'=>'index'),null,true); ?>';" />
							<input type="submit" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE');?>" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
                        </div>
                      </div>
	            </div>
	       	</div>
	     </div>
	</div>
	<input type="hidden" name="id" value="<?php echo $this->user_edit['id'];?>" />
</form>
<script>
dojo.ready(function(){
	try{
		Checkchange();
	}catch(e){
		alert(e);
	}
	$(window).keydown(function(event){
		if(event.keyCode == 13) {
		  event.preventDefault();
		  return false;
		}
	  });
});
function Checkchange(){
	  if (dojo.byId("check_change").checked){
		  dijit.byId('password').set('required',true); 
		  dijit.byId('password').set('readonly',false); 
		  dijit.byId('con_password').set('required',true); 
		  dijit.byId('con_password').set('readonly',false); 
		 
	  }else{
		  $('#password').val('');
		  dijit.byId('password').set('required',false); 
		  dijit.byId('password').set('readonly',true); 
		  dijit.byId('con_password').set('required',false); 
		  dijit.byId('con_password').set('readonly',true); 
	  }
}
</script>