<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('EDIT_CATEGORY')); 
echo $this->headTitle();
$frm = $this->frm;
$db = new MenuManager_Model_DbTable_DbCategory();
$countlang = count($this->lang);
?>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.FilteringSelect');
	dojo.require("dijit.Dialog");
	require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
</script>
<style>
.choose_file{
    position: relative;
    display: inline-block;
    border-radius: 8px;
    border: #b1badf solid 1px;
    width: 100%;
    padding: 4px 6px 4px 8px;
    font: normal 14px Myriad Pro, Verdana, Geneva, sans-serif;
    color: #7f7f7f;
    margin-top: 2px;
    background: #edf7f8;
}
.choose_file input[type="text"]{
    -webkit-appearance:none; 
    position:absolute;cursor: pointer;
    top:0; right:0;    width: 100%;
    opacity:0; 
}
</style>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
<script src="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.js"></script>
<link href="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.css" rel="stylesheet">
<form action="<?php echo $this->url(array('module'=>'menu-manager','controller'=>'category','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
    			if(alias_require==0){ alert("Please check your title alias again.");return false;}
				loading();					
				return true;
			}

			return false;
	</script>
	<div class="clearfix"></div>
	<div class="row">
      <div class="col-md-8 col-sm-8 col-xs-12">
          <div class="x_panel">
             <div class="x_title">
                <h2><i class="fa fa-bars"></i> <?php echo $tr->translate('EDIT_CATEGORY')?></h2>
                <ul class="nav navbar-right panel_toolbox">
                   <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                </ul>
                <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                  	<?php if ($countlang>1){?>
                    <div class="" role="tabpanel" data-example-id="togglable-tabs">
                      <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                      <?php $alias=''; foreach($this->lang as $key=> $rs){
                      	$alias = str_replace(' ','',$rs['title']);?>
                        <li role="presentation" class="<?php if ($key<1){echo "active";}?>"><a href="<?php echo "#".$alias;?>" id="<?php echo "#".$alias."-tab";?>" role="tab" data-toggle="tab" aria-expanded="true"><?php echo $tr->translate(strtoupper($rs['title']));?></a>
                        </li>
                     <?php }?>
                      </ul>
                      <div id="myTabContent" class="tab-content">
                      <?php $alias=''; foreach($this->lang as $key=> $rs){ 
                      	$alias = str_replace(' ','',$rs['title']); $lang = $db->getCategoryTitleByLang($this->id, $rs['id']);?>
                        <div role="tabpanel" class="tab-pane fade <?php if ($key<1){echo "active in";}?>" id="<?php echo $alias;?>" aria-labelledby="<?php echo $alias."-tab";?>">
                          <div class="form-group">
			                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate(strtoupper($rs['title']));?><span class="required">*</span>
			                   </label>
			                   <div class="col-md-8 col-sm-8 col-xs-8">
			                	   <input   type="text" onChange="generateAlias('<?php echo $alias;?>');" dojoType="dijit.form.TextBox" required="required" name="title<?php echo str_replace(' ','',$rs['title']);?>"  id="title<?php echo str_replace(' ','',$rs['title']);?>" value="<?php echo $lang['title'];?>" class="fullside" placeholder="<?php echo $tr->translate("TITLE_IN_".strtoupper($rs['title']));?>" />
			                   		<input type="hidden" dojoType="dijit.form.TextBox" name="iddetail<?php echo str_replace(' ','',$rs['title']);?>"  id="iddetail<?php echo str_replace(' ','',$rs['title']);?>" value="<?php echo $lang['id'];?>" class="fullside" />
			                   </div>
			                </div>
                        </div>
                     <?php }?>
                      </div>
                    </div>
                    <?php }else{?>
                     <?php $alias=''; foreach($this->lang as $key=> $rs){
                      	$alias = str_replace(' ','',$rs['title']); $lang = $db->getCategoryTitleByLang($this->id, $rs['id']);?>
                        <div role="tabpanel" class="tab-pane fade <?php if ($key<1){echo "active in";}?>" id="<?php echo $alias;?>" aria-labelledby="<?php echo $alias."-tab";?>">
                          <div class="form-group">
			                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate(strtoupper($rs['title']));?><span class="required">*</span>
			                   </label>
			                   <div class="col-md-8 col-sm-8 col-xs-8">
			                	   <input   type="text" onChange="generateAlias('<?php echo $alias;?>');" dojoType="dijit.form.TextBox" required="required" name="title<?php echo str_replace(' ','',$rs['title']);?>"  id="title<?php echo str_replace(' ','',$rs['title']);?>" value="<?php echo $lang['title'];?>" class="fullside" placeholder="<?php echo $tr->translate("TITLE_IN_".strtoupper($rs['title']));?>" />
			                  	<input type="hidden" dojoType="dijit.form.TextBox" name="iddetail<?php echo str_replace(' ','',$rs['title']);?>"  id="iddetail<?php echo str_replace(' ','',$rs['title']);?>" value="<?php echo $lang['id'];?>" class="fullside" />
			                   </div>
			                </div>
                        </div>
                     <?php }?>
                    <?php }?>
                    <div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12" for="first-name"><?php echo $tr->translate('DESCRIPTION');?><span class="required">*</span>
	                   </label>
	                   <div class="col-md-12 col-sm-12 col-xs-12">
	                	   <textarea class="ckeditor"   height="400px" style="min-height:60px;" id="description" name="description"></textarea>
	                   </div>
	                </div>
                  </div>
                </div>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <ul class="nav navbar-right panel_toolbox">
                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                      </li>
                    </ul>
                    <div class="clearfix"></div>
                    <div class="x_content">
                    	<br />
	                    <div class="form-group">
		                   <div class="col-md-12 col-sm-12 col-xs-12">
		                 	  <label id="message" style="color: red;"></label>
							  <?php echo $frm->getElement('title_alias');?>
		                   </div>
		                </div>
		                 <div class="form-group">
		                	<label class="control-label col-md-12 col-sm-12 col-xs-12"><?php echo $tr->translate('CHOOSE_PARENT')?>*</label>
		                   <div class="col-md-12 col-sm-12 col-xs-12">
							  <?php echo $frm->getElement('parent');?>
		                   </div>
		                </div>
		                <div class="form-group">
		                	<label class="control-label col-md-12 col-sm-12 col-xs-12"><?php echo $tr->translate('STATUS')?>*</label>
		                   <div class="col-md-12 col-sm-12 col-xs-12">
							  <?php echo $frm->getElement('status');?>
		                   </div>
		                </div>
                    </div>
                  </div>
                 </div>
             </div>
             <div class="clearfix"></div>
	        	<div class="col-md-12 col-sm-12 col-xs-12 " style="  text-align: center;">
	        		<input type="button" value="GO_BACK" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
									iconClass="dijitIconUndo" onclick="window.history.back();" />
					<input class="button_success" type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" id="save_close" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 	
        	  </div>
	          <div class="clearfix"></div>
           </div>	
</form>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'Directory'"  id="directory" style="width:850px; height:250px; overflow-y: auto;" >
		<div id="block_all_image" style=" text-align: center;">
			<?php
			$dir=opendir(PUBLIC_PATH.DIRECTORY_SEPARATOR."images".DIRECTORY_SEPARATOR."directory");
				while(@$entitys=readdir($dir))
				{
					$arraydir[]=$entitys;
				}
				closedir($dir);
				$contarray=count($arraydir);
				for($all=0;$all<$contarray;$all++){
				if($arraydir[$all] !=='..' and $arraydir[$all]!=="." ){
				$type=@filetype($arraydir[$all]);
				$file_parts = pathinfo($arraydir[$all]);
					if(empty($file_parts['extension']))
					{?>
					<div onClick="loadImageFromDirectory('<?php echo $arraydir[$all];?>');" class='blockimagelink'style="cursor: pointer; display: inline-block;border: solid 1px #ccc;text-align: center;padding: 10px;width: 100px;">
						<img style=" width: 55px; height: 52px;" src='<?php echo $this->baseUrl()."/images/folder.png";?>' width='30px' />
						<p><?php echo $arraydir[$all];?></p>
					</div>
				<?php }
					else{
				?>
					<div onClick="getImageLink('<?php echo $arraydir[$all];?>');" class='blockimagelink'style="cursor: pointer; display: inline-block;border: solid 1px #ccc;text-align: center;padding: 10px;width: 100px;">
							<img style=" height: 50px;border:1px solid #ccc;" title="<?php echo $arraydir[$all];?>" src="<?php echo $this->baseUrl()."/images/directory/".$arraydir[$all];?>" />
							<p><?php echo substr($arraydir[$all],0,15);?></p>
					</div>	
				<?php	}    
		          }
		        }
			?>
		</div>
	</div>
</div>
<script>
var alias_require=1;
	var mainDir = '<?php echo PUBLIC_PATH.DIRECTORY_SEPARATOR."images".DIRECTORY_SEPARATOR."directory";?>';
	function getImageLink(image){
		alert(image);
		 //if(menutype==4){
			 //$("#controlbytype").css("display", "block");
		// }
	}
	var	url_load_image = '<?php echo $this->url(array('module'=>'menu-manager','controller'=>'category','action'=>'loadimg'));?>';
	function loadImageFromDirectory(dir){
		if(dir==""){
			return false;
		}
		dojo.xhrPost({
			url:url_load_image,	
			content:{ 
				'mainDir':mainDir,'dir': dir
			},
			handleAs:"json",
			load: function(data) {	
				alert(data.image);
				//sale_client_store  = getDataStorefromJSON('id','name', data);		
			    //dijit.byId('sale_client').set('store', sale_client_store);
			},
			error: function(err) {
				alert(err);
			}
		});
	}
	var old_alias="<?php echo $this->row['alias_category'];?>";
	var specialcharalias = [" ",",",".","?",";","/","{","}","|","[","]","~","!","@","#","$","%","^","&","*","(",")","+","=","`","<",">"];
	function generateAlias(alias){
		title = dijit.byId('title'+alias).get('value');
		var title_alias = title.split(' ').join('-');
		//title_alias = ((title_alias.split('?').join('-')).split('"').join('-')).split('&').join('');
		for(var i=0; i<specialcharalias.length;i++){
			title_alias = title_alias.split(specialcharalias[i]).join('');
		}
		dijit.byId("title_alias").attr('value',title_alias.toLowerCase());
		checkTitle();
	}
	url_CheckTitle = '<?php echo $this->url(array('module'=>'menu-manager','controller'=>'category','action'=>'check-title-alias'));?>';
	function checkTitle(){
		title_alias = dijit.byId('title_alias').get('value');
		if(title_alias.toLowerCase()==old_alias.toLowerCase()){
			document.getElementById('message').innerHTML ='';
			alias_require=1;
			return false;
		}
		dojo.xhrPost({
			url:url_CheckTitle,	
			content:{ 
				'title_alias': title_alias
			},
			handleAs:"json",
			load: function(data) {	
				if(data !== false ){
			   		document.getElementById('message').innerHTML ='Alias is duplicated you can set new alias or clear alias will auto generate.';
			   		dijit.byId('title_alias').focus();
			   		alias_require=0;
				}else{
					alias_require=1;
					document.getElementById('message').innerHTML ='';
				}
			},
			error: function(err) {
				alert(err);
			}
		});
	}
	function checkSpcialCharFortitle(event){
        if(((event.keyCode > 64 && event.keyCode < 91) || event.keyCode == 37 || event.keyCode == 39 || event.keyCode == 34 || event.keyCode == 32 || event.keyCode == 63 || event.keyCode == 45 || (event.keyCode > 96 && event.keyCode < 123) || event.keyCode == 8 || (event.keyCode >= 48 && event.keyCode <= 57))){
            event.returnValue = true;
            return;
         }
         event.returnValue = false;
      }
	 function checkSpcialChar(event){
         if(((event.keyCode > 64 && event.keyCode < 91) || event.keyCode == 45 || (event.keyCode > 96 && event.keyCode < 123) || event.keyCode == 8 || (event.keyCode >= 48 && event.keyCode <= 57))){
             event.returnValue = true;
             return;
          }
          event.returnValue = false;
       }
</script>
