<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("CATEGORY"));
$frm = $this->frm;
$frms = $this->frm_search;
$url_delete =$this->url(array('module'=>'menu-manager','controller'=>'category','action'=>'delete'));
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
 <div class="title_left">
 	<h3><?php echo $tr->translate("CATEGORY")?></h3>
 </div>
 <form id="list" name="list" action="<?php echo $this->url(array('module'=>'menu-manager','controller'=>'category','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <div class="clearfix"></div>
	<div class="form-group">
		<div class="col-md-2 col-xs-12 mg-10">
			<?php echo $frms->getElement("adv_search");?>
		</div>
		<div class="col-md-2 col-xs-12 mg-10">
			<?php echo $frm->getElement('status_search');?>
		</div>
		<div class="col-md-2 col-xs-12 mg-10">
			<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
		</div>
	</div>
</form>
<?php 

$imgnone='<img src="'.$this->baseUrl().'/images/icon/cross.png"/>';
$imgtick='<img src="'.$this->baseUrl().'/images/icon/apply2.png"/>';
?>
	<div class="x_panel">
	    	<div class="x_content">
	    		<table id="datatable-responsive" class="table table-striped table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
					<thead>
						<tr>
						<th class="tdheader"><?php echo $tr->translate("NUM")?></th>
						<th class="tdheader" style=" width: 50%;"><?php echo $tr->translate("TITLE")?></th>
						<th class="tdheader"><?php echo $tr->translate("TYPE")?></th>
						<th class="tdheader"><?php echo $tr->translate("STATUS")?></th>
						<th class="tdheader"><?php echo $tr->translate("")?></th>
					  	</tr>
					  </thead>
					  <tbody>
					  <?php $r=0;
					   if (!empty($this->row)){ foreach($this->row as $row){ $r++;
					  	if($r%2==0)$attb='normal';
					  	else $attb='alternate';
					  	$db = new MenuManager_Model_DbTable_DbCategory();
						 $rs = 	$db->getCategoryById($row['id']);
						 if ($rs['cate_type']==1){
						 	$type= $tr->translate("FOR_PRODUCT");
						 }else{
						 	$type= $tr->translate("FOR_MENU_MANAGER");
						 }
					  	?>
					  	<tr class="<?php echo $attb; ?>">
					  		<td class="items-no"><?php echo $r;?></td>
					  		<td class="items"><a href="<?php echo $this->url(array('controller'=>'category','action'=>'edit','id'=>$row['id']));?>"><?php echo $row['name'];?></a></td>
					  		<td class="items"><?php echo $type;?></td>
					  		<td class="items"><?php if($rs['status']==1){echo  $imgtick;} else{echo $imgnone;};?></td>
					  		<td align="center">
						  		<a class="btn btn-app small" onclick="showDeleteForm(<?php echo $row['id'];?>)">
			                      <i class="fa fa-trash"></i>
			                    </a>
					  		</td>
					  	</tr>
					  	<?php }
					  	?>
					  	
					  </tbody>
			  </table>
			</div>
		</div>
	<?php }else{?>
			</table>
		</div>
	</div>
	<center style="font-size:18pt;"><label id="data_table">No record</label></center>
	<?php }?>
<?php //echo $this->list;?>
<script type="text/javascript">
dojo.require("dijit.form.CheckBox"); 
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.Dialog");
	var recordid ='';
	function  resetForm(){
		var datenow = '<?php echo date("Y-m-d");?>';
		dijit.byId('adv_search').attr('value','');
		dijit.byId('status_search').set('value','-1');
	}
	function deleteRecord(url){
		 id = recordid;
		 window.location.href = url+'/id/'+id;
	}
	function showDeleteForm(id){
		//id = dijit.byId('recorddelete').get('value');
		if(id==''){
			alert("No record selected for delete.");
			dijit.byId('deleteForm').hide();
		}else{
			dijit.byId('deleteForm').show();
			recordid = id;
		}
	}
	function closeForm(){
		dijit.byId('deleteForm').hide();
	}
</script> 
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'តើអ្នកពិតជាលុបទិន្នន័យនេះមែនទេ?'"  id="deleteForm" style="width:350px;" >
		<div style=" text-align: center;">
			<h4>តើអ្នកពិតជាលុបទិន្នន័យនេះមែនទេ?</h4>
			<button onclick="deleteRecord('<?php echo $url_delete;?>')" iconclass="dijitIconDelete" dojoType="dijit.form.Button" showLabel="true" type="button"><?php echo $tr->translate("DELETE");?></button>
			<button onclick="closeForm();" dojoType="dijit.form.Button" showLabel="true" type="button"><?php echo $tr->translate("CANCEL");?></button>
		</div>
	</div>
</div>