<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('GENERAL_SETTING')); 
echo $this->headTitle();
$frm = $this->frm_general;
$countlang = count($this->lang);

if(!empty($this->logo['value'])){
	$profile="lang/".$this->logo['value'];
}else{
	$profile ="no-image.png";
}
$header="";
if(!empty($this->headerbg['value'])){
	$header="headerbackground/".$this->headerbg['value'];
}else{
	$header ="no-image.png";
	
}
?>
<style>
div.cke_contents.cke_reset {
    height: 200px !important;
}
</style>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require("dijit.form.NumberTextBox");
	dojo.require('dijit.form.Form');	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.FilteringSelect');
	dojo.require("dijit.Dialog");
	require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
	dojo.require("dojo.parser");
	dojo.require("dojo.NodeList-manipulate");
</script>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>

<style>

img.image_view {
    width: 100%;
	height: 100px;
}
img#image_viewbg {
    height: 50px;
}
.button_browse{
	margin-top:0 !important;
}
.button_browse span {
    padding: 0 5px;
}
</style>
 <div class="title_left">
 	<h3><?php echo $tr->translate("GENERAL_SETTING")?></h3>
 </div>
<form action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data" class="form-horizontal form-label-left">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				loading();
				return true;
			}

			return false;
	</script>
	<div class="clearfix"></div>
	<div class="row">
       <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
              <div class="x_title">
                 <h2><i class="fa fa-cubes" aria-hidden="true"></i> <?php echo $tr->translate('GENERAL_SETTING')?></h2>
                 <ul class="nav navbar-right panel_toolbox">
                    <li>
                    	<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
               	</ul>
               <div class="clearfix"></div>
          	</div>
           <div class="x_content">
               <br />
                      <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-2" for="first-name"><?php echo $tr->translate('PHONE')?><span class="required">*</span>
                        </label>
                        <div class="col-md-4 col-sm-4 col-xs-4">
                        	<?php echo $frm->getElement('phone')?>
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-2" for="first-name"><?php echo $tr->translate('EMAIL')?><span class="required">*</span>
                        </label>
                        <div class="col-md-4 col-sm-4 col-xs-4">
                        	<?php echo $frm->getElement('email')?>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-2" for="first-name"><?php echo $tr->translate('ARTICLE_PER_PAGE')?><span class="required">*</span>
                        </label>
                        <div class="col-md-4 col-sm-4 col-xs-4">
                        	<?php echo $frm->getElement('items_per_page')?>
                        </div>
                        <label class="control-label col-md-2 col-sm-2 col-xs-2" for="first-name"><?php echo $tr->translate('HOME_CATEGORY')?><span class="required">*</span>
                        </label>
                        <div class="col-md-4 col-sm-4 col-xs-4">
                        	<?php echo $frm->getElement('category')?>
                        </div>
                      </div>
                      <div class="form-group">
                        <label class="control-label col-md-2 col-sm-2 col-xs-2" for="first-name"><?php echo $tr->translate('ADDRESS')?><span class="required">*</span>
                        </label>
                        <div class="col-md-10 col-sm-10 col-xs-12">
                          <?php echo $frm->getElement('address')?>
                        </div>
                      </div>
                      <div class="col-md-6 col-sm-6 col-xs-12" style=" padding: 0;">
	                      <div class="form-group">
	                        <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('HOME_WELCOME')?><span class="required">*</span>
	                        </label>
	                        <div class="col-md-8 col-sm-8 col-xs-8">
	                        	<?php echo $frm->getElement('article')?>
	                        </div>
	                      </div>
	                      <div class="form-group">
	                        <label for="middle-name" class="control-label col-md-4 col-sm-4 col-xs-4"><?php echo $tr->translate('FACEBOOK')?></label>
	                        <div class="col-md-8 col-sm-8 col-xs-8">
	                          <?php echo $frm->getElement('facebook')?>
	                        </div>
	                      </div>
	                      <div class="form-group">
	                        <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('YOUTUBE')?><span class="required">*</span>
	                        </label>
	                        <div class="col-md-8 col-sm-8 col-xs-8">
	                        	<?php echo $frm->getElement('youtube')?>
	                        </div>
	                      </div>
	                      <div class="form-group">
	                        <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('YOUTUBE')?><span class="required">*</span>
	                        </label>
	                        <div class="col-md-8 col-sm-8 col-xs-8">
	                        	<?php echo $frm->getElement('twitter')?>
	                        </div>
	                      </div>
	                       <div class="form-group">
	                        <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('GOOGLE_PLUS')?><span class="required">*</span>
	                        </label>
	                        <div class="col-md-8 col-sm-8 col-xs-8">
	                        	<?php echo $frm->getElement('googleplus')?>
	                        </div>
	                      </div>
                      </div>
                      <div class="col-md-6 col-sm-6 col-xs-12" style="border: solid 1px #ccc;  padding: 10px;">
                      	<div  style="">
                      		<img class="image_view" id="image_view" src="<?php echo $this->baseUrl().'/images/'.$profile;?>" alt=""  style=" width: 30%;" />
							<div class="button_browse" style=" width: 55%;">
								<span>Change Logo<span><i class="fa fa-camera" aria-hidden="true"></i></span></span>
								<input class="btn_borwse_image"  type="file" id="photo" name="photo" onchange="loadImage()">
							</div>
                      	</div>
                      	<br />
                      	<div style="text-align: center;">
                      		<img class="image_view bd" id="image_viewbg" src="<?php echo $this->baseUrl().'/images/'.$header;?>" alt=""  />
							<div class="button_browse">
								<span>Change Background Header<span><i class="fa fa-camera" aria-hidden="true"></i></span></span>
								<input class="btn_borwse_image"  type="file" id="backgroundheader" name="backgroundheader" onchange="loadImage1()">
							</div>
                      	</div>
                      </div>
                      <div class="clearfix"></div>
                      <div class="ln_solid"></div>
                      <div class="form-group">
                        <div class="col-md-12 col-sm-12 col-xs-12 col-md-offset-5">
                          	<input type="button" value="GO_BACK" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
							iconClass="dijitIconUndo" onclick="window.history.back();" />
							<input class="button_success" type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE');?>" id="save_close" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 
                        </div>
                      </div>

                  </div>
                </div>
              </div>
            </div>
</form>
		
<script>
function loadImage(){
	 var output = document.getElementById('image_view');
  output.src = URL.createObjectURL(event.target.files[0]);
}
function loadImage1(){
	 var output = document.getElementById('image_viewbg');
  output.src = URL.createObjectURL(event.target.files[0]);
}
</script>