<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('Edit Location'));
$frm = $this->frm;
?>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>

<form id="add_location" action="<?php echo $this->url(array('module'=>'location','controller'=>'location','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data" >
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				loading();
				return true;
			} else {
				return false;
			}
	</script>
	<div class="clearfix"></div>
	<div class="row">
      	 <div class="col-md-8 col-xs-12 forms_padding">
          <div class="x_panel">
              <div class="x_title">
                 <h2><i class="fa  fa-info-circle" aria-hidden="true"></i> <?php echo $tr->translate('Edit Location')?></h2>
                 <ul class="nav navbar-right panel_toolbox">
                    <li>
                    	<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                    </li>
               	</ul>
               <div class="clearfix"></div>
               <div class="x_content">
               		<div class="form-group">
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Location Name')?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                   		<?php echo $frm->getElement("location_name");?>
	                   		<input dojoType="dijit.form.ValidationTextBox" class="fullside" required="true" id="id" name="id" value="<?php echo $this->row['id'];?>" type="hidden">
	                   </div>
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Province")?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                  	 <?php echo $frm->getElement("province_name");?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('Service Type')?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                   		 <?php echo $frm->getElement("service_type");?>
	                   </div>
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("Location Type")?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                  	 <?php echo $frm->getElement("location_type");?>
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate('STATUS')?>
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                    <?php echo $frm->getElement("status");?>
	                   </div>
	                </div>
	                <div class="form-group">
		                <div class="col-md-12 col-sm-12 col-xs-12">
		                <?php echo $frm->getElement("note");?>
		                </div>
	                </div>
               </div>
             </div>
          </div>
       </div>
        <div class="col-md-4 col-xs-12 forms_padding">
	         <div class="x_panel">
	              <div class="x_title">
	                 <h2><i class="fa  fa-info-circle" aria-hidden="true"></i> <?php echo $tr->translate('Image Location')?></h2>
	                 <ul class="nav navbar-right panel_toolbox">
	                    <li>
	                    	<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
	                    </li>
	               	</ul>
	               <div class="clearfix"></div>
	               <div class="x_content">
						<div style="clear: both;"></div>
						<input type="hidden" dojoType="dijit.form.TextBox" id="record_row" name="record_row" />
						<div  id="store_record"></div>
						<input iconClass="dijitIconClear" type="button" onClick="addNewSeason();" label="Add Record Photo" dojoType="dijit.form.Button"/>
	               </div>
	             </div>
	          </div>
        </div>
        <div class="clearfix"></div>
	     <div class="col-md-12 col-sm-12 col-xs-12 text-center">
	      	<input type="reset" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>"dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
			<input type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button" 
				iconClass="dijitEditorIcon dijitEditorIconSave" />			
	    </div>
   </div>
</form>

<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");
require(["dojo/ready"], function(ready){
	ready(function(){
		innitialize();
		checkLocationType();
	});
});
r=0;
function innitialize(){
	dojo.query("#store_record").append('');
	tmp='<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
	tmp+='<tr style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	tmp+='</table>';
	dojo.query("#store_record").append(tmp);
	thead='<th>Delete</th>';
	thead+='<th>Images Name</th>';
	thead+='<th>Preview Image</th>';
	fund_title=1;
	dojo.query("#head_title").append(thead);	
	dijit.byId('record_row').attr('value','');
	
	<?php if(!empty($this->rowpic)) {
	foreach($this->rowpic AS $i=>$rs){?>
	r++;
	tmp='<tr style="border:1px solid #ccc; font-size:12px;" id="row_guide'+r+'">'
	tmp+="</tr>";
		dojo.query("#t_amountmoneytype").append(tmp);
		
	temp='<td style="width:30px !important;text-align:center;" ><img style="cursor:pointer" onclick="deleteRecord('+r+')" src="<?php echo $this->baseUrl()?>/images/Delete_16.png"></td>';
	temp+='<td><input type="hidden" dojoType="dijit.form.TextBox" name="old_photoid'+r+'" id="old_photoid'+r+'" /></td>';
	temp+='<td><img style="max-height: 40px;" src="<?php echo $this->baseUrl().'/images/location/'.$rs['pic_title'];?>" /></td>';
		dojo.html.set(dojo.byId("row_guide"+r),temp, {
	    parseContent: true,
	     
	});
	if(dijit.byId("record_row").get('value')!="") {
		var ids = dijit.byId("record_row").value;
		dijit.byId("record_row").attr('value',ids+','+r);
	} else { dijit.byId("record_row").attr('value',r);}

	dijit.byId('old_photoid'+r).attr('value','<?php echo $rs['id'];?>');
<?php }}?>

}
function addNewRecord(){
	dojo.query("#store_record").append('');
	tmp='<table id="t_amountmoneytype" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
	tmp+='<tr style="background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	tmp+='</table>';
	dojo.query("#store_record").append(tmp);
	thead='<th>Delete</th>';
	thead+='<th>Images Name</th>';
	fund_title=1;
	dojo.query("#head_title").append(thead);	
	dijit.byId('record_row').attr('value','');
	addNewSeason();
}

function addNewSeason(){
	r++;
	tmp='<tr style="border:1px solid #ccc; font-size:12px;" id="row_guide'+r+'">'
	tmp+="</tr>";
		dojo.query("#t_amountmoneytype").append(tmp);
		
	temp='<td style="width:30px !important;text-align:center;" ><img style="cursor:pointer" onclick="deleteRecord('+r+')" src="/lyna/trunk/public/images/Delete_16.png"></td>';
	temp+='<td><input type="file" name="photo'+r+'" id="photo'+r+'" /></td>';
	
		dojo.html.set(dojo.byId("row_guide"+r),temp, {
	    parseContent: true,
	     
	});
	if(dijit.byId("record_row").get('value')!="") {
		var ids = dijit.byId("record_row").value;
		dijit.byId("record_row").attr('value',ids+','+r);
	} else { dijit.byId("record_row").attr('value',r);}
}
function deleteRecord(index){
	var ids =dijit.byId('record_row').value;
	if(ids.length=='' || ids.length==null){
		dijit.byId('record_row').attr('value','');
		dojo.query("#row_guide"+ids).remove();
	}else{
		var arrays = ids.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		dijit.byId('record_row').attr('value',strings);
		dojo.query("#row_guide"+index).remove();
	}
}
function checkLocationType(){
	service_type = dijit.byId('service_type').get('value');
	if(service_type==1){
		dijit.byId('location_type').set('readOnly',false);
	}else{
		dijit.byId('location_type').set('readOnly',true);
	}
}
</script>
