<?php 
     $url_save = $this->url(array('module'=>'group','controller'=>'customertype','action'=>'edit'));
     $tr=Application_Form_FrmLanguages::getCurrentlanguage();
     $frm = $this->frm_custype;
?>
<title><?php echo $tr->translate("EDIT_AGENCY_TYPE")?></title>
<form id="add_province" action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	 <script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				loading();
				return true;
			} else {
				return false;
			}
	</script>
	<div class="clearfix"></div>
	<div class="row">
	 	<div class="col-md-3 col-xs-12 forms_padding">
	 	</div>
      	 <div class="col-md-6 col-xs-12 forms_padding">
	          <div class="x_panel">
	              <div class="x_title">
	                 <h2><i class="fa  fa-plus-circle" aria-hidden="true"></i> <?php echo $tr->translate('EDIT_AGENCY_TYPE')?></h2>
	                 <ul class="nav navbar-right panel_toolbox">
	                    <li>
	                    	<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
	                    </li>
	               	</ul>
	               <div class="clearfix"></div>
	          	</div>
	       		<div class="x_content">
	       			<div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-12" for="first-name"><?php echo $tr->translate('TITLE')?>
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-12">
	                    	<?php echo $frm->getElement('title');?>
	                    	<input type="hidden" id="id" name="id" value="<?php echo $this->id;?>"/>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-4 col-sm-4 col-xs-12" for="first-name"><?php echo $tr->translate('STATUS')?>
	                   </label>
	                   <div class="col-md-8 col-sm-8 col-xs-12">
	                    	<?php echo $frm->getElement('status');?>
	                   </div>
	                </div>
	                <div class="clearfix"></div>
			       	<div class="ln_solid"></div>
				     <div class="col-md-12 col-sm-12 col-xs-12 text-center">
				        <input type="reset" style="color:#000;" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" 
								iconClass="dijitIconClear" /> 
						<input type="submit" value="SAVE_CLOSE" label="<?php echo $tr->translate('SAVECLOSE');?>" style="color:#000;" id="save_close" dojoType="dijit.form.Button" name="save_close"
							iconClass="dijitEditorIcon dijitEditorIconSave" /> 
				    </div>
	       		</div>
	       	</div>
	       	
	     </div>
	     <div class="col-md-3 col-xs-12 forms_padding">
	 	</div>
	 </div>
</form> 