<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('EDIT_ARTICLE')); 
echo $this->headTitle();
$frm = $this->frm;
$db = new MenuManager_Model_DbTable_DbArticle();
$countlang = count($this->lang);

if(!empty($this->row['image_feature'])){
	$profile="article/".$this->row['image_feature'];
}else{
	$profile ="slide/no-photo.png";
}
?>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.FilteringSelect');
	dojo.require("dijit.Dialog");
	require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
</script>
<style>
	div.cke_contents.cke_reset {
		height: 600px !important;
	}
	img.image_view {
		width: 100%;
		height: 182px;
	}
	#table_parent thead tr td{
		background: url(../images/tbheader-bg1.jpg) repeat-x scroll center top #F1F1F1;
		border: 1px solid #CCC;
		color: #333;
		font-size: 14px;
		font-weight: bold;
		line-height: 30px;
		padding: 2px 5px;
		text-align: center;
		cursor: pointer;
	}
</style>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>
<script src="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.js"></script>
<link href="<?php echo $this->baseUrl();?>/ckeditor/samples/sample.css" rel="stylesheet">
<form action="<?php echo $this->url(array('module'=>'menu-manager','controller'=>'article','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				if(alias_require==0){ alert("Please check your title alias again.");return false;}
				loading();
				return true;
			}

			return false;
	</script>
	<div class="clearfix"></div>
	<div class="row">
      <div class="col-md-8 col-sm-8 col-xs-12">
          <div class="x_panel">
             <div class="x_title">
                <h2><i class="fa fa-bars"></i> <?php echo $tr->translate('EDIT_ARTICLE')?></h2>
                <ul class="nav navbar-right panel_toolbox">
                   <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                </ul>
                <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                  	<?php if ($countlang>1){?>
                    <div class="" role="tabpanel" data-example-id="togglable-tabs">
                      <ul id="myTab" class="nav nav-tabs bar_tabs" role="tablist">
                      <?php $alias=''; foreach($this->lang as $key=> $rs){
                      	$alias = str_replace(' ','',$rs['title']); $lang = $db->getArticleTitleByLang($this->id, $rs['id']);?>
                        <li role="presentation" class="<?php if ($key<1){echo "active";}?>"><a href="<?php echo "#".$alias;?>" id="<?php echo "#".$alias."-tab";?>" role="tab" data-toggle="tab" aria-expanded="true"><?php echo $tr->translate(strtoupper($rs['title']));?></a>
                        </li>
                     <?php }?>
                      </ul>
                      <div id="myTabContent" class="tab-content">
                      <?php $alias=''; foreach($this->lang as $key=> $rs){
                      	$alias = str_replace(' ','',$rs['title']); $lang = $db->getArticleTitleByLang($this->id, $rs['id']);?>
                        <div role="tabpanel" class="tab-pane fade <?php if ($key<1){echo "active in";}?>" id="<?php echo $alias;?>" aria-labelledby="<?php echo $alias."-tab";?>">
                          <div class="form-group">
			                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate(strtoupper($rs['title']));?><span class="required">*</span>
			                   </label>
			                   <div class="col-md-8 col-sm-8 col-xs-8">
			                	   <input   type="text" onChange="generateAlias('<?php echo $alias;?>');" dojoType="dijit.form.TextBox" required="required" name="title<?php echo str_replace(' ','',$rs['title']);?>"  id="title<?php echo str_replace(' ','',$rs['title']);?>" value="<?php echo $lang['title'];?>" class="fullside" placeholder="<?php echo $tr->translate("TITLE_IN_".strtoupper($rs['title']));?>" />
													<input type="hidden" dojoType="dijit.form.TextBox" name="iddetail<?php echo str_replace(' ','',$rs['title']);?>"  id="iddetail<?php echo str_replace(' ','',$rs['title']);?>" value="<?php echo $lang['id'];?>" class="fullside" />
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-12 col-sm-12 col-xs-12" for="first-name"><?php echo $tr->translate('CONTENT_'.strtoupper($rs['title']))?><span class="required">*</span>
			                   </label>
			                   <div class="col-md-12 col-sm-12 col-xs-12">
			                 	  <textarea class="ckeditor"   style="min-height:400px; height:400px;" id="description<?php echo str_replace(' ','',$rs['title']);?>" name="description<?php echo str_replace(' ','',$rs['title']);?>"><?php echo $lang['description'];?></textarea>
			                   </div>
			                </div>
                        </div>
                     <?php }?>
                      </div>
                    </div>
                    <?php }else{?>
                     <?php $alias=''; foreach($this->lang as $key=> $rs){
                      	$alias = str_replace(' ','',$rs['title']); $lang = $db->getArticleTitleByLang($this->id, $rs['id']);?>
                        <div role="tabpanel" class="tab-pane fade <?php if ($key<1){echo "active in";}?>" id="<?php echo $alias;?>" aria-labelledby="<?php echo $alias."-tab";?>">
                          <div class="form-group">
			                   <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate(strtoupper($rs['title']));?><span class="required">*</span>
			                   </label>
			                   <div class="col-md-8 col-sm-8 col-xs-8">
			                	   <input   type="text" onChange="generateAlias('<?php echo $alias;?>');" dojoType="dijit.form.TextBox" required="required" name="title<?php echo str_replace(' ','',$rs['title']);?>"  id="title<?php echo str_replace(' ','',$rs['title']);?>" value="<?php echo $lang['title'];?>" class="fullside" placeholder="<?php echo $tr->translate("TITLE_IN_".strtoupper($rs['title']));?>" />
													<input type="hidden" dojoType="dijit.form.TextBox" name="iddetail<?php echo str_replace(' ','',$rs['title']);?>"  id="iddetail<?php echo str_replace(' ','',$rs['title']);?>" value="<?php echo $lang['id'];?>" class="fullside" />
			                   </div>
			                </div>
			                <div class="form-group">
			                   <label class="control-label col-md-12 col-sm-12 col-xs-12" for="first-name"><?php echo $tr->translate('CONTENT_'.strtoupper($rs['title']))?><span class="required">*</span>
			                   </label>
			                   <div class="col-md-12 col-sm-12 col-xs-12">
			                 	  <textarea class="ckeditor"   style="min-height:400px; height:400px;" id="description<?php echo str_replace(' ','',$rs['title']);?>" name="description<?php echo str_replace(' ','',$rs['title']);?>"><?php echo $lang['description'];?></textarea>
			                   </div>
			                </div>
                        </div>
                     <?php }?>
                    <?php }?>
                  </div>
                </div>
              </div>
	          <div class="col-md-4 col-sm-4 col-xs-12">
	                <div class="x_panel">
	                  <div class="x_title">
	                    <ul class="nav navbar-right panel_toolbox">
	                      <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
	                      </li>
	                    </ul>
	                    <div class="clearfix"></div>
	                    <div class="x_content">
	                    	<br />
		                    <div class="form-group">
			                   <div class="col-md-12 col-sm-12 col-xs-12">
			                 	  <label id="message" style="color: red;"></label>
								  <?php echo $frm->getElement('title_alias');?>
			                   </div>
			                </div>
			                 <div class="form-group">
			                	<label class="control-label col-md-12 col-sm-12 col-xs-12"><?php echo $tr->translate('CHOOSE_CATEGORY')?>*</label>
			                   <div class="col-md-12 col-sm-12 col-xs-12">
								  <?php echo $frm->getElement('category');?>
			                   </div>
			                </div>
			                <div class="form-group">
			                	<label class="control-label col-md-12 col-sm-12 col-xs-12"><?php echo $tr->translate('STATUS')?>*</label>
			                   <div class="col-md-12 col-sm-12 col-xs-12">
								  <?php echo $frm->getElement('status');?>
			                   </div>
			                </div>
			            	 <div class="form-group">
				              	  <div class="col-md-12 col-sm-12 col-xs-12">
				              	  	<p style="padding: 10px 0; text-align: center;margin-bottom: 0;background: #454545;    margin-top: 10px;    color: #fff;">Image (285 X 240px)</p>
				               		<img class="image_view" id="image_view" src="<?php echo $this->baseUrl().'/images/'.$profile;?>" alt=""  />
									<div class="button_browse">
										<span>Image Feature<span> <i class="fa fa-camera" aria-hidden="true"></i></span></span>
										<input class="btn_borwse_image"  type="file" id="photo" name="photo" onchange="loadImage()">
									</div>
								</div>
			                </div>
	                    </div>
	                  </div>
	                 </div>
	             </div>
	             <div class="clearfix"></div>
	        	<div class="col-md-12 col-sm-12 col-xs-12 " style="  text-align: center;">
		          <input type="button" value="GO_BACK" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
					iconClass="dijitIconUndo" onclick="window.history.back();"/>
					<input class="button_success" type="submit" value="រក្សាទុក" label="<?php echo $tr->translate('SAVE_CLOSE');?>" id="submitButton" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 	
	        	  </div>
	          <div class="clearfix"></div>
          	</div>
          	 <div class="clearfix"></div>	
</form>
<script>
function loadImage(){
	 var output = document.getElementById('image_view');
  output.src = URL.createObjectURL(event.target.files[0]);
}
var alias_require=1;
	var old_alias="<?php echo $this->row['alias_article'];?>";
	var specialcharalias = [" ",",",".","?",";","/","{","}","|","[","]","~","!","@","#","$","%","^","&","*","(",")","+","=","`","<",">"];
	function generateAlias(alias){
		title = dijit.byId('title'+alias).get('value');
		var title_alias = title.split(' ').join('-');
		//title_alias = (title_alias.split('?').join('-')).split('"').join('-');
		for(var i=0; i<specialcharalias.length;i++){
			title_alias = title_alias.split(specialcharalias[i]).join('');
		}
		dijit.byId("title_alias").attr('value',title_alias.toLowerCase());
		checkTitle();
	}
	url_CheckTitle = '<?php echo $this->url(array('module'=>'menu-manager','controller'=>'article','action'=>'check-title-alias'));?>';
	function checkTitle(){
		title_alias = dijit.byId('title_alias').get('value');
		if(title_alias.toLowerCase()==old_alias.toLowerCase()){
			document.getElementById('message').innerHTML ='';
			alias_require=1;
			return false;
		}
		dojo.xhrPost({
			url:url_CheckTitle,	
			content:{ 
				'title_alias': title_alias
			},
			handleAs:"json",
			load: function(data) {	
				if(data !== false ){
			   		document.getElementById('message').innerHTML ='Alias is duplicated you can set new alias or clear alias will auto generate.';
			   		dijit.byId('title_alias').focus();
			   		alias_require=0;
				}else{
					document.getElementById('message').innerHTML ='';
					alias_require=1;
				}
			},
			error: function(err) {
				alert(err);
			}
		});
	}
	function checkSpcialCharFortitle(event){
        if(((event.keyCode > 64 && event.keyCode < 91) || event.keyCode == 37 || event.keyCode == 39 || event.keyCode == 34 || event.keyCode == 32 || event.keyCode == 63 || event.keyCode == 45 || (event.keyCode > 96 && event.keyCode < 123) || event.keyCode == 8 || (event.keyCode >= 48 && event.keyCode <= 57))){
            event.returnValue = true;
            return;
         }
         event.returnValue = false;
      }
	 function checkSpcialChar(event){
         if(((event.keyCode > 64 && event.keyCode < 91) || event.keyCode == 45 || (event.keyCode > 96 && event.keyCode < 123) || event.keyCode == 8 || (event.keyCode >= 48 && event.keyCode <= 57))){
             event.returnValue = true;
             return;
          }
          event.returnValue = false;
       }
</script>
