<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('HOME_CONTENT')); 
echo $this->headTitle();
$frm = $this->frm;
$countlang = count($this->lang);
$home_article = json_decode($this->home_article['value'],true);
//print_r($home_article['values']['English']);

?>
<style>
div.cke_contents.cke_reset {
    height: 500px !important;
}
</style>
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');	
	dojo.require('dijit.form.Button');
	dojo.require('dijit.form.FilteringSelect');
	dojo.require("dijit.Dialog");
	require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
	dojo.require("dojo.parser");
	dojo.require("dojo.NodeList-manipulate");
</script>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>

<style>

img.image_view {
    width: 50px;
	height: 50px;
}

</style>
<form action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				if(alias_require==0){ alert("Please check your title alias again.");return false;}
				return true;
			}

			return false;
	</script>
		
	<table  style="margin: 0 auto; width: 100%">
		<tr class="header">
			<td><strong><i class="fa fa-cubes" aria-hidden="true"></i><?php echo $tr->translate('HOME_CONTENT')?></strong></td>
		</tr>
		<tr>
			<td>
					<table width="100%">
						<tr>
							<td align="left" valign="top" width="90%">
							<fieldset>
							<?php if ($countlang>1){?>
								<div id="mainTabContainer" style=" position:relative; width:1000px; display:block; height: 820px;" dojoType="dijit.layout.TabContainer" region="center" >
					      	<?php }?>		
					      	<?php $alias=''; foreach($this->lang as $key=> $rs){ $titlelang = str_replace(' ','',$rs['title']); if ($key<1){ $alias = str_replace(' ','',$rs['title']);}?>
					      			<div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="<?php echo $tr->translate(strtoupper($rs['title']));?>" selected="true">
										<table cellspacing="5" width="100%">
											<tr>
												<td class="bold"><?php echo $tr->translate('TITLE')?></td>
												<td>
													<input type="text" onChange="generateAlias('<?php echo $alias;?>');" dojoType="dijit.form.TextBox" required="required" name="title<?php echo str_replace(' ','',$rs['title']);?>"  id="title<?php echo str_replace(' ','',$rs['title']);?>" value="<?php echo $home_article['values'][$key][$titlelang];?>" class="fullside" placeholder="<?php echo $tr->translate("TITLE_IN_".strtoupper($rs['title']));?>" />
													<?php //echo $frm->getElement('title');?>
												</td>
											</tr>
											<tr><td colspan="2" class="bold"><?php echo $tr->translate('CONTENT_'.strtoupper($rs['title']))?></td></tr>
											<tr>
												<td colspan="2">
													<textarea class="ckeditor"   style="min-height:600px; height:600px;" id="description<?php echo str_replace(' ','',$rs['title']);?>" name="description<?php echo str_replace(' ','',$rs['title']);?>"><?php echo $home_article['values'][$key]['description'.$titlelang];?></textarea>
												</td>
											</tr>
										</table>
									</div>
								<?php }?>
							<?php if ($countlang>1){?>
								</div>
							<?php }?>
								</fieldset>
							</td>
						</tr>
						<tr>
							<td colspan="2" align="center">
								<input type="button" value="GO_BACK" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
								iconClass="dijitIconUndo" onclick="window.history.back();" />
								<input class="button_success" type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVE');?>" id="save_new" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
							</td>
						</tr>
					</table>	
			</td>			
		</tr>
	</table>	
	<input type="hidden" id="agent" name="agent" value="0" />	
</form>
</script>
