<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<style>
#footer{display: none;}
table{
	font-family: 'Khmer OS Siemreap';
	font-size: 11px;
}
 .padd tr td{ 
	font-family: 'Khmer OS Siemreap';
	font-size: 11px;
 }
</style>	
<form>
<div style="border: 1px dotted #000;background: #fff; margin: 0 auto;min-height: 25cm;">
		<div id="divPrint">
			<table style="background:#fff; margin: 0 auto; width: 100%; padding: 1cm; ">
							<tr>
								<td colspan="3" align="center"><strong style=" color:#04AE18; font:18px bold,'Khmer MEF2';">ព្រះរាជាណាចក្រកម្ពុជា<br />ជាតិ សាសនា ព្រះមហាក្សត្រ</strong></td>
							</tr>
							<tr>
								<td colspan="3" align="right"><strong style=" color:#04AE18; font:18px bold,'Khmer MEF2';">វិក័យប័ត្រទទួលប្រាក់</strong></td>
							</tr>
							<tr>
								<td colspan="3" align="center"><strong style=" color:#04AE18; font: 18px bold, 'Webdings'">plolp</strong></td>
							</tr>
							<tr>
								<td colspan="3" align="left"><strong style="color:#04AE18;">Vehicle’s Owner Information - ពត៌មានម្ចាស់រថយន្ត</strong></td>
							</tr>
							<tr>
								<td colspan="3">
										<table class="padd" width="100%" align="center" style=" white-space:nowrap; border-collapse: collapse;">
											<tr style="height: 20px; ">
												<td>&nbsp;ខ្ញុំបាទ/នាងខ្ញុំឈ្មោះ  </td>
												<td width="40%" style="border-bottom: 1px solid #000;">&nbsp;<strong>&nbsp;</strong></td>
												<td >&nbsp;ថ្ងៃខៃឆ្នាំកំណើត: </td>
												<td colspan="2"style="border-bottom: 1px solid #000;">&nbsp;<strong>&nbsp;</strong></td>
												<td>&nbsp;កាន់អត្តសញ្ញាណ្ណប័ណ្ណ </td>
												
											</tr>
											<tr>
												<td width="20%">&nbsp;ឬ លិខិតឆ្លងដែនលេខ: </td>
												<td width="20%"  style="border-bottom: 1px solid #000;">&nbsp;<strong>&nbsp;</strong></td>
												<td>&nbsp;ចុះថ្ងៃទីខែឆ្នាំ  </td>
												<td style="border-bottom: 1px solid #000;">&nbsp;<strong>&nbsp;</strong></td>
												<td>&nbsp;ចេញដោយ:</td>
												<td width="30%" style="border-bottom: 1px solid #000;">&nbsp;<strong>&nbsp;</strong></td>
												<td colspan="2" style="border-bottom: #fff solid 1px;">&nbsp;</td>
											</tr>
											<tr>
												<td>&nbsp;បានទទួលប្រាក់ចំនួន  </td>
												<td style="border-bottom: #000 solid 1px;">&nbsp;</td>
												<td style="border-bottom: #fff solid 1px;" >&nbsp;ជាអក្សរ:</td>
												<td width="30%" style="border-bottom: #000 solid 1px;">&nbsp;</td>
												<td style="border-bottom: #fff solid 1px;">&nbsp;ដុល្លាសហរដ្ឋអាមេរិក)</td>
												<td style="border-bottom: #fff solid 1px;" colspan="2">&nbsp;<input type="checkbox" /> ប្រាក់កក់មុនទិញ</td>
											</tr>
											<tr>
												<td>&nbsp;រថយន្ត </td>
												<td colspan="5">&nbsp;<input type="checkbox" /> ប្រាក់ថ្លៃលក់រថយន្ត ដូចបានរៀបរាប់ខាងក្រោម:</td>
											</tr>
										</table>
								</td>
							</tr>
							<tr>
								<td colspan="3" align="left"><strong style="color:#04AE18;">Vehicle’s Information - ពត៌មានរថយន្ត</strong></td>
							</tr>
							<tr>
								<td colspan="3">
									<div style="border: solid 1px #000;">
										<table class="padd" width="100%" align="center" style=" white-space:nowrap; border-collapse: collapse;">
											<tr style="height: 20px; ">
												<td width="25%">&nbsp;ឆ្នាំផលិត Year:</td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;</td>
												<td width="25%">&nbsp;លេខតួ Frame No.: </td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;</td>
											</tr>
											<tr>
												<td width="25%">&nbsp;ម៉ាក Make:</td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;</td>
												<td width="25%">&nbsp;សាក់ស៊ី Chassis No.: </td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;</td>
											</tr>
											<tr>
												<td width="25%">&nbsp;ម៉ូដែល Model:</td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;</td>
												<td width="25%">&nbsp;លេខម៉ាស៊ីន Engine No.: </td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;</td>
											</tr>
											<tr>
												<td width="25%">&nbsp;ម៉ូដែលបន្ទាប់ Sub-model:</td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;</td>
												<td width="25%">&nbsp;ចំនួនភ្លៅ No Of Axles: </td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;</td>
											</tr>
											<tr>
												<td width="25%">&nbsp;ប្រភេទ Type:</td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;</td>
												<td width="25%">&nbsp;ចំនួនស៊ីឡាំង No. of Cylinders: </td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;</td>
											</tr>
											<tr>
												<td width="25%">&nbsp;ពណ៌ Color:</td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;</td>
												<td width="25%">&nbsp;ទំហំស៊ីឡាំង Cylinder Size: </td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000;">&nbsp;</td>
											</tr>
											<tr>
												<td width="25%">&nbsp;កម្លាំង Horse Power:</td>
												<td width="25%" colspan="2">&nbsp;</td>
												<td width="25%">&nbsp;លាកលេខ Plaque No.: </td>
												<td width="25%" colspan="2">&nbsp;</td>
											</tr>
										</table>
									</div>
								</td>
							</tr>
							<tr>
								<td colspan="3" align="left"><strong style="color:#04AE18;">Buyer’s Information - ពីភាគី អ្នកទិញ</strong></td>
							</tr>
							<tr>
								<td colspan="3">
										<table class="padd" width="100%" align="center" style=" white-space:nowrap; border-collapse: collapse;">
											<tr style="height: 20px; ">
												<td>&nbsp;នាមនិងគោត្តនាម: </td>
												<td width="40%" style="border-bottom: 1px solid #000;">&nbsp;<strong>&nbsp;</strong></td>
												<td >&nbsp;ថ្ងៃខៃឆ្នាំកំណើត: </td>
												<td colspan="2"style="border-bottom: 1px solid #000;">&nbsp;<strong>&nbsp;</strong></td>
												<td>&nbsp;កាន់អត្តសញ្ញាណ្ណប័ណ្ណ </td>
												
											</tr>
											<tr>
												<td>&nbsp;ឬ លិខិតឆ្លងដែនលេខ:</td>
												<td style="border-bottom: 1px solid #000;"><strong>&nbsp;</strong></td>
												<td>&nbsp;ចុះថ្ងៃទីខែឆ្នាំ  </td>
												<td width="20%"style="border-bottom: 1px solid #000;">&nbsp;<strong>&nbsp;</strong></td>
												<td>&nbsp; ចេញដោយ:</td>
												<td width="20%"style="border-bottom: 1px solid #000;">&nbsp;<strong>&nbsp;</strong></td>
												<td>&nbsp;។</td>
											</tr>
										</table>
								</td>
							</tr>
							<tr>
								<td colspan="3" align="left"><strong style="color:#04AE18;">Special Statement - សេចក្តីបញ្ជាក់ </strong></td>
							</tr>
							<tr>
								<td colspan="3">
									<table class="padd" width="100%" align="center" style="white-space:nowrap; border-collapse: collapse;">
										<tr>
											<td>&nbsp;ប្រាក់នៅសល់ចំនួន: </td>
											<td style="border-bottom: 1px solid #000;">&nbsp;</td>
											<td>&nbsp;ជាអក្សរ:</td>
											<td style="border-bottom: 1px solid #000;">&nbsp;</td>
											<td>&nbsp;ដុល្លាសហរដ្ឋអាមេរិក នឹងត្រូវទូទាត់</td>
										</tr>
										<tr>
											<td width="10%">&nbsp;នៅថ្ងៃទីខែឆ្នាំ: </td>
											<td width="35%" style="border-bottom: 1px solid #000;">&nbsp;</td>
											<td width="10%">&nbsp;វេលាម៉ោង </td>
											<td width="45%" style="border-bottom: 1px solid #000;">&nbsp;</td>
											<td>&nbsp;។ </td>
										</tr>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="3">រថយន្ត ដែលបានរៀបរាប់ខាងលើនឹងត្រូវប្រគល់ជូនទៅឱ្យ<strong>ភាគីអ្នកទិញ</strong> បន្ទាប់ពីបានទទួលទឹកប្រាក់គ្រប់ចំនួន។</td>
							</tr>
							<tr>
								<td colspan="3">
									<p><strong style="color:#04AE18;">Special Notice - ចំណាំពិសេស: </strong>បើភាគីអ្នកទិញចង់មានការកែប្រែចិត្ត ភាគីអ្នកលក់មិនអាចត្រឡប់ប្រាក់កក់ជូនវិញបានទេ!</p>
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<table class="padd" width="100%"  align="center" white-space:nowrap; border-collapse: collapse;">
										<tr align="center">
											<td colspan="3" width="10%">&nbsp;</td>
											<td width="40%">&nbsp;ធ្វើនៅថ្ងៃទីខែឆ្នាំ: Monday, August 18, 2015</td>
										</tr>
										<tr align="center">
											<td width="">&nbsp;ហត្ថលេខាឬស្នាមមេដៃស្តាំអ្នកទិញ</td>
											<td colspan="2">&nbsp;</td>
											<td>&nbsp;ហត្ថលេខាឬស្នាមមេដៃស្តាំអ្នកទទួលប្រាក់</td>
										</tr>
										<tr align="center">
											<td colspan="4">&nbsp;</td>
										</tr>
										<tr align="center">
											<td colspan="4">&nbsp;</td>
										</tr>
										<tr align="center">
											<td style="border-bottom: 1px solid #000;"></td>
											<td colspan="2">&nbsp;</td>
											<td style="border-bottom: 1px solid #000;"></td>
										</tr>
										<tr align="center">
											<td width=""><h4>ស៊ីម សំណាង</h4></td>
											<td width="10%">&nbsp;</td>
											<td width="10%">&nbsp;</td>
											<td><h4>ស៊ីម សំណាង</h4></td>
										</tr>
									</table>
								</td>
							</tr>
					</table>
	</div>	
</div>
</form>
