<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<style>
#footer{display: none;}
table{
	font-family: 'Khmer OS Siemreap';
	font-size: 11px;
}
 table .padd{ 
	font-family: 'Khmer OS Siemreap';
	font-size: 11px;
 }
</style>	
<div style="border: 1px dotted #000;background: #fff; margin: 0 auto;min-height: 25cm;">
		<div id="divPrint">
			<table style="background:#fff; margin: 0 auto; width: 100%; padding: 1cm; ">
							<tr>
								<td colspan="3" align="center"><strong style=" color:#04AE18; font:18px bold,'Khmer MEF2';">ព្រះរាជាណាចក្រកម្ពុជា<br />ជាតិ សាសនា ព្រះមហាក្សត្រ</strong></td>
							</tr>
							<tr>
								<td colspan="3" align="center"><strong style=" color:#04AE18; font:18px bold,'Khmer MEF2';">លិខិតលក់យានយន្ត VEHICLE BILL OF SALE</strong></td>
							</tr>
							<tr>
								<td colspan="3" align="center"><strong style="font: 18px bold, 'Webdings'">plolp</strong></td>
							</tr>
							<tr>
								<td colspan="3" align="left"><strong style="color:#04AE18; font:14px">ពត៌មានអ្នកលក់ VENDOR’S INFORMATION</strong></td>
							</tr>
							<tr>
								<td colspan="3">
									<div style="border: solid 1px #000;">
										<table class="padd" width="100%" align="center" style="white-space:nowrap; border-collapse: collapse;">
											<tr style="height: 20px; ">
												<td width="10%">&nbsp;នាមនិងគោត្តនាម:</td>
												<td width="40%" style="border-bottom: 1px solid #000; font-weight:bold; font-style:italic;">&nbsp;Mr Sawada Koji</td>
												<td width="5%"style="border-bottom: 1px solid #fff;">&nbsp;ភេទ:</td>
												<td width="20%" style="border-bottom: 1px solid #000; font-weight:bold; font-style:italic; ">&nbsp;ប្រុស</td>
												<td width="5%"style="border-bottom: 1px solid #fff; border-left: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;អាយុ:</td>
												<td width="20%" style="font-weight:bold; font-style:italic;">38  ឆ្នាំ</td>
											</tr>
											<tr>
												<td style="border-bottom: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;មុខងារបច្ចុប្បន្ម:</td>
												<td colspan="5" style="border-bottom: 1px solid #000; font-weight:bold; font-style:italic;">&nbsp;គ្រូគង្វាល</td>
											</tr>
											<tr>
												<td style="border-bottom: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;អង្គភាពឬក្រុមហ៊ុន:</td>
												<td colspan="5" style="border-bottom: 1px solid #000; font-weight:bold; font-style:italic;">&nbsp;JICA-ITC Project</td>
											</tr>
											<tr>
												<td style="border-bottom: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;អស័យដ្ឋាន:</td>
												<td colspan="5" style="border-bottom: 1px solid #000; font-weight:bold; font-style:italic;">&nbsp;#14 ផ្លូវលេខ 432, សង្កាត់ បឹងត្របែក ខ័ណ្ឌ ចំការមន ក្រុងភ្នំពេញ</td>
											</tr>
											<tr>
												<td style="border-bottom: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;លិខិតឆ្លងដែន ឬ ID:</td>
												<td style="border-bottom: 1px solid #000; font-weight:bold; font-style:italic;">&nbsp;MB3581838</td>
												<td style="border-left:1px solid #fff; border-bottom: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;សញ្ជាតិ:</td>
												<td colspan="3" style="border-bottom: 1px solid #000; font-weight:bold; font-style:italic;">ជប៉ុន</td>
											</tr>
											<tr>
												<td style="border-right: solid 1px #fff;">&nbsp;ទូរស័ព្ទចល័តលេខ:</td>
												<td style="font-weight:bold; font-style:italic;">&nbsp;012 222 864</td>
												<td style="border-left: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;អ៊ីម៉ែល:</td>
												<td colspan="3" style="font-weight:bold; font-style:italic;">&nbsp;coreytyoung@gmail.com</td>
											</tr>
										</table>
									</div>	
								</td>
							</tr>
							<tr>
								<td colspan="3" align="left"><strong style="color:#04AE18; font: bold;">ពត៌មានរថយន្ត VEHICLE’S INFORMATION</strong></td>
							</tr>
							<tr>
								<td colspan="3">
									<div style="border: solid 1px #000;">
										<table class="padd" width="100%" align="center" style=" white-space:nowrap; border-collapse: collapse;">
											<tr style="height: 20px; ">
												<td width="25%">&nbsp;ឆ្នាំផលិត Year:</td>
												<td width="25%" colspan="2" style=" font-weight:bold; font-style:italic; border-bottom: solid 1px #000;">&nbsp;1997</td>
												<td width="25%">&nbsp;លេខតួ Frame No.: </td>
												<td width="25%" colspan="2" style=" font-weight:bold; font-style:italic; border-bottom: solid 1px #000;">&nbsp;NIL</td>
											</tr>
											<tr>
												<td width="25%">&nbsp;ម៉ាក Make:</td>
												<td width="25%" colspan="2" style="font-weight:bold; font-style:italic; border-bottom: solid 1px #000;">&nbsp;MISUBISHI</td>
												<td width="25%">&nbsp;សាក់ស៊ី Chassis No.: </td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000; font-weight:bold; font-style:italic;">&nbsp;K960VP009306</td>
											</tr>
											<tr>
												<td width="25%">&nbsp;ម៉ូដែល Model:</td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000; font-weight:bold; font-style:italic;">&nbsp;MONTERO</td>
												<td width="25%">&nbsp;លេខម៉ាស៊ីន Engine No.: </td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000; font-weight:bold; font-style:italic;">&nbsp;6G72AG6154</td>
											</tr>
											<tr>
												<td width="25%">&nbsp;ម៉ូដែលបន្ទាប់ Sub-model:</td>
												<td width="25%" colspan="2" style="border-bottom: solid 1px #000; font-weight:bold; font-style:italic;">&nbsp; SPORT</td>
												<td width="25%">&nbsp;ចំនួនភ្លៅ No Of Axles: </td>
												<td width="25%" colspan="2" style="font-weight:bold; font-style:italic; border-bottom: solid 1px #000;">&nbsp;2</td>
											</tr>
											<tr>
												<td width="25%">&nbsp;ប្រភេទ Type:</td>
												<td width="25%" colspan="2" style="font-weight:bold; font-style:italic; border-bottom: solid 1px #000;">&nbsp;4WD</td>
												<td width="25%">&nbsp;ចំនួនស៊ីឡាំង No. of Cylinders: </td>
												<td width="25%" colspan="2" style="font-weight:bold; font-style:italic; border-bottom: solid 1px #000;">&nbsp;6</td>
											</tr>
											<tr>
												<td width="25%">&nbsp;ពណ៌ Color:</td>
												<td width="25%" colspan="2" style="font-weight:bold; font-style:italic; border-bottom: solid 1px #000;">&nbsp;បៃតង</td>
												<td width="25%">&nbsp;ទំហំស៊ីឡាំង Cylinder Size: </td>
												<td width="25%" colspan="2" style=" font-weight:bold; font-style:italic; border-bottom: solid 1px #000;">&nbsp;3000</td>
											</tr>
											<tr>
												<td width="25%">&nbsp;កម្លាំង Horse Power:</td>
												<td width="25%" colspan="2" style="font-weight:bold; font-style:italic;">&nbsp;188HP</td>
												<td width="25%">&nbsp;ផ្លាកលេខ Plaque No.: </td>
												<td width="25%" style="font-weight:bold; font-style:italic;">&nbsp; 2C-2139-PHP</td>
											</tr>
										</table>
									</div>
								</td>
							</tr>
							<tr>
								<td colspan="3" align="left"><strong style="color:#04AE18; font:bold;">ពត៌មានអ្នកទិញ BUYER’S INFORMATION</strong></td>
							</tr>
							<tr>
								<td colspan="3">
									<div style="border: solid 1px #000;">
										<table class="padd" width="100%" align="center" style="white-space:nowrap; border-collapse: collapse;">
											<tr style="height: 20px; ">
												<td width="10%">&nbsp;នាមនិងគោត្តនាម:</td>
												<td width="40%" style="border-bottom: 1px solid #000; font-weight:bold; font-style:italic;">&nbsp;Mr Sawada Koji</td>
												<td width="5%"style="border-bottom: 1px solid #fff;">&nbsp;ភេទ:</td>
												<td width="20%" style="border-bottom: 1px solid #000; font-weight:bold; font-style:italic; ">&nbsp;ប្រុស</td>
												<td width="5%"style="border-bottom: 1px solid #fff; border-left: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;អាយុ:</td>
												<td width="20%" style="font-weight:bold; font-style:italic;">38  ឆ្នាំ</td>
											</tr>
											<tr>
												<td style="border-bottom: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;មុខងារបច្ចុប្បន្ម:</td>
												<td colspan="5" style="border-bottom: 1px solid #000; font-weight:bold; font-style:italic;">&nbsp;ពាណិជ្ជករ</td>
											</tr>
											<tr>
												<td style="border-bottom: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;អង្គភាពឬក្រុមហ៊ុន:</td>
												<td colspan="5" style="border-bottom: 1px solid #000; font-weight:bold; font-style:italic;">&nbsp;</td>
											</tr>
											<tr>
												<td style="border-bottom: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;អស័យដ្ឋាន:</td>
												<td colspan="5" style="border-bottom: 1px solid #000; font-weight:bold; font-style:italic;">&nbsp;229, ផ្លូវ បេតុង, សក ស្ទឹងមានជ័យ ខ័ណ្ឌ មានជ័យ ក្រុង ភ្នំពេញ</td>
											</tr>
											<tr>
												<td style="border-bottom: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;លិខិតឆ្លងដែន ឬ ID:</td>
												<td style="border-bottom: 1px solid #000; font-weight:bold; font-style:italic;">&nbsp;010992672</td>
												<td style="border-left:1px solid #fff; border-bottom: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;សញ្ជាតិ:</td>
												<td colspan="3" style="border-bottom: 1px solid #000; font-weight:bold; font-style:italic;">ខ្មែរ</td>
											</tr>
											<tr>
												<td style="border-right: solid 1px #fff;">&nbsp;ទូរស័ព្ទចល័តលេខ:</td>
												<td>&nbsp;<i><strong>012  592 913</strong></i></td>
												<td style="border-left: 1px solid #fff; border-right: solid 1px #fff;">&nbsp;អ៊ីម៉ែល:</td>
												<td colspan="3">&nbsp;<strong><i>canavehiclerenting@gmail.com</i></strong></td>
											</tr>
										</table>
									</div>	
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<p style="font-size: 10px"><span style="font-weight: bold;">សន្យា: </span>ខ្ញុំបាទ/នាងខ្ញុំ សូមសន្យាចំពោះមុខច្បាប់ថា រថយន្តខាងលើ ពិតជារថយន្តរបស់ខ្ញុំបាទ/នាងខ្ញុំពិតប្រាកដមែន ផ្ទុយទៅវិញ បើមានជនណាអះអាងថា ជារថយន្តរបស់គាត់ នោះខ្ញុំបាទ/នាងខ្ញុំ សូមតទល់និងធានាអះអាងជំនួសចំពោះមុខច្បាប់ និងតុលាការ។</p>
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<p style="font-size: 10px;"><span style="font:10px; font-weight: bold;">អធិប្បាយនិងធានា: </span>: ខ្ញុំបាទ/នាងខ្ញុំ រថយន្តខាងលើ មានគ្រប់ឯកសារពាក់ព័ន្ធទាំងអស់ ដូចជា: 1. ពន្ធនាំចូល <span style="color:#F44336;">[មាន|មិនមាន]</span> 2. ពន្ធផ្លូវប្រចាំឆ្នាំ  <span style="color:#F44336;">[មាន|មិនមាន]</span>, . វិញ្ញាបនប័ត្រត្រួតពិនិត្យលក្ខណ:បចេក្ចទេសយានយន្ត <span style="color:#F44336;">[មាន|មិនមាន]</span>, និង 4. កាតគ្រី (កាតសំគាល់យានយន្ត) <span style="color:#F44336;">[មាន|មិនមាន]</span>។ រថយន្តនេះលក់ ក្នុងលក្ខណ:និងសភាពបច្ចុប្បន្ម មិនមាន ការធានាអ្វីទាំងអស់! បង់ប្រាក់ហើយមិនអាច ដូរយកប្រាក់វិញបានឡើយ!</p>
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<table class="padd" width="100%"  align="center" style="white-space:nowrap; border-collapse: collapse;">
										<tr align="center">
											<td width="20%">ស្នាមមេដៃស្តាំអ្នកទិញ</td>
											<td width="2%">&nbsp;</td>
											<td width="20%">ស្នាមមេដៃស្តាំសាក្សីអ្នកទិញ</td>
											<td width="2%">&nbsp;</td>
											<td width="20%">ស្នាមមេដៃស្តាំអ្នកទិញ</td>
											<td width="2%">&nbsp;</td>
											<td width="20%">ធ្វើនៅថ្ងៃទី 10   ខែ 10  ឆ្នាំ 2015</td>
										</tr>
										<tr align="center">
											<td colspan="4">&nbsp;</td>
											<td>សាក្សីអ្នកលក់</td>
											<td>&nbsp;</td>
											<td>ស្នាមមេដៃស្តាំអ្នកលក់</td>
										</tr>
										<tr align="center">
											<td colspan="5">&nbsp;</td>
										</tr>
										<tr align="center">
											<td colspan="5">&nbsp;</td>
										</tr>
										<tr align="center">
											<td width="20%" style="border-bottom: 1px solid #000;">&nbsp;</td>
											<td>&nbsp;</td>
											<td width="20%" style="border-bottom: 1px solid #000;">&nbsp;</td>
											<td>&nbsp;</td>
											<td width="20%" style="border-bottom: 1px solid #000;">&nbsp;</td>
											<td>&nbsp;</td>
											<td width="20%" style="border-bottom: 1px solid #000;">&nbsp;</td>
										</tr>
										<tr align="center">
											<td width="25%"><h4>នាមនិងគោត្តនាម</h4></td>
											<td>&nbsp;</td>
											<td width="25%"><h4>នាមនិងគោត្តនាម</h4></td>
											<td>&nbsp;</td>
											<td width="25%"><h4>នាមនិងគោត្តនាម</h4></td>
											<td>&nbsp;</td>
											<td width="25%"><h4>នាមនិងគោត្តនាម</h4></td>
										</tr>
									</table>
								</td>
							</tr>
					</table>
	</div>	
</div>

