<style>
#footer{display: none;}
</style>	
<div style="border: 1px dotted #000;background: #fff; margin: 0 auto;min-height: 27cm;">
		<div id="divPrint">
			<table style="background:#fff; margin: 0 auto; width: 100%; padding: 1cm; ">
							<tr>
								<td colspan="3" align="center">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="3" align="center">Vehicle Sales Report</td>
							</tr>
							<tr>
								<td colspan="3" align="center">&nbsp;</td>
							</tr>
							<tr>
								<td colspan="3">
									<style> th,td{ padding:0 1px;}</style>
										<style type="text/css">
											body{font-family: "Times New Roman",Arial; }
											table{ border-collapse:collapse; margin:0 auto;
											border-color:#000; }
											.padd tr td{  text-align:center}
											.padd tr th{  background-color: #EEEBEB;}
										</style>

									<table class="padd" width="99%" border="1" align="center" style="white-space:nowrap;">
										  <tr style="font-size:10px; height: 20px;" align="center">
										    <th>&nbsp;Date&nbsp;</th>
										    <th>&nbsp;Year&nbsp;</th>
										    <th>&nbsp;Make&nbsp;</th>
											<th>&nbsp;Model&nbsp;</th>
											<th>&nbsp;Sub-Model&nbsp;</th>
											<th>&nbsp;Plaque No&nbsp;</th>
											<th>&nbsp;Status&nbsp;</th>
											<th>&nbsp;Owner&nbsp;</th>
											<th>&nbsp;Contact&nbsp;</th>
											<th>&nbsp;Buyer&nbsp;</th>
											<th>&nbsp;Contact&nbsp;</th>
											<th>&nbsp;Price in US$&nbsp;</th>
											<th>&nbsp;Remark&nbsp;</th>
										  </tr>
										  <tr></tr>
												<style> td{padding:0 3px; }</style>
										  <tr style="font-size:10px; height: 18px;"​ align="center">
										    <td>15-03-2016</td>
										    <td>2017</td>
										    <td>Toyota</td>
										    <td>Corolla</td>
										    <td>LE</td>
										    <td>2AB-9988-PHP</td>
										    <td>New</td>
										    <td>Chatuchak Sorn</td>
										    <td>014 099 098</td>
										    <td>Chatuchak Sorn</td>
										    <td>014 099 098</td>
										    <td>50,000.00</td>
										    <td></td>
										  </tr>
										  <tr style="font-size:10px; height: 18px;"​ align="center">
										    <td>15-03-2016</td>
										    <td>2009</td>
										    <td>Lexus</td>
										    <td>RX</td>
										    <td>300</td>
										    <td>2VF-9898-PHP</td>
										    <td>2nd Hand</td>
										    <td>Chatuchak Sorn</td>
										    <td>014 099 098</td>
										    <td>Chatuchak Sorn</td>
										    <td>014 099 098</td>
										    <td>50,000.00</td>
										    <td></td>
										  </tr>
										   <tr style="font-size:10px; height: 18px;"​ align="center">
										    <td>15-03-2016</td>
										    <td>2017</td>
										    <td>Toyota</td>
										    <td>Corolla</td>
										    <td>LE</td>
										    <td>2AB-9988-PHP</td>
										    <td>New</td>
										    <td>Chatuchak Sorn</td>
										    <td>014 099 098</td>
										    <td>Chatuchak Sorn</td>
										    <td>014 099 098</td>
										    <td>50,000.00</td>
										    <td></td>
										  </tr>
										  <tr style="font-size:10px; height: 18px;"​ align="center">
										    <td>15-03-2016</td>
										    <td>2009</td>
										    <td>Lexus</td>
										    <td>RX</td>
										    <td>300</td>
										    <td>2VF-9898-PHP</td>
										    <td>2nd Hand</td>
										    <td>Chatuchak Sorn</td>
										    <td>014 099 098</td>
										    <td>Chatuchak Sorn</td>
										    <td>014 099 098</td>
										    <td>50,000.00</td>
										    <td></td>
										  </tr>
										  <tr style="font-size:10px; height: 18px;"​ align="center">
										  	<td colspan="10" style="border-left: #fff solid 1px; border-bottom:solid 1px #fff;"></td>
										  	<td>Total in US$:</td>
										  	<td style="background: #EEEBEB;">$200,000.00</td>
										  	<td colspan="10" style="border-right: #fff solid 1px; border-bottom:solid 1px #fff;"></td>
										  </tr>
										</table>
									</td>
								</tr>
							</table>
						
	</div>	
</div>

