<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("Vehicle Agreement"));
//$frm = $this->frm_holiday;
$url_invoice = $this->url(array("module"=>"agreement","controller"=>"carsale","action"=>"addreciept"),null,true);
?>
<div class="row">
	<div class="x_panel" >
		<table width="100%">
			<tr>
		   		<td align="right">
					<a href="<?php echo $url_invoice;?>" ><button iconClass="dijitEditorIcon dijitEditorIconSave" dojoType="dijit.form.Button">Add Receipt</button></a>
				</td>
		   	</tr>
		</table>
		<form id="list" name="list" action="<?php echo $this->url(array('module'=>'other','controller'=>'holiday','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
		   <table>
			  <tr> 
				   <td><?php //echo $frm->getElement("adv_search");?></td>
				   <td> <?php //echo $frm->getElement("start_date");?></td>
		           <td><?php //echo $frm->getElement("end_date");?></td>
				   <td><?php // $frm->getElement('search_status');?></td>
				   <td><!-- <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php //echo $tr->translate("SEARCH");?></button> --> </td>
		   	  </tr>
		   </table>
		</form>
		<?php echo $this->list;?>
	</div>
</div>
