<?php 
   $tr = Application_Form_FrmLanguages::getCurrentlanguage();
   echo $this->headTitle($tr->translate("Agentcy Payment"));
   $frm = $this->frm;
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dijit.form.DateTextBox");
dojo.require("dojo.data.ItemFileWriteStore"); 
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
 
dojo.require("dojo.html");
dojo.require("dojo.NodeList-manipulate");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.TimeTextBox");
dojo.require("dojo.parser");
 
</script>
<style>
div.cus_info{
	display: block;
    border: solid 1px #eee;
    clear: both;
    padding: 5px 2px;
    background: #f7f7f7;
}
.image-box.infor {
    padding: 2px;
    border: solid 1px #eee;
}		
span.span_title {
    min-width: 30%;
    display: inline-block;
    font-weight: 600;
}
h4.car_title {
    font-size: 14px;
    color: #156288;
    font-weight: 600;
    margin: 0;
    text-align: center;
    padding: 2px 0;
}
.head-td th {
    text-align: center;
}
th {
     text-align: center;
}

td {
     padding-left: 2px;
}
</style>
<div class="clearfix"></div>
<div class="x_panel">
	<div class="row">
		<form action="" method="post" id="addbookingrental" dojoType="dijit.form.Form">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					var agency = dijit.byId('agency').get('value');
					if(agency==0){
						alert("<?php echo $tr->translate('PLEASE_SELECT_AGENCY')?>");
						dijit.byId('agency').focus(); 
						return false;
					}
					var total_paid = dijit.byId('total_paid').get('value');
					if(total_paid>0){
						var payment_method = dijit.byId('payment_method').get('value');
						if(payment_method==0){
							alert("<?php echo $tr->translate('PLEASE_SELECT_PAYMENT_METHOD')?>");
							dijit.byId('payment_method').focus(); 
							return false;
						}
					}
					loading();
					return true;
				} else {
					return false;
				}
			</script>
      	 <div class="col-md-12 col-xs-12 forms_padding">
	          <div class="x_panel">
	              <div class="x_title">
	                 <h2><i class="fa  fa-info-circle" aria-hidden="true"></i> <?php echo $tr->translate('Agentcy Payment')?></h2>
	                 <ul class="nav navbar-right panel_toolbox">
	                    <li>
	                    	<a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
	                    </li>
	               	</ul>
               		<div class="clearfix"></div>
          		</div>
	       		<div class="x_content">
	       			<div class="col-md-8 col-sm-8 col-xs-12">
		                <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("RECIEPT_NO")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('reciept_no');?>
		                   </div>
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("AGENCY")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('agency');?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("PAYMENT_DATE")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('payment_date');?>
		                   </div>
		                    <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("PAYMENT_METHOD")?>
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                    	<?php echo $frm->getElement('payment_method');?>
		                   </div>
		                </div>
		            	  <div class="form-group">
	                   		   <label class="control-label col-md-2 col-sm-2 col-xs-4" for="first-name"><?php echo $tr->translate('BALANCE')?>
			                   </label>
			                  <div class="col-md-4 col-sm-4 col-xs-12">
			                    	<?php echo $frm->getElement('balance');?>
			                   </div>
			                   <label class="control-label col-md-2 col-sm-2 col-xs-12" for="first-name"><?php echo $tr->translate("AMOUNT")?>
			                   </label>
			                   <div class="col-md-4 col-sm-4 col-xs-12">
			                    	<?php echo $frm->getElement('amount');?>
			                   </div>
		                </div>
		                
	       			</div>
	       			<div class="col-md-4 col-sm-4 col-xs-12">
						<div class="title_form_blog " style=" margin: 0;">
	       					<h4 style=" font-size: 14px;"><i class="fa  fa-user" aria-hidden="true"></i> <?php echo $tr->translate('AGENCY_INFO')?></h4>
	       				</div>
	       				<div id="agent_info" class="cus_info col-md-12 col-sm-12 col-xs-12">
		       				<div class="col-md-4 col-sm-4 col-xs-12">
				               	<div class="image-box infor">
									<img id="profile_wiew" src="<?php echo $this->baseUrl().'/images/profile.jpg';?>" alt=""  />
								</div>
							</div>
							<div class="col-md-8 col-sm-8 col-xs-12">
								<ul class="list-unstyled">
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('NAME')?></span> : <span class="span_value"></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('Gender')?></span> : <span class="span_value"></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('Nationality')?></span> : <span class="span_value"></span>
                              		</li>
                              		<li>
                              			<span class="span_title"><?php echo $tr->translate('PHONE')?></span> : <span class="span_value"></span>
                              		</li>
                              	</ul>
							</div>
						</div>
						<div class="clearfix"></div>
	       			</div>
	       		</div>
	       		<div class="x_content">
	       		<!-- 
	       			<div class="col-md-12 col-sm-12 col-xs-12 bg" style="background: #dbe8f9;    padding: 10px;    margin: 10px 0;    border: solid 1px #ccc;">
		                  	
		                  	 <div class="col-md-12 col-sm-12 col-xs-12">
			                    <label class="control-label col-md-2 col-sm-2 col-xs-2" for="first-name"><?php echo $tr->translate('DATE')?></label>
			                	<div class="col-md-3 col-sm-3 col-xs-3">
			                    	<?php echo $frm->getElement('booking_date_start');?>
			                   </div>
			                    <label class="control-label col-md-2 col-sm-2 col-xs-2" for="first-name"><?php echo $tr->translate('TO')?></label>
			                   <div class="col-md-3 col-sm-3 col-xs-3">
			                    	<?php echo $frm->getElement('booking_date_end');?>
			                   </div>
			                    <div class="col-md-2 col-sm-2 col-xs-2">
			                    <input type="button" value="go" label="<?php echo $tr->translate('GO');?>" id="go_search" dojoType="dijit.form.Button" 
												iconClass="dijitEditorIcon dijitEditorIconPrint" onclick="getCommissionAgent();" />
			                    </div>
		                   </div>
		                   
		                   <div class="col-md-12 col-sm-12 col-xs-12">
			                   	<div class="col-md-2 col-sm-2 col-xs-2">
			                   		<input type="checkbox" class="checkbox"  name="check_all" id="check_all" value="all" OnChange="CheckAllTotal(0);" style=" height: initial; display: inline-block;"  />&nbsp;
									<span style="vertical-align: top;"><?php echo $tr->translate('ALL');?></span>
			                   	</div>
		                   </div>
		                  
	             	   </div>  -->
		                 
						<table id="table_parent" class="table" style="margin: 0 auto; width: 100%;  " >
							<thead>
								<tr>
									<td colspan="8">
										<table class="table" style=" border: 1px #ccc solid;  ">
											<thead>
											 
											</thead>
										<tbody  >
										     <div  id="showrecord"></div>
											<input type="text"  id="record_row" name="record_row" value="0"  dojoType="dijit.form.TextBox" />
										</tbody>
										</table>
										<input type="hidden" name="identity" id="identity"  value="" >
										<input type="hidden" name="old_identity" id="old_identity"  value="" >
									</td>
								</tr>
							</thead>
						</table>
						
						<div class="form-group">
		                   <div class="col-md-4 col-sm-4 col-xs-4">
		                    	<?php echo $frm->getElement('remark');?>
		                   </div>
		                    <div class="col-md-8 col-sm-8 col-xs-8">
		                   		<div class="col-md-12 col-sm-12 col-xs-12">
		                   		 <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('TOTAL_PAID')?>
				                   </label>
				                   <div class="col-md-8 col-sm-8 col-xs-8">
				                    	<?php echo $frm->getElement('total_paid');?>
				                   </div>
		                   		</div>
		                   		<div class="col-md-12 col-sm-12 col-xs-12">
		                   		 <label class="control-label col-md-4 col-sm-4 col-xs-4" for="first-name"><?php echo $tr->translate('TOTAL_DUE')?>
				                   </label>
				                   <div class="col-md-8 col-sm-8 col-xs-8">
				                    	<?php echo $frm->getElement('total_due');?>
				                   </div>
		                   		</div>
		                   </div>
		           	  	</div>
		               <div class="text-center">
							<input type="button" value="GO_BACK" label="<?php echo $tr->translate('GO_BACK');?>" id="back" dojoType="dijit.form.Button" 
										iconClass="dijitIconUndo" onclick="window.history.back();" />
							<input class="button_success" type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVE_CLOSE');?>" id="save_close" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 	
							<input class="button_success" type="submit" value="save_new" name="save_new" label="<?php echo $tr->translate('SAVE_NEW');?>" id="save_new" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 							
						</div>
	       		</div>
       		</div>
  		 </div>
     </form>
</div>
</div>

<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");
require(["dojo/ready"], function(ready){
	ready(function(){
	});
});

var urlagent="<?php echo $this->url(array('module'=>'bookings','controller'=>'commissionpayment','action'=>'getagent'));?>";
function getAgent(){
	var id = dijit.byId('agency').get('value');
	loading();
	dojo.xhrPost({
	    url: urlagent,
	    content:{
	     'agency':id
	     },
	    handleAs:"json",
	    load: function(data) {
	    	document.getElementById('agent_info').innerHTML =data;
			document.getElementsByClassName("overlay")[0].style.display="none";
	    },
	    error: function(err) {
	     alert(err);
	    }
	   });
}

function ResetPayment(){
	var old_identity = $("#old_identity").val();
	var rowIDArray = old_identity.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		dijit.byId('payment_amount'+rowIDArray[n]).set('value',0);
		amountrow = parseFloat(dijit.byId('commision_fee'+rowIDArray[n]).get('value'));
		
		amountrow = parseFloat(dijit.byId('remain'+rowIDArray[n]).set('value',amountrow.toFixed(2)));
	}
}
function calBalance() {
	var balance=0;
	var rowId = $('#old_identity').val();
	if(rowId==""){
		return false;
	}
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		//balance+= parseFloat(dijit.byId('due_val'+rowIDArray[n]).get('value'));
		if($('#mfdid_'+rowIDArray[n]).is(":checked")){
			amountrow = parseFloat(dijit.byId('commision_fee'+rowIDArray[n]).get('value'));
			balance = balance + parseFloat(amountrow);
		}
	}
	dijit.byId('balance').attr('value',balance.toFixed(2));
} 
 
function calculateLastTotal(){
	var rowId = $('#identity').val();
	if(rowId==""){
		return false;
	}
	var payment=0;
	var due = 0;
	var rowIDArray = rowId.split(',');
	for(var n = 0; n < rowIDArray.length; n++) {
		payment+= parseFloat(dijit.byId('payment_amount'+rowIDArray[n]).get('value'));
		due+= parseFloat(dijit.byId('remain'+rowIDArray[n]).get('value'));
	}
	dijit.byId('total_paid').attr('value',payment.toFixed(2));
	dijit.byId('total_due').attr('value',due.toFixed(2));
}
function calculateamount(index){
	var due = dijit.byId('commision_fee'+index).get('value');
	var payment = dijit.byId('payment_amount'+index).get('value');
	var paid =0;
	var subtotal=0;
	paid = parseFloat(payment);
	subtotal= parseFloat(due);
	
	if(paid > subtotal){
		dijit.byId('payment_amount'+index).set('value',subtotal.toFixed(2));
		dijit.byId('remain'+index).set('value',0);
	}else{
		dijit.byId('remain'+index).set('value',(subtotal-paid).toFixed(2));
	}
	calBalance();
	calculateAmountCheckByKeyup();
}

function calculateAmountCheckByKeyup(){
	var rowId = $('#identity').val();
	if(rowId==""){
		return false;
	}
	var payment=0;
	var amount = 0;
	var due = 0;
	var amountrow = 0;
	var rowIDArray = rowId.split(',');
		for(var n = 0; n < rowIDArray.length; n++) {
			payment+= parseFloat(dijit.byId('payment_amount'+rowIDArray[n]).get('value'));
			due+= parseFloat(dijit.byId('remain'+rowIDArray[n]).get('value'));
		}
	amount = parseFloat(payment).toFixed(2);
	dijit.byId('total_paid').attr('value',payment.toFixed(2));
	dijit.byId('total_due').attr('value',due.toFixed(2));
	dijit.byId('amount').attr('value',parseFloat(amount).toFixed(2));
}

function deleteRecord(index) {
	var identity = $('#record_row').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#record_row').val(strings);
	$("#row_capital"+index).remove();
	//netTotal();
}
 
url_getagentcy = '<?php echo $this->url(array('module'=>'bookings','controller'=>'agentcypayment','action'=>'get-agentcy-payments'));?>';
r=0;
function getAllAgentcyPayment(){
	fund_title=0;
	temp='';
	agency_id  = dijit.byId('agency').get('value');
	dojo.query("#showrecord").append('');
	tmp='<table id="t_amountmoneytype" width="100%" style=" margin-top: 20px; border-collapse: collapse;border:1px solid #bdbdbd;" border="" >';
	tmp+='<tr  style="background:#eee;border:1px solid #bdbdbd;  font-size: 12px; height: 40px;font-weight: bold; margin-bottom: 10px;text-align: center;" id="head_title" class="head-title"></tr>';
	tmp+='</table>';
	dojo.query("#showrecord").append(tmp);
	dojo.xhrPost({
		url: url_getagentcy,
		content:{
			'agency_id':agency_id
		},
		handleAs:"json",
		load: function(data){
			alert(data);
			dijit.byId('record_row').attr('value','');
			if(data==''){
				thead='<th style="margin-bottom: 20px;"><?php echo $tr->translate("DEL");?></th>';
				thead+='<th><?php echo $tr->translate("NUM");?></th>';
				thead+='<th><?php echo $tr->translate("BOOKING_NO");?></th>';
				thead+='<th ><?php echo $tr->translate("CUSTOMER_NAME");?></th>';
				thead+='<th ><?php echo $tr->translate("BOOKING_DATE");?></th>';
				thead+='<th><?php echo $tr->translate("TOTAL");?></th>';
				thead+=' <th><?php echo $tr->translate("COMMISSION_FEE");?></th>';
				thead+='<th><?php echo $tr->translate("PAID");?></th>';
				thead+='<th><?php echo $tr->translate("PAYMENT_AMOUNT");?></th>';
				thead+='<th><?php echo $tr->translate("BALANCE");?></th>';
				thead+='<th><?php echo $tr->translate("TOTAL_AGENTCY");?></th>';
				thead+='<th><?php echo $tr->translate("TOTAL_OWNER");?></th>';
				fund_title=1;
				dojo.query("#head_title").append(thead);
			}
			for(i=0;i<data.length;i++){  
				r++;
				if(fund_title!=1){
					thead='<th style="margin-bottom: 20px;"><?php echo $tr->translate("DEL");?></th>';
					thead+='<th><?php echo $tr->translate("NUM");?></th>';
					thead+='<th><?php echo $tr->translate("BOOKING_NO");?></th>';
					thead+='<th style="margin-left:0px;width:200px;"><?php echo $tr->translate("CUSTOMER_NAME");?></th>';
					thead+='<th ><?php echo $tr->translate("BOOKING_DATE");?></th>';
					thead+='<th><?php echo $tr->translate("COMMISSION_FEE");?></th>';
					thead+='<th><?php echo $tr->translate("TOTAL");?></th>';
					thead+='<th><?php echo $tr->translate("PAID");?></th>';
					thead+='<th><?php echo $tr->translate("PAYMENT_AMOUNT");?></th>';
					thead+='<th><?php echo $tr->translate("BALANCE");?></th>';
					thead+='<th><?php echo $tr->translate("TOTAL_AGENTCY");?></th>';
					thead+='<th><?php echo $tr->translate("TOTAL_OWNER");?></th>';
					fund_title=1;
					dojo.query("#head_title").append(thead);
				}
				temp='<td><img style="cursor:pointer" onclick="deleteRecord('+r+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
				temp+='<td>'+r+'</td>';
				temp+='<td>'+data[i].booking_no+'</td>';
				temp+='<td nowrap>'+data[i].last_name+'</td>';
				temp+='<td nowrap>'+data[i].booking_date+'</td>';
				temp+='<td><input  style="margin-left:0px;width:100px;"  type="text" data-dojo-props="constraints:{places:0}" value="'+data[i].commision_fee_after+'"    name="commission_fee_'+r+'" id="commission_fee_'+r+'" dojoType="dijit.form.NumberTextBox" onkeyup=" " readonly="true"/></td>';
				temp+='<td><input  style="margin-left:0px;width:100px;"  type="text" data-dojo-props="constraints:{places:0}" value="'+data[i].totals+'"    name="total_'+r+'" id="total_'+r+'" dojoType="dijit.form.NumberTextBox" onkeyup=" " readonly="true"/></td>';
				temp+='<td><input  style="margin-left:0px;width:100px;"  type="text" data-dojo-props="constraints:{places:0}" value="'+data[i].paid_after+'" name="paid_'+r+'" id="paid_'+r+'" dojoType="dijit.form.NumberTextBox" readonly="true" onkeyup=" "  /></td>';
				temp+='<td><input  style="margin-left:0px;width:100px;"  type="text" data-dojo-props="constraints:{places:0}" value="'+data[i].borr_qty+'"   name="payment_amount'+r+'"  id="payment_amount'+r+'" dojoType="dijit.form.NumberTextBox" onkeyup=" " required/></td>';
				temp+='<td><input  style="margin-left:0px;width:100px;"  type="text" data-dojo-props="constraints:{places:0}" value="'+data[i].balance_after+'" name="balance_'+r+'"     id="balance_'+r+'" dojoType="dijit.form.NumberTextBox" onkeyup=" "  readonly="true"  /></td>';
				temp+='<td><input  style="margin-left:0px;width:100px;"  type="text" data-dojo-props="constraints:{places:0}" value="'+data[i].borr_qty+'"   name="total_agentcy_'+r+'"  id="total_agentcy_'+r+'" dojoType="dijit.form.NumberTextBox" onkeyup=" " readonly="true"  /></td>';
				temp+='<td><input  style="margin-left:0px;width:100px;"  type="text" data-dojo-props="constraints:{places:0}" value="'+data[i].borr_qty+'"   name="total_owner_'+r+'"    id="total_owner_'+r+'" dojoType="dijit.form.NumberTextBox"  onkeyup=" " readonly="true"  /></td>';
				tmp='<tr style="border:1px solid #bdbdbd; font-size:12px;height:37px; !important;text-align:center;" id="row_capital'+r+'" >'
				tmp+="</tr>";
				dojo.query("#t_amountmoneytype").append(tmp);
				dojo.html.set(dojo.byId("row_capital"+r),temp, {
					parseContent: true,
				});
				if(dijit.byId("record_row").get('value')!="") {
					var ids = dijit.byId("record_row").get("value");
					dijit.byId("record_row").attr('value',ids+','+r);
				}
				else { dijit.byId("record_row").attr('value',r);
				}
			}
		},error: function(err) {
		}
	});
}

</script>
